(in-package #:rimefall)
(eval-when (:compile-toplevel :load-toplevel :execute)
  (sb-ext:add-package-local-nickname :grafico :lwlgl.opengl.gl33 :rimefall)
  (sb-ext:add-package-local-nickname :janela :lwlgl.glfw :rimefall)
  (sb-ext:add-package-local-nickname :entrada :lwlgl.input :rimefall)
  (sb-ext:add-package-local-nickname :som :lwlgl.openal :rimefall))

;;; Um único formato de vértice atende cenário, objetos, arma e letras.
(defparameter *programa-vertices*
"#version 330 core
layout(location=0) in vec3 posicao;
layout(location=1) in vec4 cor;
uniform mat4 matriz;
uniform vec3 olho;
out vec4 tonalidade;
out float distancia;
void main() {
  gl_Position = matriz * vec4(posicao, 1.0);
  tonalidade = cor;
  distancia = gl_Position.w;
}")
(defparameter *programa-fragmentos*
"#version 330 core
in vec4 tonalidade;
in float distancia;
uniform float neblina;
uniform float inicio;
uniform float fim;
out vec4 resultado;
void main() {
  float mistura = smoothstep(inicio, fim, distancia) * neblina;
  resultado = vec4(mix(tonalidade.rgb, vec3(0.47,0.56,0.61), mistura), tonalidade.a);
}")
(defstruct (malha (:constructor %criar-malha) (:predicate malha-p) (:copier copiar-malha))
  arranjo memoria (quantidade 0))
(defvar *vertices*)
(defvar *botoes* nil)
(defvar *foco* :entrar)
(defvar *historico-aberto* nil)
(defvar *pagina-historico* 0)
(defvar *pagina-evidencias* 0)
(defvar *diario-historico* nil)
(defvar *linha-diario* 0)
(defvar *edicao-diario* nil)
(defvar *mapa-aberto* nil)
(defvar *configuracoes-abertas* nil)
(defvar *remapeando* nil)
(defvar *celula-mapa* '(0 . 11))
(defvar *texto-marca* "")
(defvar *editando-marca* nil)

(defvar *fontes-sonoras* nil)
(defvar *amostras* nil)
(defvar *audio-ativo* nil)
(defparameter *gelo* '(0.83 0.89 0.89 1.0))
(defparameter *apagado* '(0.47 0.58 0.60 1.0))
(defparameter *destaque* '(0.85 0.69 0.39 1.0))
(defparameter *painel* '(0.045 0.074 0.089 0.97))
;; Paleta de interface inspirada em quadros de comando militares: carvão,
;; verde-oliva e bronze para estados de foco e confirmação.
(defparameter *carvao-menu* '(0.035 0.043 0.037 0.98))
(defparameter *oliva-menu* '(0.115 0.145 0.115 0.98))
(defparameter *oliva-foco* '(0.24 0.29 0.21 1.0))
(defparameter *bronze-menu* '(0.73 0.56 0.28 1.0))

(defun iniciar-vertices ()
  (make-array 100000 :element-type 'single-float :adjustable t :fill-pointer 0))
(defun vertice (x y z cor)
  (dolist (valor (list x y z (first cor) (second cor) (third cor) (or (fourth cor) 1.0)))
    (vector-push-extend (float valor 1.0) *vertices*)))
(defun triangulo (primeiro segundo terceiro cor)
  (dolist (ponto (list primeiro segundo terceiro))
    (vertice (first ponto) (second ponto) (third ponto) cor)))
(defun quadrilatero (primeiro segundo terceiro quarto cor)
  (triangulo primeiro segundo terceiro cor) (triangulo primeiro terceiro quarto cor))
(defun tonalizar (cor intensidade)
  (list (* (first cor) intensidade) (* (second cor) intensidade) (* (third cor) intensidade)
        (or (fourth cor) 1.0)))
(defun caixa (x y z largura altura profundidade cor)
  (let* ((esquerda (- x (/ largura 2))) (direita (+ x (/ largura 2)))
         (baixo (- y (/ altura 2))) (cima (+ y (/ altura 2)))
         (frente (+ z (/ profundidade 2))) (fundo (- z (/ profundidade 2)))
         (pontos (vector (list esquerda baixo frente) (list direita baixo frente)
                         (list direita cima frente) (list esquerda cima frente)
                         (list esquerda baixo fundo) (list direita baixo fundo)
                         (list direita cima fundo) (list esquerda cima fundo))))
    (loop for indices in '((0 1 2 3) (5 4 7 6) (4 0 3 7) (1 5 6 2) (3 2 6 7) (4 5 1 0))
          for intensidade in '(0.80 0.64 0.70 0.91 1.12 0.50)
          do (apply #'quadrilatero
                    (append (mapcar (lambda (indice) (aref pontos indice)) indices)
                            (list (tonalizar cor intensidade)))))))
(defun retangulo (x y largura altura cor)
  (quadrilatero (list x y 0) (list (+ x largura) y 0)
                (list (+ x largura) (+ y altura) 0) (list x (+ y altura) 0) cor))
(defun moldura (x y largura altura cor)
  "Desenha uma moldura fina para painéis de briefing."
  (retangulo x y largura 2 cor)
  (retangulo x (+ y altura -2) largura 2 cor)
  (retangulo x y 2 altura cor)
  (retangulo (+ x largura -2) y 2 altura cor))

(defun criar-malha ()
  (let ((malha (%criar-malha :arranjo (lwlgl.opengl:make-vertex-array) :memoria (lwlgl.opengl:make-buffer))))
    (grafico:gl-bind-vertex-array (malha-arranjo malha))
    (grafico:gl-bind-buffer grafico:+gl-array-buffer+ (malha-memoria malha))
    (grafico:gl-vertex-attrib-pointer 0 3 grafico:+gl-float+ 0 28 (cffi:null-pointer))
    (grafico:gl-enable-vertex-attrib-array 0)
    (grafico:gl-vertex-attrib-pointer 1 4 grafico:+gl-float+ 0 28 (cffi:make-pointer 12))
    (grafico:gl-enable-vertex-attrib-array 1)
    malha))
(defun enviar-malha (malha &optional (uso grafico:+gl-dynamic-draw+))
  (setf (malha-quantidade malha) (/ (length *vertices*) 7))
  (grafico:gl-bind-vertex-array (malha-arranjo malha))
  (grafico:gl-bind-buffer grafico:+gl-array-buffer+ (malha-memoria malha))
  (lwlgl.opengl:upload-floats grafico:+gl-array-buffer+ *vertices* uso))
(defun desenhar-malha (malha)
  (grafico:gl-bind-vertex-array (malha-arranjo malha))
  (grafico:gl-draw-arrays grafico:+gl-triangles+ 0 (malha-quantidade malha)))
(defun destruir-malha (malha)
  (lwlgl.opengl:delete-buffer (malha-memoria malha))
  (lwlgl.opengl:delete-vertex-array (malha-arranjo malha)))
(defun localizar-uniforme (programa nome)
  (cffi:with-foreign-string (ponteiro nome) (grafico:gl-get-uniform-location programa ponteiro)))

;;; Fonte bitmap autoral: sem dependências de fontes ou recursos externos.
(defparameter *glifos*
  '((#\A "01110" "10001" "10001" "11111" "10001" "10001" "10001")
    (#\B "11110" "10001" "10001" "11110" "10001" "10001" "11110")
    (#\C "01111" "10000" "10000" "10000" "10000" "10000" "01111")
    (#\D "11110" "10001" "10001" "10001" "10001" "10001" "11110")
    (#\E "11111" "10000" "10000" "11110" "10000" "10000" "11111")
    (#\F "11111" "10000" "10000" "11110" "10000" "10000" "10000")
    (#\G "01111" "10000" "10000" "10111" "10001" "10001" "01111")
    (#\H "10001" "10001" "10001" "11111" "10001" "10001" "10001")
    (#\I "11111" "00100" "00100" "00100" "00100" "00100" "11111")
    (#\J "00111" "00010" "00010" "00010" "10010" "10010" "01100")
    (#\K "10001" "10010" "10100" "11000" "10100" "10010" "10001")
    (#\L "10000" "10000" "10000" "10000" "10000" "10000" "11111")
    (#\M "10001" "11011" "10101" "10101" "10001" "10001" "10001")
    (#\N "10001" "11001" "10101" "10011" "10001" "10001" "10001")
    (#\O "01110" "10001" "10001" "10001" "10001" "10001" "01110")
    (#\P "11110" "10001" "10001" "11110" "10000" "10000" "10000")
    (#\Q "01110" "10001" "10001" "10001" "10101" "10010" "01101")
    (#\R "11110" "10001" "10001" "11110" "10100" "10010" "10001")
    (#\S "01111" "10000" "10000" "01110" "00001" "00001" "11110")
    (#\T "11111" "00100" "00100" "00100" "00100" "00100" "00100")
    (#\U "10001" "10001" "10001" "10001" "10001" "10001" "01110")
    (#\V "10001" "10001" "10001" "10001" "10001" "01010" "00100")
    (#\W "10001" "10001" "10001" "10101" "10101" "10101" "01010")
    (#\X "10001" "10001" "01010" "00100" "01010" "10001" "10001")
    (#\Y "10001" "10001" "01010" "00100" "00100" "00100" "00100")
    (#\Z "11111" "00001" "00010" "00100" "01000" "10000" "11111")
    (#\0 "01110" "10001" "10011" "10101" "11001" "10001" "01110")
    (#\1 "00100" "01100" "00100" "00100" "00100" "00100" "01110")
    (#\2 "01110" "10001" "00001" "00010" "00100" "01000" "11111")
    (#\3 "11110" "00001" "00001" "01110" "00001" "00001" "11110")
    (#\4 "00010" "00110" "01010" "10010" "11111" "00010" "00010")
    (#\5 "11111" "10000" "10000" "11110" "00001" "00001" "11110")
    (#\6 "01110" "10000" "10000" "11110" "10001" "10001" "01110")
    (#\7 "11111" "00001" "00010" "00100" "01000" "01000" "01000")
    (#\8 "01110" "10001" "10001" "01110" "10001" "10001" "01110")
    (#\9 "01110" "10001" "10001" "01111" "00001" "00001" "01110")
    (#\. "00000" "00000" "00000" "00000" "00000" "00110" "00110")
    (#\, "00000" "00000" "00000" "00000" "00110" "00100" "01000")
    (#\: "00000" "00110" "00110" "00000" "00110" "00110" "00000")
    (#\; "00000" "00110" "00110" "00000" "00110" "00100" "01000")
    (#\- "00000" "00000" "00000" "11111" "00000" "00000" "00000")
    (#\+ "00000" "00100" "00100" "11111" "00100" "00100" "00000")
    (#\/ "00001" "00001" "00010" "00100" "01000" "10000" "10000")
    (#\! "00100" "00100" "00100" "00100" "00100" "00000" "00100")
    (#\? "01110" "10001" "00001" "00010" "00100" "00000" "00100")
    (#\[ "01110" "01000" "01000" "01000" "01000" "01000" "01110")
    (#\] "01110" "00010" "00010" "00010" "00010" "00010" "01110")
    (#\( "00010" "00100" "01000" "01000" "01000" "00100" "00010")
    (#\) "01000" "00100" "00010" "00010" "00010" "00100" "01000")
    (#\' "00100" "00100" "00000" "00000" "00000" "00000" "00000")
    (#\= "00000" "00000" "11111" "00000" "11111" "00000" "00000")
    (#\_ "00000" "00000" "00000" "00000" "00000" "00000" "11111")))

(defun desenhar-texto (texto x y &optional (escala 2) (cor *gelo*))
  (loop for caractere across (string-upcase texto) for coluna from 0
        for base = (or (cdr (assoc caractere '((#\Á . #\A) (#\À . #\A) (#\Ã . #\A) (#\Â . #\A)
                                               (#\É . #\E) (#\Ê . #\E) (#\Í . #\I) (#\Ó . #\O)
                                               (#\Ô . #\O) (#\Õ . #\O) (#\Ú . #\U) (#\Ü . #\U) (#\Ç . #\C)))) caractere)
        for linhas = (cdr (assoc base *glifos*))
        for origem = (+ x (* coluna 6 escala))
        do (loop for linha in linhas for altura from 0
                 do (loop for pixel across linha for largura from 0
                          when (char= pixel #\1)
                          do (retangulo (+ origem (* largura escala)) (+ y (* altura escala)) escala escala cor)))
           (when (find caractere "ÁÉÍÓÚ")
             (retangulo (+ origem (* 3 escala)) (- y (* 2 escala)) escala escala cor)
             (retangulo (+ origem (* 2 escala)) (- y escala) escala escala cor))
           (when (find caractere "ÂÊÔ")
             (retangulo (+ origem (* 2 escala)) (- y (* 2 escala)) escala escala cor)
             (retangulo (+ origem escala) (- y escala) escala escala cor)
             (retangulo (+ origem (* 3 escala)) (- y escala) escala escala cor))
           (when (char= caractere #\À)
             (retangulo (+ origem escala) (- y (* 2 escala)) escala escala cor)
             (retangulo (+ origem (* 2 escala)) (- y escala) escala escala cor))
           (when (find caractere "ÃÕ")
             (retangulo (+ origem escala) (- y (* 2 escala)) (* 2 escala) escala cor)
             (retangulo (+ origem (* 2 escala)) (- y escala) (* 2 escala) escala cor))
           (when (char= caractere #\Ü)
             (retangulo (+ origem escala) (- y (* 2 escala)) escala escala cor)
             (retangulo (+ origem (* 3 escala)) (- y (* 2 escala)) escala escala cor))
           (when (char= caractere #\Ç)
             (retangulo (+ origem (* 2 escala)) (+ y (* 7 escala)) escala escala cor))))

(defun linhas-texto (texto limite)
  (let ((linhas nil) (inicio 0) (tamanho (length texto)))
    (loop while (< inicio tamanho)
          for fim = (min tamanho (+ inicio limite))
          for quebra = (position #\Newline texto :start inicio :end fim)
          do (when quebra (setf fim quebra))
             (when (and (not quebra) (< fim tamanho))
               (let ((espaco (position #\Space texto :start inicio :end fim :from-end t)))
                 (when (and espaco (> espaco inicio)) (setf fim espaco))))
             (push (subseq texto inicio fim) linhas)
             (setf inicio (if (and (< fim tamanho) (find (char texto fim) '(#\Space #\Newline))) (1+ fim) fim)))
    (nreverse linhas)))
(defun paragrafo (texto x y limite &optional (cor *apagado*) (escala 2) (maximo 20))
  (loop for linha in (linhas-texto texto limite) for indice below maximo
        do (desenhar-texto linha x (+ y (* indice (+ 8 (* 7 escala)))) escala cor)))

(defvar *modelos* nil)
(defvar *pasta-modelos* nil)
(defun carregar-modelos ()
  (let ((modelos (make-hash-table :test #'equal)))
    (dolist (nome (append '("posto" "guerra" "criatura" "perna-esquerda" "perna-direita" "fuzil" "escopeta" "suprimento" "braco-esquerdo" "braco-direito" "braco-criatura-esquerdo" "braco-criatura-direito" "corpo" "isca" "clarao" "chamador" "porta" "temporizador" "bipe" "ferrolho" "telha" "carabina" "submetralhadora" "culatra" "culatra-submetralhadora" "carregador-submetralhadora" "cartucho" "precisao" "franco-atirador" "culatra-precisao" "ferrolho-longo"
                           "metralhadora" "pistola" "morteiro" "radio-campo" "caminhao"
                           "soldado-aurora-fuzileiro" "soldado-aurora-medico" "soldado-aurora-suporte" "soldado-aurora-engenheiro" "soldado-aurora-comandante"
                           "soldado-bruma-fuzileiro" "soldado-bruma-medico" "soldado-bruma-suporte" "soldado-bruma-engenheiro" "soldado-bruma-comandante"
                           "monstro-rastreador" "monstro-couracado" "monstro-enxame"
                           "primeira-pessoa-aurora-esquerdo" "primeira-pessoa-aurora-direito"
                           "primeira-pessoa-bruma-esquerdo" "primeira-pessoa-bruma-direito")
                         (loop for lado in '("aurora" "bruma") append
                           (loop for funcao in '("fuzileiro" "medico" "suporte" "engenheiro" "comandante") append
                             (loop for parte in '("tronco" "perna-esquerda" "perna-direita" "braco-esquerdo" "braco-direito")
                                   collect (format nil "soldado-~A-~A-~A" lado funcao parte))))))
      (let* ((caminho (merge-pathnames (format nil "~A.malha" nome)
                                     (or *pasta-modelos* (asdf:system-relative-pathname "rimefall" "modelos/"))))
             (*read-eval* nil)
             (dados (with-open-file (arquivo caminho) (read arquivo)))
             (*vertices* (make-array (length dados) :element-type 'single-float)))
        (unless (and (vectorp dados) (zerop (mod (length dados) 7)))
          (error "Malha inválida: ~A" caminho))
        (dotimes (indice (length dados)) (setf (aref *vertices* indice) (float (aref dados indice) 1.0)))
        (let ((malha (criar-malha)))
          (enviar-malha malha grafico:+gl-static-draw+)
          (setf (gethash nome modelos) malha))))
    modelos))
(defun compor-matrizes (&rest matrizes) (reduce #'lwlgl.math:mat4-mul matrizes))
(defun desenhar-modelo (nome matriz uniforme)
  (lwlgl.opengl:set-uniform-mat4 uniforme matriz)
  (desenhar-malha (gethash nome *modelos*)))

(defun nome-modelo-arma-guerra (arma)
  (case arma
    (:metralhadora "metralhadora") (:pistola "pistola") (:morteiro "morteiro")
    (:carabina "carabina") (:escopeta "escopeta") (:precisao "precisao")
    (:franco-atirador "franco-atirador") (otherwise "fuzil")))

(defun nome-modelo-soldado-guerra (jogador)
  (format nil "soldado-~A-~A"
          (if (eq (exercito-id (jogador-guerra-exercito jogador)) :aurora) "aurora" "bruma")
          (string-downcase (symbol-name (jogador-guerra-funcao jogador)))))

(defun desenhar-entidade-guerra (base nome x z angulo uniforme &optional (altura 0.0))
  (desenhar-modelo nome
                  (compor-matrizes base
                    ;; O mapa é comprimido para caber na câmera; as entidades
                    ;; usam a mesma conversão de metros para posição e tamanho.
                    (lwlgl.math:translation-mat4 (* .08 x) (* .08 altura) (* .08 z))
                    (lwlgl.math:rotation-y-mat4 (- angulo))
                    (lwlgl.math:scale-mat4 .08 .08 .08))
                  uniforme))

(defun desenhar-campo-guerra (guerra projecao visao uniforme)
  "Desenha o mapa principal e todas as entidades visíveis da batalha."
  (let ((base (lwlgl.math:mat4-mul projecao visao)))
    (desenhar-modelo "guerra"
                     (compor-matrizes base (lwlgl.math:scale-mat4 .08 .08 .08))
                     uniforme)
    (dolist (jogador (guerra-jogadores guerra))
      (unless (or (eq jogador (jogador-local-guerra guerra)) (eq (jogador-guerra-estado jogador) :morto))
        ;; A animação completa fica reservada aos combatentes próximos; os
        ;; demais usam a malha completa para manter a frente legível em hardware
        ;; modesto sem alterar a simulação.
        (let ((distancia (sqrt (+ (expt (- (jogador-guerra-x jogador)
                                           (jogador-guerra-x (jogador-local-guerra guerra))) 2)
                                  (expt (- (jogador-guerra-z jogador)
                                           (jogador-guerra-z (jogador-local-guerra guerra))) 2)))))
          (desenhar-soldado-articulado guerra jogador base uniforme (< distancia 65.0)))))
    (dolist (veiculo (guerra-veiculos guerra))
      (when (plusp (veiculo-guerra-vida veiculo))
        (desenhar-entidade-guerra base "caminhao" (veiculo-guerra-x veiculo)
                                  (veiculo-guerra-z veiculo) 0.0 uniforme .75)))
    (dolist (morteiro (guerra-morteiros guerra))
      (desenhar-entidade-guerra base "morteiro" (morteiro-guerra-x morteiro)
                                (morteiro-guerra-z morteiro) 0.0 uniforme .05)
      (when (morteiro-guerra-operador morteiro)
        (desenhar-entidade-guerra base "radio-campo" (morteiro-guerra-x morteiro)
                                  (morteiro-guerra-z morteiro) 0.0 uniforme .65)))
    (let ((invasao (guerra-invasao guerra)))
      (when invasao
        (dolist (monstro (invasao-guerra-monstros invasao))
          (when (plusp (monstro-guerra-vida monstro))
            (desenhar-entidade-guerra
             base (case (mod (monstro-guerra-id monstro) 3)
                    (0 "monstro-rastreador") (1 "monstro-couracado")
                    (otherwise "monstro-enxame"))
             (monstro-guerra-x monstro) (monstro-guerra-z monstro) 0.0 uniforme)))))))

(defun desenhar-efeitos-guerra (guerra projecao visao uniforme dinamica)
  (setf (fill-pointer *vertices*) 0)
  (dolist (efeito (guerra-efeitos guerra))
    (let ((origem (second efeito)) (destino (third efeito)))
      (loop for indice from 1 to 10 for fracao = (/ indice 10.0)
            do (caixa (* .08 (+ (first origem) (* fracao (- (first destino) (first origem)))))
                      (* .08 (+ (second origem) (* fracao (- (second destino) (second origem)))))
                      (* .08 (+ (third origem) (* fracao (- (third destino) (third origem)))))
                      .006 .006 .035 '(1.0 .72 .31 1.0)))))
  (lwlgl.opengl:set-uniform-mat4 uniforme (compor-matrizes projecao visao))
  (enviar-malha dinamica) (desenhar-malha dinamica))

(defun desenhar-soldado-articulado (guerra jogador base uniforme &optional (articulado t))
  (declare (ignore guerra))
  (let* ((nome (nome-modelo-soldado-guerra jogador))
         (ativo (jogador-ativo-p jogador))
         (passo (if ativo (* .38 (jogador-guerra-movimento jogador)
                            (sin (jogador-guerra-passada jogador))) 0.0))
         (matriz (compor-matrizes base
                    (lwlgl.math:translation-mat4 (* .08 (jogador-guerra-x jogador))
                      (if ativo 0.0 (* .08 .39)) (* .08 (jogador-guerra-z jogador)))
                    (lwlgl.math:rotation-y-mat4 (- (jogador-guerra-angulo jogador)))
                    (lwlgl.math:scale-mat4 .08 (if (and ativo (jogador-guerra-agachado jogador)) .052 .08) .08)
                    (lwlgl.math:rotation-x-mat4 (if ativo 0.0 (float (/ pi 2) 1.0))))))
    (if articulado
        (progn
          (desenhar-modelo (concatenate 'string nome "-tronco") matriz uniforme)
          (loop for parte in '("perna-esquerda" "perna-direita" "braco-esquerdo" "braco-direito")
                for lateral in '(-.13 .13 -.255 .255) for altura in '(.86 .86 1.42 1.42)
                for amplitude in (list passo (- passo) (* -.04 passo) (* -.04 passo))
                do (desenhar-modelo (format nil "~A-~A" nome parte)
                      (compor-matrizes matriz (lwlgl.math:translation-mat4 lateral altura 0)
                       (lwlgl.math:rotation-x-mat4 amplitude)
                       (lwlgl.math:translation-mat4 (- lateral) (- altura) 0)) uniforme)))
        (desenhar-modelo nome matriz uniforme))
    (desenhar-modelo (nome-modelo-arma-guerra (jogador-guerra-arma jogador))
                     (compor-matrizes matriz (lwlgl.math:translation-mat4 .1 1.20 -.30)) uniforme)
    (when (plusp (jogador-guerra-clarão jogador))
      (desenhar-modelo "clarao" (compor-matrizes matriz (lwlgl.math:translation-mat4 .1 1.2 -1.1)) uniforme))))

(defun desenhar-corpo-soldado (base x z uniforme)
  "Usa o modelo articulado de um fuzileiro como corpo recuperável do tutorial."
  (let* ((nome "soldado-aurora-fuzileiro")
         (matriz (compor-matrizes base
                    (lwlgl.math:translation-mat4 x .34 z)
                    (lwlgl.math:rotation-x-mat4 (float (/ pi 2) 1.0)))))
    (desenhar-modelo (concatenate 'string nome "-tronco") matriz uniforme)
    (loop for parte in '("perna-esquerda" "perna-direita" "braco-esquerdo" "braco-direito")
          for lado in '(-1 1 -1 1) for altura in '(.86 .86 1.42 1.42)
          do (desenhar-modelo (format nil "~A-~A" nome parte)
                (compor-matrizes matriz (lwlgl.math:translation-mat4 (* lado .18) altura 0)
                 (lwlgl.math:rotation-y-mat4 (if (> lado 0) -.08 .08))
                 (lwlgl.math:translation-mat4 (* lado -.18) (- altura) 0)) uniforme))))

(defparameter *duracao-entrada-mira* .30)
(defparameter *duracao-saida-mira* .22)

(defun avancar-mira (progresso mirando intervalo)
  "Progresso visual em segundos; pode inverter de direção sem reiniciar."
  (limitar (+ progresso (* (if mirando 1.0 -1.0)
                          (/ (max 0.0 intervalo)
                             (if mirando *duracao-entrada-mira* *duracao-saida-mira*)))) 0.0 1.0))

(defun suavizar-mira (progresso)
  "Acelera e desacelera a elevação da arma, chegando exatamente aos extremos."
  (* progresso progresso (- 3.0 (* 2.0 progresso))))

(defun mira-solicitada-p (sessao)
  (if (eq (sessao-fase sessao) :guerra)
      (let ((jogador (jogador-local-guerra *guerra-atual*)))
        (and jogador (jogador-ativo-p jogador) (jogador-guerra-mirando jogador)
             (zerop (jogador-guerra-tempo-recarga jogador))))
      (let ((soldado (sessao-soldado sessao)))
        (and (member (sessao-fase sessao) '(:combate :pausa)) soldado
             (soldado-mirando soldado) (zerop (soldado-recarga soldado))
             (zerop (soldado-troca soldado))))))

(defun campo-visao-mira (campo mira arma guerra)
  "O mesmo fator anima câmera e arma; mantém a ampliação própria do tutorial."
  (let* ((ampliacao (if guerra 1.0 (ampliacao-arma arma)))
         (destino (cond (guerra 48.0) ((> ampliacao 1.0) (/ campo ampliacao))
                        (t (- campo 20.0)))))
    (+ campo (* mira (- destino campo)))))

(defun desenhar-arma-guerra (jogador proporcao uniforme mira)
  "Recuo, respiração, passos, ferrolho e troca de carregador em primeira pessoa."
  (when (jogador-ativo-p jogador)
    (let* ((recuo (jogador-guerra-recuo jogador))
           (recarga (if (plusp (jogador-guerra-tempo-recarga jogador))
                        (sin (* pi (- 1.0 (/ (jogador-guerra-tempo-recarga jogador) (fifth (dados-arma-guerra jogador)))))) 0.0))
           (balanco (* (- 1.0 (* .85 mira)) (jogador-guerra-movimento jogador)
                       .015 (sin (jogador-guerra-passada jogador))))
           (base (compor-matrizes
                   (lwlgl.math:perspective-mat4 (lwlgl.math:degrees->radians 60) proporcao .025 5.0)
                   (lwlgl.math:translation-mat4 (+ (* .22 (- 1 mira)) balanco)
                     (+ (* -.24 (- 1 mira)) (* -.22 recarga)) (+ -.62 (* .05 mira) (* .09 recuo)))
                   (lwlgl.math:rotation-z-mat4 (+ (* -.08 (- 1 mira)) (* -.7 recarga)))
                   (lwlgl.math:rotation-x-mat4 (+ (* -.14 recuo) (* -.035 (sin (* pi mira))))))))
      (let ((exercito (if (eq (exercito-id (jogador-guerra-exercito jogador)) :aurora) "aurora" "bruma")))
        (desenhar-modelo (format nil "primeira-pessoa-~A-direito" exercito) base uniforme)
        (desenhar-modelo (format nil "primeira-pessoa-~A-esquerdo" exercito)
          (compor-matrizes base (lwlgl.math:translation-mat4 0 (* -.22 recarga) (* .15 recarga))) uniforme))
      (desenhar-modelo (nome-modelo-arma-guerra (jogador-guerra-arma jogador)) base uniforme)
      (when (member (jogador-guerra-arma jogador) '(:fuzil :precisao :franco-atirador))
        (desenhar-modelo (if (eq (jogador-guerra-arma jogador) :franco-atirador)
                             "ferrolho-longo" "ferrolho")
                         (compor-matrizes base (lwlgl.math:translation-mat4 0 0 (* .12 recuo))) uniforme))
      (when (> recarga .2)
        (desenhar-modelo "carregador-submetralhadora" (compor-matrizes base (lwlgl.math:translation-mat4 0 (* -.25 recarga) 0)) uniforme))
      (when (plusp (jogador-guerra-clarão jogador))
        (desenhar-modelo "clarao" (compor-matrizes base (lwlgl.math:translation-mat4 0 0 -1.0)) uniforme)))))

(defun desenhar-campo (sessao projecao visao uniforme dinamica)
  (let ((base (lwlgl.math:mat4-mul projecao visao)))
    (desenhar-modelo "posto" base uniforme)
    (dolist (inimigo (sessao-inimigos sessao))
      (let* ((morto (not (vivo-p inimigo))) (queda (inimigo-queda inimigo))
             (direcao (atan (- (inimigo-alvo-x inimigo) (inimigo-x inimigo))
                            (- (inimigo-z inimigo) (inimigo-alvo-z inimigo))))
             (balanco (if morto 0.0 (* .07 (sin (* 5 (inimigo-movimento inimigo))))))
             (matriz (compor-matrizes base
                       (lwlgl.math:translation-mat4 (inimigo-x inimigo) (if morto (* .2 queda) balanco) (inimigo-z inimigo))
                       (lwlgl.math:rotation-y-mat4 (- direcao))
                       (lwlgl.math:rotation-z-mat4 (if morto (* 1.5 queda) 0.0))
                       (lwlgl.math:rotation-x-mat4 (cond ((plusp (inimigo-chamado inimigo)) .35) ((plusp (inimigo-ataque inimigo)) -.3) (t 0.0))))))
        (desenhar-modelo (if (eq (inimigo-tipo inimigo) :chamador) "chamador" "criatura") matriz uniforme)
        (loop for nome in '("braco-criatura-esquerdo" "braco-criatura-direito") for lado in '(-1 1)
              do (desenhar-modelo nome
                    (compor-matrizes matriz (lwlgl.math:translation-mat4 (* lado .46) 1.5 0)
                     (lwlgl.math:rotation-x-mat4
                      (cond ((plusp (inimigo-chamado inimigo)) -.9)
                            ((plusp (inimigo-ataque inimigo)) (* -1.4 (sin (* pi (/ (inimigo-ataque inimigo) .8)))))
                            (t (* (- lado) balanco 5))))
                     (lwlgl.math:translation-mat4 (* lado -.46) -1.5 0)) uniforme))
        (loop for nome in '("perna-esquerda" "perna-direita") for lado in '(-1 1)
              do (desenhar-modelo nome
                    (compor-matrizes matriz (lwlgl.math:translation-mat4 0 .95 0)
                     (lwlgl.math:rotation-x-mat4 (* lado balanco 4))
                     (lwlgl.math:translation-mat4 0 -.95 0)) uniforme))))
    (dolist (porta (sessao-obstaculos sessao))
      (when (eq (obstaculo-tipo porta) :porta)
        (desenhar-modelo "porta" (compor-matrizes base
          (lwlgl.math:translation-mat4 (obstaculo-x porta) (if (obstaculo-aberto porta) 2.1 0.0) (obstaculo-z porta))) uniforme)))
    (dolist (dispositivo (sessao-dispositivos sessao))
      (desenhar-modelo "temporizador" (compor-matrizes base
        (lwlgl.math:translation-mat4 (dispositivo-x dispositivo) 0.0 (dispositivo-z dispositivo))) uniforme))
    (dolist (item (sessao-suprimentos sessao))
      (unless (suprimento-retirado item)
        (let ((matriz (compor-matrizes base (lwlgl.math:translation-mat4 (suprimento-x item) 0 (suprimento-z item)))))
          (desenhar-modelo "suprimento" matriz uniforme)
          (when (suprimento-equipamento item)
            (desenhar-modelo (if (eq (suprimento-equipamento item) :bipé) "bipe" "temporizador")
              (compor-matrizes matriz (lwlgl.math:translation-mat4 0 .4 0)) uniforme))
          (when (suprimento-arma item)
            (desenhar-modelo (nome-modelo-arma (suprimento-arma item))
              (compor-matrizes matriz (lwlgl.math:translation-mat4 0 .48 0)
                               (lwlgl.math:rotation-y-mat4 1.5)) uniforme)))))
    (dolist (item (sessao-suprimentos sessao))
      (when (suprimento-corpo item)
        (desenhar-corpo-soldado base (suprimento-x item) (suprimento-z item) uniforme)))
    (dolist (isca (sessao-iscas sessao))
      (let ((fracao (- 1 (/ (isca-tempo isca) .7))))
        (desenhar-modelo "isca" (compor-matrizes base
          (lwlgl.math:translation-mat4
            (+ (isca-x isca) (* fracao (- (isca-destino-x isca) (isca-x isca))))
            (+ .15 (* 3 (sin (* pi fracao))))
            (+ (isca-z isca) (* fracao (- (isca-destino-z isca) (isca-z isca)))))) uniforme)))
    ;; A neve em suspensão é composta por partículas leves.
    (setf (fill-pointer *vertices*) 0)
    (let ((soldado (sessao-soldado sessao)) (tempo (sessao-tempo sessao)))
      (dotimes (indice (getf *configuracao* :neve))
        (caixa (+ (if soldado (soldado-x soldado) 0) (- (mod (+ (* indice 3.713) (* tempo (if (eq (sessao-clima sessao) :rajada) 6.0 1.7))) 40.0) 20))
               (- 8 (mod (+ (* indice 1.731) (* tempo 1.4)) 7.8))
               (+ (if soldado (soldado-z soldado) 23) (- (mod (+ (* indice 5.17) (* tempo .6)) 40.0) 20))
               .027 .06 .015 '(.87 .92 .93 .75))))
    (enviar-malha dinamica)
    (lwlgl.opengl:set-uniform-mat4 uniforme base)
    (desenhar-malha dinamica)))

(defun desenhar-arma (sessao proporcao uniforme mira)
  (let* ((soldado (sessao-soldado sessao)) (tempo (sessao-tempo sessao)) (arma (soldado-arma soldado))
         (recarga (soldado-recarga soldado)) (recuo (soldado-recuo soldado))
         (insercao (if (plusp recarga) (sin (* pi (- 1.0 (/ recarga (duracao-recarga arma))))) 0.0))
         (ciclo (sin (* pi (limitar (/ (soldado-espera-tiro soldado) (intervalo-disparo arma)) 0.0 1.0))))
         (troca (/ (soldado-troca soldado) .65))
         (oscilacao (* .012 (min 1 (soldado-movimento soldado)) (sin (* tempo 9))))
         (base (compor-matrizes
                (lwlgl.math:perspective-mat4 (lwlgl.math:degrees->radians 60) proporcao .025 5.0)
                (lwlgl.math:translation-mat4
                 (+ (* .24 (- 1 mira)) (* .008 (sin (* tempo 4)) (soldado-movimento soldado)))
                 (+ (* -.24 (- 1 mira)) oscilacao (* -.14 insercao) (* -.6 troca))
                 (+ -.58 (* .085 recuo)))
                (lwlgl.math:rotation-z-mat4 (+ (* -.32 insercao) (* .2 troca)))
                (lwlgl.math:rotation-x-mat4 (+ (* .1 recuo) (* .65 troca) (if (soldado-correndo soldado) -.55 0))))))
    (grafico:gl-clear grafico:+gl-depth-buffer-bit+)
    (desenhar-modelo "primeira-pessoa-aurora-direito" base uniforme)
    (desenhar-modelo "primeira-pessoa-aurora-esquerdo"
      (compor-matrizes base (lwlgl.math:translation-mat4 (* .16 insercao) (* -.18 insercao)
                              (+ (* .18 insercao) (if (eq arma :escopeta) (* .11 ciclo) 0)))) uniforme)
    (when (> recuo .85)
      (desenhar-modelo "clarao" (compor-matrizes base (lwlgl.math:translation-mat4 0 0 (ninth (dados-arma arma)))) uniforme))
    (desenhar-modelo (nome-modelo-arma arma) base uniforme)
    (desenhar-modelo (eighth (dados-arma arma))
      (compor-matrizes base (lwlgl.math:translation-mat4 0 0 (* .11 ciclo))
                       (lwlgl.math:rotation-z-mat4 (if (member arma '(:fuzil :franco-atirador)) (* .25 ciclo) 0))) uniforme)
    (when (and (plusp recarga) (not (eq arma :submetralhadora)))
      (desenhar-modelo "cartucho" (compor-matrizes base
        (lwlgl.math:translation-mat4 (* .12 (- 1 insercao)) (+ .015 (* .13 (- 1 insercao))) -.1)) uniforme))
    (when (and (> ciclo .1) (plusp (soldado-espera-tiro soldado)))
      (desenhar-modelo "cartucho" (compor-matrizes base
        (lwlgl.math:translation-mat4 (+ .1 (* .4 ciclo)) (+ .02 (* .13 ciclo)) -.15)
        (lwlgl.math:rotation-z-mat4 (* ciclo 5))) uniforme))
    (when (eq arma :submetralhadora)
      (desenhar-modelo "carregador-submetralhadora" (compor-matrizes base
        (lwlgl.math:translation-mat4 (* -.15 insercao) (* -.4 insercao) (* .18 insercao))) uniforme))
    (when (eq (soldado-apoiado soldado) :bipé)
      (desenhar-modelo "bipe" (compor-matrizes base (lwlgl.math:translation-mat4 0 -.55 -.35)) uniforme))))

(defun gerar-amostra (tipo)
  "Sons originais sintetizados: ruído filtrado, transientes e ressonância grave."
  (let* ((duracao (case tipo (:vento 3.0) ((:fuzil :escopeta :carabina :submetralhadora :precisao :franco-atirador) .8)
                           ((:criatura :ataque) .7) ((:chamado :aviso-chamado) 2.0) (:porta .8) (:gelo .5) (:ferimento .35) (t .18)))
         (quantidade (round (* duracao 22050)))
         (dados (make-array quantidade :element-type '(signed-byte 16)))
         (filtro 0.0) (semente 31))
    (dotimes (indice quantidade dados)
      (setf semente (mod (+ (* semente 1103515245) 12345) 2147483648))
      (let* ((tempo (/ indice 22050.0)) (ruido (- (/ semente 1073741824.0) 1.0))
             (envoltoria (if (eq tipo :vento) .15 (exp (* (- (if (member tipo '(:fuzil :escopeta :carabina :submetralhadora :precisao :franco-atirador)) 9.0 6.0)) tempo))))
             (tom (sin (* 2 pi (case tipo (:criatura 85) (:ataque 135) (:fuzil 52) (:escopeta 43) (:carabina 68) (:submetralhadora 105) (:precisao 59) (:franco-atirador 38) (:chamado 230) (:aviso-chamado 150) (:metal 950) (:temporizador 650) (:porta 65) (t 180)) tempo))))
        (setf filtro (+ (* .86 filtro) (* .14 ruido)))
        (setf (aref dados indice)
              (round (* 26000 envoltoria
                        (case tipo
                          (:vento (* 2 filtro (+ .65 (* .35 (sin (* 2 pi (/ tempo duracao)))))))
                          ((:fuzil :escopeta :carabina :submetralhadora :precisao :franco-atirador) (+ (* .65 ruido) (* .35 tom)))
                          ((:criatura :ataque) (* tom (+ .5 (* .5 (sin (* 39 tempo))))))
                          (:passo (+ (* .75 filtro) (* .25 ruido)))
                          (:madeira (+ (* .6 filtro) (* .4 tom)))
                          (:metal (+ (* .4 ruido) (* .6 tom)))
                          (:gelo (* ruido (sin (* 840 tempo))))
                          (:porta (* tom (sin (* 25 tempo))))
                          ((:chamado :aviso-chamado) (* tom (+ .5 (* .5 (sin (* 18 tempo))))))
                          (:temporizador (* tom (sin (* 90 tempo))))
                          (:isca (* ruido (abs (sin (* 230 tempo)))))
                          (t (* .65 ruido))))))))))

(defun ganho-ruido (sessao origem)
  (* (case origem ((:fuzil :escopeta :carabina :submetralhadora :precisao :franco-atirador :chamado) .9) (:passo .22) (:madeira .32) (:metal .48) (t .65))
     (if (and (eq (sessao-clima sessao) :rajada) (member origem '(:passo :madeira :metal))) .5 1.0)))

(defun abrir-audio ()
  (let ((dispositivo (cffi:null-pointer)) (contexto (cffi:null-pointer)))
    (handler-case
        (progn
          (setf dispositivo (som:open-device nil))
          (when (cffi:null-pointer-p dispositivo) (error "Dispositivo de áudio indisponível."))
          (setf contexto (som:create-context dispositivo))
          (when (cffi:null-pointer-p contexto) (error "Contexto de áudio indisponível."))
          (som:make-context-current contexto)
          (som:create-alc-capabilities dispositivo) (som:create-capabilities)
          (setf *audio-ativo* t *amostras* (make-hash-table))
          (dolist (tipo '(:vento :fuzil :escopeta :carabina :submetralhadora :precisao :franco-atirador :criatura :ataque :passo :isca :queda :ferimento :recarga :madeira :metal :gelo :porta :temporizador :chamado :aviso-chamado))
            (setf (gethash tipo *amostras*) (gerar-amostra tipo)))
          (multiple-value-bind (fonte memoria)
              (som:play-pcm16 (gethash :vento *amostras*) 22050 :looping-p t :gain-value .35)
            (som:source-i fonte som:source-relative 1)
            (push (list fonte memoria :vento) *fontes-sonoras*))
          (values dispositivo contexto))
      (error (condicao)
        (format *error-output* "~&Áudio indisponível: ~A. A demo continuará sem reprodução sonora.~%" condicao)
        (unless (cffi:null-pointer-p contexto) (som:destroy-context contexto))
        (unless (cffi:null-pointer-p dispositivo) (som:close-device dispositivo))
        (setf *audio-ativo* nil)
        (values (cffi:null-pointer) (cffi:null-pointer))))))

(defun atualizar-audio (sessao)
  (when *audio-ativo*
    (let ((soldado (sessao-soldado sessao)) (pausado (not (eq (sessao-fase sessao) :combate))))
      (dolist (par *fontes-sonoras*)
        (som:source-f (first par) som:gain
          (float (* (getf *configuracao* :volume)
                    (if (eq (third par) :vento)
                        (* (getf *configuracao* :ambiente)
                           (case (sessao-clima sessao) (:rajada 1.6) (:aviso (+ .35 (* (- 4 (sessao-tempo-clima sessao)) .25))) (t .35)))
                        (* (getf *configuracao* :efeitos) (or (fourth par) .65)))) 1.0)))
      (when soldado
        (som:listener-3f som:position (float (soldado-x soldado) 1.0) (altura-olhos soldado) (float (soldado-z soldado) 1.0))
        (som:set-listener-orientation (sin (soldado-angulo soldado)) 0 (- (cos (soldado-angulo soldado))) 0 1 0))
      (setf *fontes-sonoras*
            (delete-if (lambda (par)
                         (let ((estado (som:get-source-i (first par) som:source-state)))
                           (cond ((= estado som:stopped)
                                  (som:delete-source (first par)) (som:delete-buffer (second par)) t)
                                 ((and pausado (= estado som:playing)) (som:source-pause (first par)) nil)
                                 ((and (not pausado) (= estado som:paused)) (som:source-play (first par)) nil))))
                       *fontes-sonoras*))
      (unless pausado
        (dolist (ruido (reverse (sessao-sons sessao)))
          (when (< (length *fontes-sonoras*) 32)
            (multiple-value-bind (fonte memoria)
                (som:play-pcm16 (gethash (ruido-origem ruido) *amostras*) 22050
                                :gain-value (float (* (getf *configuracao* :volume) (getf *configuracao* :efeitos)
                                 (ganho-ruido sessao (ruido-origem ruido))) 1.0))
              (som:source-3f fonte som:position (float (ruido-x ruido) 1.0) .7 (float (ruido-z ruido) 1.0))
              ;; AL_REFERENCE_DISTANCE e AL_ROLLOFF_FACTOR da própria API OpenAL.
              (som:source-f fonte #x1020 (if (member (ruido-origem ruido) '(:fuzil :escopeta :carabina :submetralhadora :precisao :franco-atirador)) 8.0 3.0))
              (som:source-f fonte #x1021 1.0)
              (push (list fonte memoria (ruido-origem ruido) (ganho-ruido sessao (ruido-origem ruido))) *fontes-sonoras*)))))))
  (setf (sessao-sons sessao) nil))

(defun atualizar-audio-guerra (guerra)
  "Usa o mesmo reprodutor OpenAL, com posições em metros da simulação."
  (let* ((j (jogador-local-guerra guerra))
         (sessao (%criar-sessao :fase (if (guerra-pausada guerra) :pausa :combate)
                    :soldado (criar-soldado :x (jogador-guerra-x j) :z (jogador-guerra-z j)
                                             :angulo (jogador-guerra-angulo j))
                    :sons (mapcar (lambda (som) (criar-ruido :origem (first som) :x (second som) :z (third som)))
                                  (guerra-audio guerra)))))
    (atualizar-audio sessao)
    (setf (guerra-audio guerra) nil)))

(defun fechar-audio (dispositivo contexto)
  (when *audio-ativo*
    (dolist (par *fontes-sonoras*)
      (som:source-stop (first par)) (som:delete-source (first par)) (som:delete-buffer (second par)))
    (setf *fontes-sonoras* nil)
    (som:make-context-current (cffi:null-pointer))
    (som:destroy-context contexto) (som:close-device dispositivo)))

(defun capturar-quadro (caminho largura altura)
  "Grava os pixels reais do quadro, sem dependências de captura de tela."
  (ensure-directories-exist caminho)
  (grafico:gl-pixel-storei grafico:+gl-pack-alignment+ 1)
  (cffi:with-foreign-object (ponteiro :unsigned-char (* largura altura 3))
    (grafico:gl-read-pixels 0 0 largura altura grafico:+gl-rgb+ grafico:+gl-unsigned-byte+ ponteiro)
    (with-open-file (arquivo caminho :direction :output :element-type '(unsigned-byte 8) :if-exists :supersede)
      (loop for caractere across (format nil "P6~%~D ~D~%255~%" largura altura) do (write-byte (char-code caractere) arquivo))
      (loop for linha downfrom (1- altura) to 0
            do (dotimes (coluna (* largura 3))
                 (write-byte (cffi:mem-aref ponteiro :unsigned-char (+ (* linha largura 3) coluna)) arquivo))))))

(defun roteiro-visual (sessao quadro)
  "Ensaio reproduzível: posiciona situações e usa as mesmas ações do jogo."
  (case quadro
    (10 (confirmar-notas sessao))
    (35 (setf (soldado-x (sessao-soldado sessao)) 3.0 (soldado-z (sessao-soldado sessao)) 18.0)
        (recolher sessao) (iniciar-recarga sessao))
    (245 (let ((soldado (sessao-soldado sessao)))
           (setf (sessao-inimigos sessao)
                 (list (criar-inimigo :numero 0 :x 0.0 :z 11.0 :alvo-x 0.0 :alvo-z 11.0)
                       (criar-inimigo :numero 1 :x 6.0 :z 18.0 :alvo-x 6.0 :alvo-z 18.0))
                 (soldado-x soldado) 0.0 (soldado-inclinacao soldado) (atan -.65 7.0) (soldado-mirando soldado) t)))
    (275 (disparar sessao))
    (290 (let ((soldado (sessao-soldado sessao)))
           (setf (soldado-angulo soldado) (- (/ pi 2))) (lancar-isca sessao)))
    (350 (let ((soldado (sessao-soldado sessao)))
           (setf (sessao-inimigos sessao)
                 (list (criar-inimigo :x (soldado-x soldado) :z (- (soldado-z soldado) 1.0))))))
    (610 (abrir-notas sessao)
         (setf (notas-texto (sessao-notas sessao)) "A escopeta funciona de perto. Desvie a busca com uma isca antes de avançar."))
    (630 (setf (notas-arma (sessao-notas sessao)) :escopeta
               (notas-preparo (sessao-notas sessao)) :distracao))
    (680 (confirmar-notas sessao))
    (720 (setf (sessao-fase sessao) :pausa))))

(defun executar-apresentacao (&key (largura 1280 largura-fornecida) (altura 720 altura-fornecida) quadros-maximos
                                   validacao pasta-capturas sem-audio guerra (sincronizar t sincronizar-fornecido))
  (let ((*persistencia-ativa* t) (*gravacao-bloqueada* nil) (*erro-persistencia* nil)
        (*configuracao* (configuracao-padrao))
        (*pasta-dados* (if validacao (merge-pathnames "dados/" (or pasta-capturas #P"/tmp/rimefall-validacao/")) *pasta-dados*))
        (*pasta-configuracao* (if validacao (merge-pathnames "preferencias/" (or pasta-capturas #P"/tmp/rimefall-validacao/")) *pasta-configuracao*))
        (*vertices* (iniciar-vertices)) (*modelos* nil) (*botoes* nil) (*foco* :entrar)
        (*historico-aberto* nil) (*edicao-diario* nil) (*pagina-historico* 0) (*pagina-evidencias* 0)
        (*diario-historico* nil) (*linha-diario* 0)
        (*fontes-sonoras* nil) (*amostras* nil) (*audio-ativo* nil))
    (unless validacao (carregar-configuracao))
    (setf *mapa-aberto* nil *configuracoes-abertas* nil *remapeando* nil *editando-marca* nil)
    (unless largura-fornecida (setf largura (getf *configuracao* :largura)))
    (unless altura-fornecida (setf altura (getf *configuracao* :altura)))
    (unless sincronizar-fornecido (setf sincronizar (getf *configuracao* :sincronizar)))
    (janela:with-glfw ()
      (janela:default-window-hints)
      (janela:window-hint janela:context-version-major 3)
      (janela:window-hint janela:context-version-minor 3)
      (janela:window-hint janela:opengl-profile janela:opengl-core-profile)
      (janela:with-window (janela largura altura "Rimefall / Posto 07"
                                   :monitor (when (getf *configuracao* :tela-cheia) (janela:primary-monitor)))
        (janela:make-context-current janela)
        ;; Alguns ambientes deixam a janela recém-criada sem foco de teclado;
        ;; o jogo deve estar pronto para receber WASD assim que aparece.
        (janela:focus-window janela)
        (janela:swap-interval (if sincronizar 1 0))
        (lwlgl.opengl:load-opengl)
        (let ((programa 0) (dinamica nil) (interface nil) (estado nil)
              (dispositivo (cffi:null-pointer)) (contexto (cffi:null-pointer)))
          (unwind-protect
               (progn
                 (setf programa (lwlgl.opengl:make-program *programa-vertices* *programa-fragmentos*)
                       dinamica (criar-malha) interface (criar-malha)
                       *modelos* (carregar-modelos) estado (entrada:make-input-state janela))
                 (unless sem-audio (multiple-value-setq (dispositivo contexto) (abrir-audio)))
                 (grafico:gl-enable grafico:+gl-blend+)
                 (grafico:gl-blend-func grafico:+gl-src-alpha+ grafico:+gl-one-minus-src-alpha+)
                 (let ((uniforme (localizar-uniforme programa "matriz"))
                       (neblina (localizar-uniforme programa "neblina"))
                       (inicio (localizar-uniforme programa "inicio"))
                       (fim (localizar-uniforme programa "fim"))
                       (sessao (cond
                                 (validacao (nova-sessao))
                                 (guerra (setf *hud-guerra-visivel* nil
                                               *guerra-atual* (criar-guerra-offline :jogadores-por-lado 8))
                                         (criar-logistica-guerra *guerra-atual*)
                                         (%criar-sessao :fase :guerra))
                                 (t (%criar-sessao :fase :titulo))))
                       (anterior (janela:get-time)) (acumulado 0.0d0)
                       (quadros 0) (capturado nil) (mira 0.0) (progresso-mira 0.0)
                       (portador-mira nil) (geracao-mira nil) (fase-anterior nil)
                       (medicao-inicio nil) (tempos nil))
                   (when guerra (janela:set-window-title janela "Rimefall / Guerra / COMBATE"))
                   (format t "~&Rimefall: ~A / ~A~%" (lwlgl.opengl:get-string grafico:+gl-renderer+)
                           (lwlgl.opengl:get-string grafico:+gl-version+))
                   (loop until (janela:window-should-close-p janela)
                         for agora = (janela:get-time)
                         for intervalo = (min .1d0 (- agora anterior))
                         do (setf anterior agora)
                            (entrada:begin-input-frame estado)
                            (janela:poll-events)
                            (unless validacao (setf sessao (processar-interface sessao estado janela)))
                            (when validacao (setf sessao (roteiro-expansao sessao quadros)))
                            (when (and *gravacao-bloqueada* (eq (sessao-fase sessao) :combate))
                              (setf (sessao-fase sessao) :pausa))
                            (let ((em-combate (and (member (sessao-fase sessao) '(:combate :guerra))
                                                    (or (not (eq (sessao-fase sessao) :guerra))
                                                        (and (guerra-ativa-p *guerra-atual*) (not (guerra-pausada *guerra-atual*)))))))
                              (unless (eq em-combate capturado)
                                (janela:set-input-mode janela janela:cursor
                                                       (if em-combate janela:cursor-disabled janela:cursor-normal))
                                (setf capturado em-combate))
                              (unless (eq fase-anterior (sessao-fase sessao))
                                (unless (member (sessao-fase sessao) '(:titulo :guerra))
                                  (salvar-transicao sessao))
                                (setf *foco* (case (sessao-fase sessao) (:titulo :nova) (:notas :entrar) (:relatorio :notas)
                                                   ((:vitoria :derrota) :reiniciar) (:pausa :retomar)))
                                (setf fase-anterior (sessao-fase sessao)))
                              (if (eq (sessao-fase sessao) :guerra)
                                  (progn
                                    (incf acumulado (if (and (guerra-ativa-p *guerra-atual*) (not (guerra-pausada *guerra-atual*))) intervalo 0.0))
                                    (loop while (>= acumulado *passo-fixo*)
                                          do (atualizar-guerra *guerra-atual* *passo-fixo*)
                                             (atualizar-logistica-guerra *guerra-atual* *passo-fixo*)
                                             (atualizar-invasao-guerra *guerra-atual* *passo-fixo*)
                                             (decf acumulado *passo-fixo*)))
                                  (if em-combate
                                  (let ((frente (if validacao 0.0 (- (if (acao-mantida-p estado :frente) 1.0 0.0)
                                                                 (if (acao-mantida-p estado :tras) 1.0 0.0))))
                                        (lado (if validacao 0.0 (- (if (acao-mantida-p estado :direita) 1.0 0.0)
                                                               (if (acao-mantida-p estado :esquerda) 1.0 0.0)))))
                                    (incf acumulado (if validacao *passo-fixo* intervalo))
                                    (loop while (>= acumulado *passo-fixo*)
                                          do (atualizar-campo sessao *passo-fixo* :frente frente :lado lado
                                                    :gatilho (and (not validacao) (entrada:mouse-down-p estado janela:mouse-button-left)))
                                             (decf acumulado *passo-fixo*)))
                                  (setf acumulado 0.0d0))))
                            (unless (eq (sessao-fase sessao) :guerra)
                              (salvar-periodicamente sessao))
                            (if (eq (sessao-fase sessao) :guerra) (atualizar-audio-guerra *guerra-atual*) (atualizar-audio sessao))
                            (multiple-value-bind (largura-real altura-real) (janela:framebuffer-size janela)
                              (when (and (plusp largura-real) (plusp altura-real))
                                (grafico:gl-viewport 0 0 largura-real altura-real)
                                (grafico:gl-clear-color .47 .56 .61 1.0)
                                (grafico:gl-clear (logior grafico:+gl-color-buffer-bit+ grafico:+gl-depth-buffer-bit+))
                                (grafico:gl-enable grafico:+gl-depth-test+)
                                (grafico:gl-use-program programa)
                                ;; O mapa da guerra usa escala comprimida; se
                                ;; recebesse a mesma neblina do tutorial, a
                                ;; câmera veria somente uma massa azul-escura.
                                ;; Mantemos a tempestade fechada, mas ampliamos
                                ;; o alcance visual em calmaria e aviso.
                                (let ((guerra-p (eq (sessao-fase sessao) :guerra)))
                                  (grafico:gl-uniform-1f neblina 1.0)
                                  (grafico:gl-uniform-1f inicio
                                                           (if (eq (sessao-clima sessao) :rajada)
                                                               8.0
                                                               (if guerra-p 22.0 *inicio-neblina*)))
                                  (grafico:gl-uniform-1f fim
                                                           (if (eq (sessao-clima sessao) :rajada)
                                                               32.0
                                                               (if guerra-p 78.0 (distancia-visivel sessao)))))
                                (let* ((soldado (sessao-soldado sessao))
                                       (proporcao (/ (float largura-real) altura-real))
                                       (visao (cond
                                                ((eq (sessao-fase sessao) :guerra)
                                                 (let ((jogador (jogador-local-guerra *guerra-atual*)))
                                                   (if jogador
                                                       (compor-matrizes
                                                        (lwlgl.math:rotation-x-mat4 (- (jogador-guerra-inclinacao jogador)))
                                                        (lwlgl.math:rotation-y-mat4 (jogador-guerra-angulo jogador))
                                                         (lwlgl.math:translation-mat4
                                                         (- (* .08 (jogador-guerra-x jogador))) (- (* .08 (altura-jogador-guerra jogador)))
                                                         (- (* .08 (jogador-guerra-z jogador)))))
                                                       (compor-matrizes (lwlgl.math:rotation-x-mat4 .12)
                                                        (lwlgl.math:translation-mat4 0 -3.0 -23.0)))))
                                                (soldado
                                                 (compor-matrizes
                                                  (lwlgl.math:rotation-x-mat4 (- (+ (soldado-inclinacao soldado) (oscilacao-respiracao sessao))))
                                                  (lwlgl.math:rotation-y-mat4 (soldado-angulo soldado))
                                                  (lwlgl.math:translation-mat4 (- (soldado-x soldado))
                                                   (- (altura-olhos soldado)) (- (soldado-z soldado)))))
                                                (t (compor-matrizes (lwlgl.math:rotation-x-mat4 .12)
                                                    (lwlgl.math:translation-mat4 0 -3.0 -23.0)))))
                                       (guerra-p (eq (sessao-fase sessao) :guerra))
                                       (portador (if guerra-p (jogador-local-guerra *guerra-atual*)
                                                     (when (member (sessao-fase sessao) '(:combate :pausa)) soldado)))
                                       (geracao (when (and guerra-p portador) (jogador-guerra-geracao portador)))
                                       (suspensa (or (eq (sessao-fase sessao) :pausa)
                                                     (and guerra-p (guerra-pausada *guerra-atual*)))))
                                  ;; Uma vida nova não herda a pose da anterior. Pausar preserva a pose.
                                  (unless (and (eq portador portador-mira) (eql geracao geracao-mira))
                                    (setf progresso-mira 0.0 portador-mira portador geracao-mira geracao))
                                  (setf progresso-mira (avancar-mira progresso-mira (mira-solicitada-p sessao)
                                                        (cond (suspensa 0.0) (validacao *passo-fixo*) (t intervalo)))
                                        mira (suavizar-mira progresso-mira))
                                  (let ((projecao (lwlgl.math:perspective-mat4
                                                   (lwlgl.math:degrees->radians
                                                    (campo-visao-mira (getf *configuracao* :visao) mira
                                                      (if soldado (soldado-arma soldado) :fuzil) guerra-p))
                                                   proporcao (if (eq (sessao-fase sessao) :guerra) .004 .05) 95.0)))
                                    (if (eq (sessao-fase sessao) :guerra)
                                        (progn (desenhar-campo-guerra *guerra-atual* projecao visao uniforme)
                                               (desenhar-efeitos-guerra *guerra-atual* projecao visao uniforme dinamica))
                                        (desenhar-campo sessao projecao visao uniforme dinamica)))
                                  (grafico:gl-uniform-1f neblina 0.0)
                                  (when (and (eq (sessao-fase sessao) :guerra)
                                             (jogador-local-guerra *guerra-atual*))
                                    (grafico:gl-clear grafico:+gl-depth-buffer-bit+)
                                    (desenhar-arma-guerra (jogador-local-guerra *guerra-atual*) proporcao uniforme mira))
                                  (when (and soldado (member (sessao-fase sessao) '(:combate :pausa)))
                                    (unless (and (> mira .85) (> (ampliacao-arma (soldado-arma soldado)) 1.0))
                                      (desenhar-arma sessao proporcao uniforme mira))))
                                (grafico:gl-disable grafico:+gl-depth-test+)
                                (lwlgl.opengl:set-uniform-mat4 uniforme (lwlgl.math:orthographic-mat4 0 1280 720 0 -1 1))
                                (setf (fill-pointer *vertices*) 0 *botoes* nil)
                                (when (and (eq (sessao-fase sessao) :combate) (> mira .85)
                                           (> (ampliacao-arma (soldado-arma (sessao-soldado sessao))) 1.0))
                                  (desenhar-luneta))
                                (desenhar-interface sessao)
                                (enviar-malha interface) (desenhar-malha interface)
                                (when (and pasta-capturas (member quadros '(2 25 260 320 590 650 700 725 780 830 890 940 970 1020 1080 1590 1606 1760 2270 2440 2950 2960 3120 3630 3640 3775)))
                                  (capturar-quadro (merge-pathnames (format nil "quadro-~3,'0D.ppm" quadros) pasta-capturas)
                                                  largura-real altura-real))
                                (let ((erro (grafico:gl-get-error)))
                                  (unless (zerop erro) (error "Erro OpenGL no quadro ~D: ~D" quadros erro)))))
                            (janela:swap-buffers janela)
                            (when (= quadros 30) (setf medicao-inicio (janela:get-time)))
                            (when (and (> quadros 30) (not (and pasta-capturas (member quadros '(260 320 590 650 700 725)))))
                              (push intervalo tempos))
                            (incf quadros)
                            (when (and quadros-maximos (>= quadros quadros-maximos)) (return)))
                   (unless (member (sessao-fase sessao) '(:titulo :guerra)) (salvar-sessao sessao))
                   (when medicao-inicio
                     (let ((duracao (- (janela:get-time) medicao-inicio)))
                       (format t "~&Medição real: ~,1F quadros/s; ~D quadros; ~,2F s.~%"
                               (/ (- quadros 30) (max duracao .001)) (- quadros 30) duracao)))
                   (when validacao
                     (unless (and (= (sessao-usados sessao) 2)
                                  (gethash :escopeta (sessao-acervo sessao))
                                  (gethash :distracao (sessao-acervo sessao))
                                  (eq (soldado-arma (sessao-soldado sessao)) :franco-atirador)
                                  (= (soldado-iscas (sessao-soldado sessao)) 4))
                       (error "O roteiro visual não completou a transmissão e o segundo preparo."))
                     (verificar-roteiro-expansao sessao)
                     (format t "~&Roteiro visual concluído: escopeta, distração, morte, diário e segundo soldado.~%"))))
            (when estado (entrada:detach-input-state estado))
            (fechar-audio dispositivo contexto)
            (when *modelos* (maphash (lambda (nome malha) (declare (ignore nome)) (destruir-malha malha)) *modelos*))
            (when dinamica (destruir-malha dinamica)) (when interface (destruir-malha interface))
            (when (plusp programa) (grafico:gl-delete-program programa))))))))

(defun roteiro-expansao (sessao quadro)
  "Percurso gráfico determinístico com ações reais e situações preparadas."
  (when (< quadro 741) (roteiro-visual sessao quadro))
  (case quadro
    (12 (let ((soldado (sessao-soldado sessao)))
          (setf (soldado-x soldado) 0.0 (soldado-z soldado) 15.0)
          (interagir-porta sessao)
          (setf (soldado-z soldado) 23.0)))
    (45 (let ((soldado (sessao-soldado sessao)))
          (setf (soldado-x soldado) -24.0 (soldado-z soldado) 4.0
                (sessao-inimigos sessao) (list (criar-inimigo :x -24.0 :z -7.0)))
          (recolher sessao) (colocar-dispositivo sessao)))
    (55 (let ((soldado (sessao-soldado sessao)))
          (setf (soldado-x soldado) -16.0)
          (emitir-ruido sessao -16.0 4.0 45.0 :fuzil (soldado-numero soldado))))
    (240 (let ((soldado (sessao-soldado sessao)))
           (setf (soldado-x soldado) -24.0 (soldado-z soldado) 4.0)
           (recuperar-dispositivo sessao)
           (setf (soldado-x soldado) 24.0 (soldado-z soldado) -7.0)
           (recolher sessao)
           (setf (soldado-x soldado) 0.0 (soldado-z soldado) 18.0)))
    (270 (let ((soldado (sessao-soldado sessao)))
           (setf (soldado-agachado soldado) t (soldado-inclinacao soldado) 0.0)
           (apoiar-arma sessao)))
    (620 (let ((celula (loop for chave being the hash-keys of (sessao-explorado sessao) return chave)))
           (when celula
             (adicionar-marca sessao (car celula) (cdr celula) "Caminho para o abrigo. Silêncio.")
             (selecionar-celula sessao (car celula) (cdr celula)))))
    (640 (setf *mapa-aberto* t)
         (salvar-sessao sessao)
         (uiop:copy-file (caminho-sessao) (merge-pathnames "memoria.sexp" *pasta-dados*)))
    (665 (setf *mapa-aberto* nil))
    (750 (setf (sessao-fase sessao) :combate (sessao-clima sessao) :aviso (sessao-tempo-clima sessao) 1.0)
         (let ((soldado (sessao-soldado sessao)))
           (setf (soldado-x soldado) 0.0 (soldado-z soldado) 6.0 (soldado-angulo soldado) 0.0)))
    (790 (setf (sessao-inimigos sessao)
               (list (criar-inimigo :tipo :chamador :x .7 :z 5.0 :alvo-x .7 :alvo-z 5.0)
                     (criar-inimigo :x 11.0 :z 4.0 :alvo-x 11.0 :alvo-z 4.0))))
    (840 (setf (soldado-z (sessao-soldado sessao)) 23.0))
    (880 (unless (salvar-sessao sessao) (error "Falha na gravação do roteiro: ~A" *erro-persistencia*))
         (let ((carregada (carregar-sessao)))
           (unless carregada (error "Falha ao continuar: ~A" *erro-persistencia*))
           (setf sessao carregada)))
    (910 (setf (sessao-fase sessao) :combate))
    (930 (setf (sessao-fase sessao) :pausa *historico-aberto* t *pagina-historico* 0))
    (955 (setf *historico-aberto* nil *configuracoes-abertas* t))
    (995 (setf *configuracoes-abertas* nil)))
  (when (>= quadro 1045)
    (let* ((indice (floor (- quadro 1045) 680)) (etapa (mod (- quadro 1045) 680))
           (arma (nth indice '(:carabina :submetralhadora :precisao :franco-atirador)))
           (soldado (sessao-soldado sessao)))
      (when arma
        (when (zerop etapa)
          (setf (sessao-fase sessao) :combate (soldado-mirando soldado) nil
                (sessao-inimigos sessao) (list (criar-inimigo :x -39.0 :z 39.0 :alvo-x -39.0 :alvo-z 39.0)))
          (let ((item (find arma (sessao-suprimentos sessao) :key #'suprimento-arma)))
            (setf (soldado-x soldado) (suprimento-x item) (soldado-z soldado) (suprimento-z item)
                  (soldado-angulo soldado) 0.0 (soldado-inclinacao soldado) 0.0)
            (recolher sessao) (iniciar-recarga sessao)))
        (when (= etapa 530)
          (setf (sessao-inimigos sessao)
                (list (criar-inimigo :x (soldado-x soldado) :z (- (soldado-z soldado) 8.0)
                                    :alvo-x (soldado-x soldado) :alvo-z (- (soldado-z soldado) 8.0)))
                (soldado-mirando soldado) t
                (soldado-inclinacao soldado) (atan -.65 8.0)))
        (when (member etapa (if (eq arma :submetralhadora) '(560 570 580 590) '(560 600)))
          (setf (soldado-inclinacao soldado) (atan -.65 8.0)) (disparar sessao))
        (when (= etapa 625) (setf (sessao-fase sessao) :pausa)))))
  sessao)
(defun verificar-roteiro-expansao (sessao)
  (unless (and (gethash :temporizador (sessao-acervo sessao))
               (gethash :bipé (sessao-acervo sessao))
               (plusp (hash-table-count (sessao-explorado sessao)))
               (sessao-marcas sessao) (not *erro-persistencia*)
               (eq (sessao-fase sessao) :pausa))
    (error "A expansão não completou descobertas, mapa e continuação: ~A" *erro-persistencia*))
  (unless (every (lambda (arma) (find arma (soldado-aprendizados (sessao-soldado sessao)) :key #'evidencia-conhecimento))
                 '(:carabina :submetralhadora :precisao :franco-atirador))
    (error "Uma das quatro novas armas não completou seu ensaio de eliminação."))
  (format t "~&Seis armas validadas, incluindo lunetas 2x/4x e recarga do carregador.~%")
  (format t "~&Expansão validada: isca temporizada, bipé, mapa, chamado, rajada, salvamento e continuação.~%"))

(defun desenhar-luneta ()
  "Retículo óptico fixo. A cena continua sujeita à mesma neve e neblina."
  (let ((escuro '(.012 .017 .018 1.0)))
    (dotimes (indice 96)
      (let* ((angulo (* 2 pi (/ indice 96))) (seguinte (* 2 pi (/ (1+ indice) 96)))
             (interno (list (+ 640 (* 275 (cos angulo))) (+ 360 (* 275 (sin angulo))) 0))
             (outro (list (+ 640 (* 275 (cos seguinte))) (+ 360 (* 275 (sin seguinte))) 0)))
        (quadrilatero interno outro
                      (list (+ 640 (* 1600 (cos seguinte))) (+ 360 (* 1600 (sin seguinte))) 0)
                      (list (+ 640 (* 1600 (cos angulo))) (+ 360 (* 1600 (sin angulo))) 0) escuro)))
    (retangulo 366 359 263 2 escuro) (retangulo 651 359 263 2 escuro)
    (retangulo 639 86 2 263 escuro) (retangulo 639 371 2 263 escuro)
    (retangulo 639 359 2 2 escuro)))
