(in-package #:rimefall)

;;; Unidades em metros e segundos. Ajustes de ritmo ficam reunidos aqui.
(defparameter *passo-fixo* (/ 1.0 60.0))
(defparameter *velocidade-marcha* 2.8)
(defparameter *velocidade-corrida* 4.6)
(defparameter *velocidade-agachado* 1.35)
(defparameter *alcance-passos* 12.0)
(defparameter *alcance-corrida* 24.0)
(defparameter *alcance-agachado* 3.2)
(defparameter *alcance-disparo* 65.0)
(defparameter *alcance-isca* 24.0)
(defparameter *duracao-busca* 7.0)
(defparameter *intervalo-ondas* 8.0)
(defparameter *composicao-ondas* '(3 4 5))
(defparameter *inicio-neblina* 9.0)
(defparameter *fim-neblina* 34.0)

(defstruct (soldado (:constructor criar-soldado) (:predicate soldado-p) (:copier copiar-soldado))
  (numero 1) (x 0.0) (z 23.0) (angulo 0.0) (inclinacao 0.0)
  (ferimentos 0) (arma :fuzil) (carregador 4) (reserva-fuzil 8) (reserva-escopeta 0) (reserva-carabina 0) (reserva-submetralhadora 0) (reserva-precisao 0) (reserva-franco-atirador 0)
  (iscas 2) preparo (aprendizados nil) (transferido nil) (ultimo-ruido -100.0)
  (recarga 0.0) (troca 0.0) (espera-tiro 0.0) (recuo 0.0) (passada 0.0)
  (agachado nil) (correndo nil) (mirando nil) (movimento 0.0) (eliminacoes 0) (nome "") (origem "") (causa "Contato com uma criatura")
  equipamento (apoiado nil) (explorado (make-hash-table :test #'equal)))
(defstruct (inimigo (:constructor criar-inimigo) (:predicate inimigo-p) (:copier copiar-inimigo))
  (numero 0) (x 0.0) (z 0.0) (vida 100) (estado :patrulha)
  (alvo-x 0.0) (alvo-z 0.0) (pista -100.0) (busca 0.0) rastreado
  (ataque 0.0) (intervalo 0.0) (rota nil) (recalculo 0.0) (patrulha 0)
  (voz 0.0) (movimento 0.0) (tipo :comum) (chamado 0.0) (chamou nil) (queda 0.0))
(defstruct (obstaculo (:constructor criar-obstaculo) (:predicate obstaculo-p) (:copier copiar-obstaculo))
  x z largura profundidade altura (tipo :muro) (aberto nil))
(defstruct (suprimento (:constructor criar-suprimento) (:predicate suprimento-p) (:copier copiar-suprimento))
  x z arma (fuzil 0) (escopeta 0) (carabina 0) (submetralhadora 0) (precisao 0) (franco-atirador 0) (iscas 0) corpo equipamento (retirado nil))
(defstruct (ruido (:constructor criar-ruido) (:predicate ruido-p) (:copier copiar-ruido))
  x z alcance origem soldado instante)
(defstruct (isca (:constructor criar-isca) (:predicate isca-p) (:copier copiar-isca))
  x z destino-x destino-z (tempo 0.7) soldado)
(defstruct (sessao (:constructor %criar-sessao) (:predicate sessao-p) (:copier copiar-sessao))
  (fase :notas) (tempo 0.0) (onda 0) (espera-onda 0.0) (usados 0)
  soldado (acervo (criar-acervo)) (notas (criar-notas)) (historico nil)
  (inimigos nil) (obstaculos nil) (suprimentos nil) (iscas nil)
  (sons nil) (ruidos nil) (mensagem "") (mensagem-ate 0.0) (semente 73)
  (mapa :posto-ampliado) (clima :calmaria) (tempo-clima 36.0) (exploracao-em 0.0)
  (explorado (make-hash-table :test #'equal)) (marcas nil) (dispositivos nil)
  (gelo-partido nil) (salvamento-em 0.0) (fase-retorno :combate))
(defstruct (dispositivo (:constructor criar-dispositivo) (:predicate dispositivo-p) (:copier copiar-dispositivo))
  x z soldado (tempo 0.0) (pulso 3.0))

(defparameter *mapa-teste*
  (let ((*package* (find-package :rimefall)) (*read-eval* nil))
    (with-open-file (arquivo (asdf:system-relative-pathname "rimefall/nucleo" "mapas/posto.dat"))
      (loop for linha = (read-line arquivo nil) while linha
            unless (or (zerop (length linha)) (char= (char linha 0) #\;))
            collect (read-from-string (concatenate 'string "(" linha ")"))))))
(defparameter *identidades*
  '(("André Nunes" "Operador de rádio. Guardava cartas para a irmã.")
    ("Lúcia Reis" "Mecânica. Conhecia cada ruído do posto.")
    ("Caio Moura" "Cartógrafo. Desenhava caminhos nas margens dos relatórios.")
    ("Helena Duarte" "Reservista. Prometeu trazer os nomes de todos de volta.")))
(defparameter *limite-mapa* 41.0)
(defparameter *meia-grade-mapa* 21)
(defparameter *tempo-cartucho* 0.85)
;;; Capacidade, reserva inicial, intervalo, dano, recarga, modelo e peça móvel.
(defparameter *armamentos*
  '((:fuzil 4 8 1.1 100 .85 "fuzil" "ferrolho" .0)
    (:escopeta 2 6 .85 36 .85 "escopeta" "telha" .1)
    (:carabina 8 16 .34 55 .65 "carabina" "culatra" .05)
    (:submetralhadora 20 20 .12 26 2.7 "submetralhadora" "culatra-submetralhadora" .27)
    (:precisao 10 10 .55 75 .85 "precisao" "culatra-precisao" -.04)
    (:franco-atirador 5 5 1.8 160 1.1 "franco-atirador" "ferrolho-longo" -.2)))
(defun ampliacao-arma (arma) (case arma (:precisao 2.0) (:franco-atirador 4.0) (t 1.0)))
(defun dados-arma (arma) (or (assoc arma *armamentos*) (error "Arma desconhecida: ~A" arma)))
(defun nome-modelo-arma (arma) (seventh (dados-arma arma)))
(defun intervalo-disparo (arma) (fourth (dados-arma arma)))
(defun duracao-recarga (arma) (sixth (dados-arma arma)))
(defparameter *atraso-dispositivo* 3.0)
(defparameter *duracao-dispositivo* 5.0)
(defparameter *tempo-chamado* 2.0)

(defun limitar (valor minimo maximo) (max minimo (min maximo valor)))
(defun distancia (x z outro-x outro-z) (sqrt (+ (expt (- x outro-x) 2) (expt (- z outro-z) 2))))
(defun vivo-p (inimigo) (plusp (inimigo-vida inimigo)))
(defun capacidade-arma (arma) (second (dados-arma arma)))
(defun campo-reserva (arma)
  (ecase arma (:fuzil 'reserva-fuzil) (:escopeta 'reserva-escopeta)
              (:carabina 'reserva-carabina) (:submetralhadora 'reserva-submetralhadora) (:precisao 'reserva-precisao) (:franco-atirador 'reserva-franco-atirador)))
(defun reserva-arma (soldado) (slot-value soldado (campo-reserva (soldado-arma soldado))))
(defun (setf reserva-arma) (valor soldado) (setf (slot-value soldado (campo-reserva (soldado-arma soldado))) valor))
(defun municao-no-corpo (soldado arma)
  (+ (slot-value soldado (campo-reserva arma)) (if (eq arma (soldado-arma soldado)) (soldado-carregador soldado) 0)))
(defun avisar (sessao texto)
  (setf (sessao-mensagem sessao) texto (sessao-mensagem-ate sessao) (+ 3.0 (sessao-tempo sessao))))

(defun montar-mapa (sessao)
  (dolist (registro *mapa-teste*)
    (case (first registro)
      ((parede porta)
       (destructuring-bind (categoria x z largura profundidade altura &optional tipo) registro
         (push (criar-obstaculo :x (float x) :z (float z) :largura (float largura)
                :profundidade (float profundidade) :altura (float altura)
                :tipo (if (eq categoria 'porta) :porta (intern (symbol-name tipo) :keyword)))
               (sessao-obstaculos sessao))))
      (suprimento
       (destructuring-bind (categoria x z arma fuzil escopeta iscas equipamento &optional (carabina 0) (submetralhadora 0) (precisao 0) (franco-atirador 0)) registro
         (declare (ignore categoria))
         (push (criar-suprimento :x (float x) :z (float z) :fuzil fuzil :escopeta escopeta :iscas iscas :carabina carabina :submetralhadora submetralhadora :precisao precisao :franco-atirador franco-atirador
                 :arma (unless (eq arma 'nenhuma) (intern (symbol-name arma) :keyword))
                 :equipamento (unless (eq equipamento 'nenhum) (intern (symbol-name equipamento) :keyword)))
               (sessao-suprimentos sessao))))))
  sessao)

(defun obstaculos-solidos (sessao)
  (remove-if #'obstaculo-aberto (sessao-obstaculos sessao)))

(defun bloqueado-p (sessao x z &optional (raio 0.38))
  (or (> (abs x) *limite-mapa*) (> (abs z) *limite-mapa*)
      (some (lambda (parede)
              (and (< (abs (- x (obstaculo-x parede))) (+ raio (/ (obstaculo-largura parede) 2)))
                   (< (abs (- z (obstaculo-z parede))) (+ raio (/ (obstaculo-profundidade parede) 2)))))
            (obstaculos-solidos sessao))))

(defun segmento-caixa (x y z dx dy dz parede &optional (limite 100.0))
  "Calcula a interseção do segmento com o volume nos três eixos."
  (let ((entrada 0.0) (saida limite))
    (loop for origem in (list x y z)
          for direcao in (list dx dy dz)
          for minimo in (list (- (obstaculo-x parede) (/ (obstaculo-largura parede) 2)) 0.0
                               (- (obstaculo-z parede) (/ (obstaculo-profundidade parede) 2)))
          for maximo in (list (+ (obstaculo-x parede) (/ (obstaculo-largura parede) 2))
                               (obstaculo-altura parede)
                               (+ (obstaculo-z parede) (/ (obstaculo-profundidade parede) 2)))
          do (if (< (abs direcao) 0.00001)
                 (unless (<= minimo origem maximo) (return-from segmento-caixa nil))
                 (let ((primeiro (/ (- minimo origem) direcao))
                       (segundo (/ (- maximo origem) direcao)))
                   (setf entrada (max entrada (min primeiro segundo))
                         saida (min saida (max primeiro segundo)))
                   (when (> entrada saida) (return-from segmento-caixa nil)))))
    entrada))

(defun passagem-livre-p (sessao x z outro-x outro-z)
  (let ((trechos (max 1 (ceiling (/ (distancia x z outro-x outro-z) 0.4)))))
    (loop for trecho from 1 to trechos
          always (not (bloqueado-p sessao (+ x (* (/ trecho trechos) (- outro-x x)))
                                   (+ z (* (/ trecho trechos) (- outro-z z))) 0.42)))))

(defun celula-navegavel (sessao x z)
  "Escolhe uma célula livre próxima quando arredondar encostaria numa parede."
  (let ((melhor nil) (menor most-positive-single-float))
    (loop for coluna from (- (round x) 2) to (+ (round x) 2)
          do (loop for linha from (- (round z) 2) to (+ (round z) 2)
                   for separacao = (distancia x z coluna linha)
                   when (and (< separacao menor) (not (bloqueado-p sessao coluna linha 0.48)))
                   do (setf melhor (cons coluna linha) menor separacao)))
    melhor))

(defun calcular-rota (sessao x z alvo-x alvo-z)
  "Busca em largura na grade estática; evita que a IA atravesse trincheiras."
  (let* ((inicio (celula-navegavel sessao x z)) (fim (celula-navegavel sessao alvo-x alvo-z))
         (fila (make-array 10000)) (lidos 0) (total 1) (pais (make-hash-table :test #'equal))
         (encontrado nil))
    (unless (and inicio fim) (return-from calcular-rota nil))
    (setf (aref fila 0) inicio (gethash inicio pais) :inicio)
    (loop while (< lidos total) for atual = (aref fila lidos)
          do (incf lidos)
             (when (equal atual fim) (setf encontrado atual) (return))
             (dolist (deslocamento '((1 . 0) (-1 . 0) (0 . 1) (0 . -1)))
               (let ((vizinho (cons (+ (car atual) (car deslocamento))
                                    (+ (cdr atual) (cdr deslocamento)))))
                 (when (and (not (gethash vizinho pais))
                            (not (bloqueado-p sessao (car vizinho) (cdr vizinho) 0.48)))
                   (setf (gethash vizinho pais) atual (aref fila total) vizinho)
                   (incf total)))))
    (when encontrado
      (let ((caminho nil))
        (loop until (equal encontrado inicio)
              do (push encontrado caminho) (setf encontrado (gethash encontrado pais)))
        caminho))))

(defun registrar-aprendizado (sessao chave descricao)
  (let ((soldado (sessao-soldado sessao)))
    (when (and soldado (< (soldado-ferimentos soldado) 2)
               (not (find chave (soldado-aprendizados soldado) :key #'evidencia-conhecimento)))
      (push (criar-evidencia :conhecimento chave :soldado (soldado-numero soldado)
                            :instante (sessao-tempo sessao) :descricao descricao)
            (soldado-aprendizados soldado)))))

(defun ouvir-ruido (sessao inimigo ruido)
  (let* ((separacao (distancia (inimigo-x inimigo) (inimigo-z inimigo) (ruido-x ruido) (ruido-z ruido)))
         (paredes (count-if (lambda (parede)
                             (segmento-caixa (ruido-x ruido) 0.8 (ruido-z ruido)
                                             (- (inimigo-x inimigo) (ruido-x ruido)) 0.0
                                             (- (inimigo-z inimigo) (ruido-z ruido)) parede 1.0))
                           (obstaculos-solidos sessao)))
         (alcance (* (ruido-alcance ruido) (expt 0.65 paredes))))
    (when (< separacao alcance)
      (when (and (member (ruido-origem ruido) '(:isca :temporizador))
                 (member (inimigo-estado inimigo) '(:investigar :buscar))
                 (eql (inimigo-rastreado inimigo) (ruido-soldado ruido))
                 (> (distancia (inimigo-alvo-x inimigo) (inimigo-alvo-z inimigo)
                               (ruido-x ruido) (ruido-z ruido)) 2.0))
        (when (eql (ruido-soldado ruido) (soldado-numero (sessao-soldado sessao)))
          (registrar-aprendizado sessao (if (eq (ruido-origem ruido) :temporizador) :temporizador :distracao)
                                "Uma isca desviou uma criatura da última posição ouvida do soldado.")))
      (setf (inimigo-alvo-x inimigo) (ruido-x ruido)
            (inimigo-alvo-z inimigo) (ruido-z ruido)
            (inimigo-pista inimigo) (sessao-tempo sessao)
            (inimigo-rastreado inimigo) (unless (member (ruido-origem ruido) '(:isca :temporizador)) (ruido-soldado ruido))
            (inimigo-estado inimigo) :investigar
            (inimigo-rota inimigo) nil (inimigo-recalculo inimigo) 0.0))))

(defun emitir-ruido (sessao x z alcance origem &optional numero)
  (let ((ruido (criar-ruido :x x :z z :alcance alcance :origem origem
                           :soldado numero :instante (sessao-tempo sessao))))
    (when (and numero (not (member origem '(:isca :temporizador))) (sessao-soldado sessao))
      (setf (soldado-ultimo-ruido (sessao-soldado sessao)) (sessao-tempo sessao)))
    (push ruido (sessao-ruidos sessao))
    (when (> (length (sessao-ruidos sessao)) 32) (setf (cdr (nthcdr 31 (sessao-ruidos sessao))) nil))
    (push ruido (sessao-sons sessao))
    (dolist (inimigo (sessao-inimigos sessao)) (when (vivo-p inimigo) (ouvir-ruido sessao inimigo ruido)))
    ruido))

(defun som-local (sessao x z origem)
  "Vocalizações são audíveis ao jogador, mas não realimentam a caça."
  (push (criar-ruido :x x :z z :origem origem :instante (sessao-tempo sessao)) (sessao-sons sessao)))

(defun mover-soldado (sessao frente lado intervalo)
  (let* ((soldado (sessao-soldado sessao))
         (comprimento (max 1.0 (sqrt (+ (* frente frente) (* lado lado)))))
         (velocidade (cond ((soldado-agachado soldado) *velocidade-agachado*)
                          ((soldado-correndo soldado) *velocidade-corrida*)
                          (t *velocidade-marcha*)))
         (angulo (soldado-angulo soldado))
         (dx (* velocidade intervalo (/ (+ (* frente (sin angulo)) (* lado (cos angulo))) comprimento)))
         (dz (* velocidade intervalo (/ (+ (* (- frente) (cos angulo)) (* lado (sin angulo))) comprimento)))
         (anterior-x (soldado-x soldado)) (anterior-z (soldado-z soldado)))
    (unless (bloqueado-p sessao (+ anterior-x dx) anterior-z)
      (incf (soldado-x soldado) dx))
    (unless (bloqueado-p sessao (soldado-x soldado) (+ anterior-z dz))
      (incf (soldado-z soldado) dz))
    (let ((trajeto (distancia anterior-x anterior-z (soldado-x soldado) (soldado-z soldado))))
      (setf (soldado-movimento soldado) (/ trajeto (max intervalo 0.001)))
      (when (> trajeto 0.001) (setf (soldado-apoiado soldado) nil))
      (verificar-gelo sessao trajeto)
      (incf (soldado-passada soldado) trajeto)
      (when (> (soldado-passada soldado) (if (soldado-correndo soldado) 1.65 1.4))
        (setf (soldado-passada soldado) 0.0)
        (emitir-ruido sessao (soldado-x soldado) (soldado-z soldado)
                      (* (fator-passos sessao) (if (eq (soldado-preparo soldado) :silencio) 0.5 1.0)
                         (cond ((soldado-agachado soldado) *alcance-agachado*)
                               ((soldado-correndo soldado) *alcance-corrida*) (t *alcance-passos*)))
                      (som-superficie sessao) (soldado-numero soldado))))))

(defun altura-olhos (soldado) (if (soldado-agachado soldado) 1.05 1.7))

(defun alvo-do-disparo (sessao angulo inclinacao)
  (let* ((soldado (sessao-soldado sessao))
         (x (soldado-x soldado)) (y (altura-olhos soldado)) (z (soldado-z soldado))
         (dx (* (sin angulo) (cos inclinacao))) (dy (sin inclinacao))
         (dz (* (- (cos angulo)) (cos inclinacao))) (mais-perto 55.0) (alvo nil))
    (dolist (parede (obstaculos-solidos sessao))
      (let ((toque (segmento-caixa x y z dx dy dz parede mais-perto)))
        (when toque (setf mais-perto toque))))
    (dolist (inimigo (sessao-inimigos sessao))
      (when (vivo-p inimigo)
        (let* ((ex (- (inimigo-x inimigo) x)) (ey (- 1.05 y)) (ez (- (inimigo-z inimigo) z))
               (projecao (+ (* ex dx) (* ey dy) (* ez dz)))
               (desvio (- (+ (* ex ex) (* ey ey) (* ez ez)) (* projecao projecao))))
          (when (and (> projecao 0.0) (< desvio 0.72))
            (let ((toque (- projecao (sqrt (- 0.72 desvio)))))
              (when (< toque mais-perto) (setf mais-perto toque alvo inimigo)))))))
    (values alvo mais-perto (+ y (* dy mais-perto)))))

(defun disparar (sessao)
  (when (eq (sessao-fase sessao) :combate)
    (let ((soldado (sessao-soldado sessao)))
      (when (and (plusp (soldado-carregador soldado)) (plusp (soldado-recarga soldado)))
        (setf (soldado-recarga soldado) 0.0))
      (when (and (<= (soldado-espera-tiro soldado) 0) (<= (soldado-recarga soldado) 0)
                 (not (soldado-correndo soldado)) (<= (soldado-troca soldado) 0))
        (when (zerop (soldado-carregador soldado))
          (avisar sessao "Arma vazia. R para recarregar.") (return-from disparar nil))
        (decf (soldado-carregador soldado))
        (setf (soldado-espera-tiro soldado) (intervalo-disparo (soldado-arma soldado))
              (soldado-recuo soldado) 1.0)
        (emitir-ruido sessao (soldado-x soldado) (soldado-z soldado) *alcance-disparo*
                      (soldado-arma soldado) (soldado-numero soldado))
        (dolist (desvio (if (not (eq (soldado-arma soldado) :escopeta)) '((0 . 0))
                           '((0 . 0) (0.025 . 0) (-0.025 . 0) (0 . 0.025) (0 . -0.025)
                             (0.04 . 0.02) (-0.04 . -0.02))))
          (multiple-value-bind (alvo alcance altura-impacto)
              (alvo-do-disparo sessao (+ (soldado-angulo soldado) (car desvio))
                               (+ (soldado-inclinacao soldado) (oscilacao-respiracao sessao) (cdr desvio)))
            (when alvo
              (decf (inimigo-vida alvo) (* (if (>= altura-impacto 1.55) 1.6 1.0) (case (soldado-arma soldado)
                                        (:escopeta (if (< alcance 13.0) 36 14))
                                        (:carabina (if (< alcance 25.0) 55 40))
                                        (:submetralhadora (if (< alcance 17.0) 26 18))
                                        (:precisao 75) (:franco-atirador 160) (t 100))))
              (unless (vivo-p alvo)
                (incf (soldado-eliminacoes soldado))
                (when (eq (soldado-apoiado soldado) :bipé)
                  (registrar-aprendizado sessao :bipé "Eliminação com a arma estabilizada pelo bipé."))
                (som-local sessao (inimigo-x alvo) (inimigo-z alvo) :queda)
                (registrar-aprendizado sessao (soldado-arma soldado)
                  (format nil "Eliminação confirmada com ~A na onda ~D."
                          (conhecimento-titulo (procurar-conhecimento (soldado-arma soldado))) (sessao-onda sessao)))))))
        (incf (soldado-inclinacao soldado) (* (if (soldado-mirando soldado) 0.025 0.045)
                               (if (eq (soldado-arma soldado) :submetralhadora) .5 1.0)))
        t))))

(defun iniciar-recarga (sessao)
  (let ((soldado (sessao-soldado sessao)))
    (when (and (eq (sessao-fase sessao) :combate) (zerop (soldado-recarga soldado))
               (< (soldado-carregador soldado) (capacidade-arma (soldado-arma soldado)))
               (plusp (reserva-arma soldado)))
      (setf (soldado-recarga soldado) (duracao-recarga (soldado-arma soldado)) (soldado-apoiado soldado) nil)
      (emitir-ruido sessao (soldado-x soldado) (soldado-z soldado) 5.0 :recarga (soldado-numero soldado)))))

(defun lancar-isca (sessao)
  (let ((soldado (sessao-soldado sessao)))
    (when (and (eq (sessao-fase sessao) :combate) (plusp (soldado-iscas soldado)))
      (decf (soldado-iscas soldado))
      (let ((x (soldado-x soldado)) (z (soldado-z soldado)))
        (loop for trecho from 1 to 14
              for destino-x = (+ (soldado-x soldado) (* trecho (sin (soldado-angulo soldado))))
              for destino-z = (- (soldado-z soldado) (* trecho (cos (soldado-angulo soldado))))
              until (bloqueado-p sessao destino-x destino-z 0.2)
              do (setf x destino-x z destino-z))
        (push (criar-isca :x (soldado-x soldado) :z (soldado-z soldado)
                         :destino-x x :destino-z z :soldado (soldado-numero soldado)) (sessao-iscas sessao))))))

(defun suprimento-proximo (sessao)
  (let ((soldado (sessao-soldado sessao)))
    (find-if (lambda (item) (and (not (suprimento-retirado item))
                                (visivel-p sessao (suprimento-x item) (suprimento-z item) .3)
                                (< (distancia (soldado-x soldado) (soldado-z soldado)
                                              (suprimento-x item) (suprimento-z item)) 2.2)))
             (sessao-suprimentos sessao))))

(defun recolher (sessao)
  (unless (eq (sessao-fase sessao) :combate) (return-from recolher nil))
  (when (interagir-porta sessao) (return-from recolher t))
  (when (recuperar-dispositivo sessao) (return-from recolher t))
  (let ((item (suprimento-proximo sessao)) (soldado (sessao-soldado sessao)))
    (when (and item (eq (sessao-fase sessao) :combate))
      (when (suprimento-equipamento item)
        (unless (guardar-equipamento sessao (suprimento-equipamento item))
          (return-from recolher nil)))
      ;; Descarregar a arma antes da troca conserva cada cartucho.
      (when (and (suprimento-arma item) (not (eq (suprimento-arma item) (soldado-arma soldado))))
        (incf (reserva-arma soldado) (soldado-carregador soldado))
        (push (criar-suprimento :x (soldado-x soldado) :z (soldado-z soldado) :arma (soldado-arma soldado))
              (sessao-suprimentos sessao))
        (setf (soldado-arma soldado) (suprimento-arma item) (soldado-carregador soldado) 0
              (soldado-recarga soldado) 0.0 (soldado-troca soldado) .65 (soldado-apoiado soldado) nil))
      (incf (soldado-reserva-fuzil soldado) (suprimento-fuzil item))
      (incf (soldado-reserva-escopeta soldado) (suprimento-escopeta item))
      (incf (soldado-reserva-carabina soldado) (suprimento-carabina item))
      (incf (soldado-reserva-submetralhadora soldado) (suprimento-submetralhadora item))
      (incf (soldado-reserva-precisao soldado) (suprimento-precisao item))
      (incf (soldado-reserva-franco-atirador soldado) (suprimento-franco-atirador item))
      (incf (soldado-iscas soldado) (suprimento-iscas item))
      (setf (suprimento-retirado item) t)
      (avisar sessao "Equipamento recolhido. R para recarregar.")
      (emitir-ruido sessao (soldado-x soldado) (soldado-z soldado) 4.0 :recarga (soldado-numero soldado))
      t)))

(defun iniciar-onda (sessao)
  (incf (sessao-onda sessao))
  (let ((quantidade (nth (1- (sessao-onda sessao)) *composicao-ondas*)))
    (setf (sessao-inimigos sessao)
          (loop for numero below quantidade
                for acesso = (nth (mod numero 3) '((-37.0 . -28.0) (0.0 . -38.0) (37.0 . -28.0)))
                collect (criar-inimigo :numero numero :tipo (if (and (> (sessao-onda sessao) 1) (zerop numero)) :chamador :comum) :x (+ (car acesso) (* 1.5 (floor numero 3)))
                                       :z (cdr acesso) :alvo-x (* (- (mod numero 3) 1) 10.0)
                                       :alvo-z 9.0 :voz (+ 2.0 numero) :patrulha numero)))
    (avisar sessao (format nil "Onda ~D. Ouça antes de avançar." (sessao-onda sessao)))))

(defun mover-inimigo (sessao inimigo intervalo)
  (let ((x (inimigo-alvo-x inimigo)) (z (inimigo-alvo-z inimigo)))
    (decf (inimigo-recalculo inimigo) intervalo)
    (unless (passagem-livre-p sessao (inimigo-x inimigo) (inimigo-z inimigo) x z)
      (when (<= (inimigo-recalculo inimigo) 0)
        (setf (inimigo-rota inimigo) (calcular-rota sessao (inimigo-x inimigo) (inimigo-z inimigo) x z)
              (inimigo-recalculo inimigo) 1.0))
      (when (and (inimigo-rota inimigo)
                 (< (distancia (inimigo-x inimigo) (inimigo-z inimigo)
                               (caar (inimigo-rota inimigo)) (cdar (inimigo-rota inimigo))) 0.25))
        (pop (inimigo-rota inimigo)))
      (if (inimigo-rota inimigo)
          (setf x (caar (inimigo-rota inimigo)) z (cdar (inimigo-rota inimigo)))
          (setf x (inimigo-x inimigo) z (inimigo-z inimigo))))
    (let* ((separacao (distancia x z (inimigo-x inimigo) (inimigo-z inimigo)))
           (passo (min separacao (* intervalo (if (eq (inimigo-estado inimigo) :patrulha) 1.0 2.1)))))
      (when (> separacao 0.01)
        (let ((dx (* passo (/ (- x (inimigo-x inimigo)) separacao)))
              (dz (* passo (/ (- z (inimigo-z inimigo)) separacao))))
          (unless (bloqueado-p sessao (+ (inimigo-x inimigo) dx) (inimigo-z inimigo) 0.42)
            (incf (inimigo-x inimigo) dx))
          (unless (bloqueado-p sessao (inimigo-x inimigo) (+ (inimigo-z inimigo) dz) 0.42)
            (incf (inimigo-z inimigo) dz))
          (incf (inimigo-movimento inimigo) passo))))))

(defun atualizar-inimigo (sessao inimigo intervalo)
  (let* ((soldado (sessao-soldado sessao))
         (perto (and (< (distancia (inimigo-x inimigo) (inimigo-z inimigo)
                                  (soldado-x soldado) (soldado-z soldado)) 1.35)
                     (passagem-livre-p sessao (inimigo-x inimigo) (inimigo-z inimigo)
                                       (soldado-x soldado) (soldado-z soldado)))))
    (decf (inimigo-intervalo inimigo) intervalo)
    (decf (inimigo-voz inimigo) intervalo)
    (when (<= (inimigo-voz inimigo) 0)
      (som-local sessao (inimigo-x inimigo) (inimigo-z inimigo) :criatura)
      (setf (inimigo-voz inimigo) (+ 4.0 (mod (inimigo-numero inimigo) 3))))
    (cond
      ((plusp (inimigo-chamado inimigo))
       (decf (inimigo-chamado inimigo) intervalo)
       (when (<= (inimigo-chamado inimigo) 0)
         (setf (inimigo-chamado inimigo) 0.0)
         (emitir-ruido sessao (inimigo-x inimigo) (inimigo-z inimigo) 45.0 :chamado)))
      ((and perto (eq (inimigo-tipo inimigo) :chamador) (not (inimigo-chamou inimigo)))
       (setf (inimigo-chamou inimigo) t (inimigo-chamado inimigo) *tempo-chamado*)
       (som-local sessao (inimigo-x inimigo) (inimigo-z inimigo) :aviso-chamado))
      ((plusp (inimigo-ataque inimigo))
       (decf (inimigo-ataque inimigo) intervalo)
       (when (<= (inimigo-ataque inimigo) 0)
         (setf (inimigo-intervalo inimigo) 1.8)
         (when perto
           (incf (soldado-ferimentos soldado))
           (som-local sessao (soldado-x soldado) (soldado-z soldado) :ferimento)
           (when (>= (soldado-ferimentos soldado) 2) (encerrar-vida sessao)))))
      ((and perto (<= (inimigo-intervalo inimigo) 0))
       (setf (inimigo-ataque inimigo) 0.8)
       (som-local sessao (inimigo-x inimigo) (inimigo-z inimigo) :ataque))
      (perto nil)
      (t
       (when (and (eq (inimigo-estado inimigo) :buscar)
                  (> (- (sessao-tempo sessao) (inimigo-busca inimigo)) *duracao-busca*))
         (when (and (eql (inimigo-rastreado inimigo) (soldado-numero soldado))
                    (<= (soldado-ultimo-ruido soldado) (+ 0.001 (inimigo-pista inimigo))))
           (registrar-aprendizado sessao :silencio
                                 "A criatura encerrou a busca enquanto o soldado permaneceu em silêncio."))
         (setf (inimigo-estado inimigo) :patrulha (inimigo-rastreado inimigo) nil))
       (when (< (distancia (inimigo-x inimigo) (inimigo-z inimigo)
                          (inimigo-alvo-x inimigo) (inimigo-alvo-z inimigo)) 0.7)
         (if (eq (inimigo-estado inimigo) :patrulha)
             (let ((destino (nth (mod (incf (inimigo-patrulha inimigo)) 6)
                                '((-10 . 9) (0 . -5) (10 . 9) (21 . 2) (0 . 16) (-21 . 2)))))
               (setf (inimigo-alvo-x inimigo) (float (car destino))
                     (inimigo-alvo-z inimigo) (float (cdr destino))))
             (unless (eq (inimigo-estado inimigo) :buscar)
               (setf (inimigo-estado inimigo) :buscar
                     (inimigo-busca inimigo) (sessao-tempo sessao)))))
       (unless (eq (inimigo-estado inimigo) :buscar) (mover-inimigo sessao inimigo intervalo))))))

(defun atualizar-campo (sessao intervalo &key (frente 0.0) (lado 0.0) gatilho)
  (when (eq (sessao-fase sessao) :combate)
    (incf (sessao-tempo sessao) intervalo)
    (atualizar-clima sessao intervalo)
    (atualizar-dispositivos sessao intervalo)
    (let ((soldado (sessao-soldado sessao)))
      (when (and (eq (soldado-apoiado soldado) :bipé) (not (soldado-agachado soldado)))
        (setf (soldado-apoiado soldado) nil))
      (mover-soldado sessao frente lado intervalo)
      (setf (soldado-troca soldado) (max 0.0 (- (soldado-troca soldado) intervalo)))
      (when (and gatilho (eq (soldado-arma soldado) :submetralhadora)) (disparar sessao))
      (when (>= (sessao-tempo sessao) (sessao-exploracao-em sessao))
        (explorar-campo sessao)
        (setf (sessao-exploracao-em sessao) (+ (sessao-tempo sessao) .25)))
      (setf (soldado-espera-tiro soldado) (max 0.0 (- (soldado-espera-tiro soldado) intervalo))
            (soldado-recuo soldado) (max 0.0 (- (soldado-recuo soldado) (* intervalo 3.5))))
      (when (plusp (soldado-recarga soldado))
        (setf (soldado-recarga soldado) (max 0.0 (- (soldado-recarga soldado) intervalo)))
        (when (zerop (soldado-recarga soldado))
          (when (plusp (reserva-arma soldado))
            (let ((quantidade (if (eq (soldado-arma soldado) :submetralhadora)
                                 (min (reserva-arma soldado) (- (capacidade-arma (soldado-arma soldado)) (soldado-carregador soldado))) 1)))
              (incf (soldado-carregador soldado) quantidade) (decf (reserva-arma soldado) quantidade))
            (when (< (soldado-carregador soldado) (capacidade-arma (soldado-arma soldado)))
              (iniciar-recarga sessao))))))
    (dolist (isca (sessao-iscas sessao))
      (decf (isca-tempo isca) intervalo)
      (when (<= (isca-tempo isca) 0)
        (emitir-ruido sessao (isca-destino-x isca) (isca-destino-z isca) *alcance-isca* :isca (isca-soldado isca))))
    (setf (sessao-iscas sessao) (delete-if (lambda (isca) (<= (isca-tempo isca) 0)) (sessao-iscas sessao)))
    (dolist (inimigo (sessao-inimigos sessao))
      (unless (vivo-p inimigo) (setf (inimigo-queda inimigo) (min 1.0 (+ (inimigo-queda inimigo) (* intervalo 2.2)))))
      (when (and (vivo-p inimigo) (eq (sessao-fase sessao) :combate))
        (atualizar-inimigo sessao inimigo intervalo)))
    (when (and (eq (sessao-fase sessao) :combate) (notany #'vivo-p (sessao-inimigos sessao)))
      (if (= (sessao-onda sessao) (length *composicao-ondas*))
          (setf (sessao-fase sessao) :vitoria)
          (progn
            (when (zerop (sessao-espera-onda sessao))
              (setf (sessao-espera-onda sessao) *intervalo-ondas*)
              (avisar sessao "O setor silenciou. Recarregue e procure suprimentos."))
            (decf (sessao-espera-onda sessao) intervalo)
            (when (<= (sessao-espera-onda sessao) 0)
              (setf (sessao-espera-onda sessao) 0.0) (iniciar-onda sessao)))))))

;;; Superfícies, clima e equipamento usam eventos sonoros da mesma simulação.
(defun superficie-em (x z)
  (find-if (lambda (registro)
             (and (eq (first registro) 'superficie)
                  (<= (abs (- x (second registro))) (/ (fourth registro) 2))
                  (<= (abs (- z (third registro))) (/ (fifth registro) 2)))) *mapa-teste*))
(defun superficie-soldado (sessao)
  (let ((soldado (sessao-soldado sessao)))
    (superficie-em (soldado-x soldado) (soldado-z soldado))))
(defun fator-passos (sessao)
  (* (case (sixth (superficie-soldado sessao)) (madeira 1.25) (metal 1.8) (t 1.0))
     (if (eq (sessao-clima sessao) :rajada) .5 1.0)))
(defun som-superficie (sessao)
  (case (sixth (superficie-soldado sessao)) (madeira :madeira) (metal :metal) (t :passo)))
(defun verificar-gelo (sessao trajeto)
  (let ((superficie (superficie-soldado sessao)) (soldado (sessao-soldado sessao)))
    (when (and (> trajeto 0.001) (eq (sixth superficie) 'gelo)
               (not (member superficie (sessao-gelo-partido sessao) :test #'equal)))
      (push superficie (sessao-gelo-partido sessao))
      (emitir-ruido sessao (soldado-x soldado) (soldado-z soldado) 28.0 :gelo (soldado-numero soldado)))))
(defun atualizar-clima (sessao intervalo)
  (decf (sessao-tempo-clima sessao) intervalo)
  (when (<= (sessao-tempo-clima sessao) 0)
    (case (sessao-clima sessao)
      (:calmaria (setf (sessao-clima sessao) :aviso (sessao-tempo-clima sessao) 4.0))
      (:aviso (setf (sessao-clima sessao) :rajada (sessao-tempo-clima sessao) 10.0))
      (:rajada
       (setf (sessao-semente sessao) (mod (+ (* 1664525 (sessao-semente sessao)) 1013904223) 4294967296)
             (sessao-clima sessao) :calmaria
             (sessao-tempo-clima sessao) (float (+ 30 (mod (sessao-semente sessao) 16))))))))
(defun distancia-visivel (sessao) (if (eq (sessao-clima sessao) :rajada) 18.0 *fim-neblina*))

(defun visivel-p (sessao x z &optional (altura .2))
  (let* ((soldado (sessao-soldado sessao)) (olhos (altura-olhos soldado)))
    (and (< (distancia (soldado-x soldado) (soldado-z soldado) x z) (distancia-visivel sessao))
         (notany (lambda (parede)
                   (segmento-caixa (soldado-x soldado) olhos (soldado-z soldado)
                                   (- x (soldado-x soldado)) (- altura olhos)
                                   (- z (soldado-z soldado)) parede .995))
                 (obstaculos-solidos sessao)))))
(defun terreno-no-cone-p (soldado x z)
  "Cone conservador dentro da imagem; lunetas não revelam terreno periférico."
  (let* ((dx (- x (soldado-x soldado))) (dy (- .2 (altura-olhos soldado)))
         (dz (- z (soldado-z soldado))) (separacao (sqrt (+ (* dx dx) (* dy dy) (* dz dz))))
         (angulo (soldado-angulo soldado)) (inclinacao (soldado-inclinacao soldado))
         (zoom (ampliacao-arma (soldado-arma soldado)))
         (abertura (if (soldado-mirando soldado) (if (> zoom 1.0) (/ .4 zoom) .28) .45)))
    (> (/ (+ (* dx (sin angulo) (cos inclinacao)) (* dy (sin inclinacao))
              (* (- dz) (cos angulo) (cos inclinacao))) (max .001 separacao))
       (cos abertura))))

(defun explorar-campo (sessao)
  "Amostra terreno de dois metros no cone observado; não registra inimigos."
  (let* ((soldado (sessao-soldado sessao)) (raio (distancia-visivel sessao))
         (x (soldado-x soldado)) (z (soldado-z soldado)))
    (loop for coluna from (max (- *meia-grade-mapa*) (floor (- x raio) 2)) to (min (1- *meia-grade-mapa*) (ceiling (+ x raio) 2))
          do (loop for linha from (max (- *meia-grade-mapa*) (floor (- z raio) 2)) to (min (1- *meia-grade-mapa*) (ceiling (+ z raio) 2))
                   for cx = (+ 1 (* 2 coluna)) for cz = (+ 1 (* 2 linha))
                   for separacao = (distancia x z cx cz)
                   when (and (or (< separacao 2.0)
                                 (terreno-no-cone-p soldado cx cz))
                             (visivel-p sessao cx cz))
                   do (setf (gethash (cons coluna linha) (soldado-explorado soldado)) t)))))
(defun adicionar-marca (sessao coluna linha texto)
  (when (and (eq (sessao-fase sessao) :notas) (gethash (cons coluna linha) (sessao-explorado sessao))
             (<= (length texto) 48))
    (setf (sessao-marcas sessao)
          (remove (cons coluna linha) (sessao-marcas sessao) :key #'first :test #'equal))
    (unless (zerop (length texto))
      (when (>= (length (sessao-marcas sessao)) 24) (return-from adicionar-marca nil))
      (push (list (cons coluna linha) (copy-seq texto)) (sessao-marcas sessao)))
    t))

(defun porta-proxima (sessao)
  (let ((soldado (sessao-soldado sessao)))
    (find-if (lambda (parede)
               (and (eq (obstaculo-tipo parede) :porta)
                    (< (distancia (soldado-x soldado) (soldado-z soldado)
                                  (obstaculo-x parede) (obstaculo-z parede)) 2.8)
                    (visivel-p sessao (obstaculo-x parede) (obstaculo-z parede) 2.1)))
             (sessao-obstaculos sessao))))
(defun interagir-porta (sessao)
  (let ((porta (porta-proxima sessao)) (soldado (sessao-soldado sessao)))
    (when porta
      ;; Não fechar o portão sobre o soldado ou sobre uma criatura.
      (when (and (obstaculo-aberto porta)
                 (some (lambda (posicao)
                         (and (< (abs (- (car posicao) (obstaculo-x porta))) (+ .5 (/ (obstaculo-largura porta) 2)))
                              (< (abs (- (cdr posicao) (obstaculo-z porta))) .7)))
                       (cons (cons (soldado-x soldado) (soldado-z soldado))
                             (loop for inimigo in (sessao-inimigos sessao) when (vivo-p inimigo)
                                   collect (cons (inimigo-x inimigo) (inimigo-z inimigo))))))
        (avisar sessao "Passagem ocupada.") (return-from interagir-porta t))
      (setf (obstaculo-aberto porta) (not (obstaculo-aberto porta)))
      (dolist (inimigo (sessao-inimigos sessao))
        (setf (inimigo-rota inimigo) nil (inimigo-recalculo inimigo) 0.0))
      (emitir-ruido sessao (obstaculo-x porta) (obstaculo-z porta) 22.0 :porta (soldado-numero soldado))
      t)))
(defun possui-equipamento-p (soldado equipamento)
  (or (eq (soldado-preparo soldado) equipamento) (eq (soldado-equipamento soldado) equipamento)))
(defun guardar-equipamento (sessao equipamento)
  (let ((soldado (sessao-soldado sessao)))
    (when (possui-equipamento-p soldado equipamento)
      (avisar sessao "Você já carrega esse dispositivo.") (return-from guardar-equipamento nil))
    (when (and (eq (soldado-equipamento soldado) :temporizador) (dispositivo-do-soldado sessao))
      (avisar sessao "Recupere a isca instalada antes de trocar.") (return-from guardar-equipamento nil))
    (when (soldado-equipamento soldado)
      (push (criar-suprimento :x (soldado-x soldado) :z (soldado-z soldado)
                              :equipamento (soldado-equipamento soldado)) (sessao-suprimentos sessao)))
    (setf (soldado-equipamento soldado) equipamento (soldado-apoiado soldado) nil)
    t))
(defun dispositivo-do-soldado (sessao)
  (find (soldado-numero (sessao-soldado sessao)) (sessao-dispositivos sessao) :key #'dispositivo-soldado))
(defun colocar-dispositivo (sessao)
  (let ((soldado (sessao-soldado sessao)))
    (when (and (eq (sessao-fase sessao) :combate) (possui-equipamento-p soldado :temporizador)
               (not (dispositivo-do-soldado sessao)))
      (push (criar-dispositivo :x (soldado-x soldado) :z (soldado-z soldado) :soldado (soldado-numero soldado))
            (sessao-dispositivos sessao))
      (avisar sessao "Isca armada. Três segundos para sair.") t)))
(defun atualizar-dispositivos (sessao intervalo)
  (dolist (dispositivo (sessao-dispositivos sessao))
    (incf (dispositivo-tempo dispositivo) intervalo)
    (when (and (>= (dispositivo-tempo dispositivo) (dispositivo-pulso dispositivo))
               (< (dispositivo-pulso dispositivo) (+ *atraso-dispositivo* *duracao-dispositivo*)))
      (incf (dispositivo-pulso dispositivo) 1.0)
      (emitir-ruido sessao (dispositivo-x dispositivo) (dispositivo-z dispositivo) 30.0
                    :temporizador (dispositivo-soldado dispositivo)))))
(defun dispositivo-proximo (sessao)
  (let ((soldado (sessao-soldado sessao)))
    (find-if (lambda (dispositivo)
               (and (< (distancia (soldado-x soldado) (soldado-z soldado)
                                  (dispositivo-x dispositivo) (dispositivo-z dispositivo)) 2.2)
                    (visivel-p sessao (dispositivo-x dispositivo) (dispositivo-z dispositivo))))
             (sessao-dispositivos sessao))))
(defun recuperar-dispositivo (sessao)
  (let ((dispositivo (dispositivo-proximo sessao)) (soldado (sessao-soldado sessao)))
    (when dispositivo
      (when (or (eql (dispositivo-soldado dispositivo) (soldado-numero soldado))
                (guardar-equipamento sessao :temporizador))
        (setf (sessao-dispositivos sessao) (remove dispositivo (sessao-dispositivos sessao)))
        (avisar sessao "Dispositivo recuperado e desarmado."))
      t)))
(defun apoiar-arma (sessao)
  (let ((soldado (sessao-soldado sessao)))
    (when (and (eq (sessao-fase sessao) :combate) (< (soldado-movimento soldado) .01)
               (zerop (soldado-recarga soldado)))
      (setf (soldado-apoiado soldado)
            (unless (soldado-apoiado soldado)
              (cond ((and (soldado-agachado soldado) (possui-equipamento-p soldado :bipé)) :bipé)
                    ((some (lambda (parede)
                             (and (<= .8 (obstaculo-altura parede) 1.8)
                                  (< (abs (- (soldado-x soldado) (obstaculo-x parede)))
                                     (+ .8 (/ (obstaculo-largura parede) 2)))
                                  (< (abs (- (soldado-z soldado) (obstaculo-z parede)))
                                     (+ .8 (/ (obstaculo-profundidade parede) 2)))))
                           (obstaculos-solidos sessao)) :cobertura))))
      (avisar sessao (if (soldado-apoiado soldado) "Arma apoiada." "Sem apoio ao alcance."))
      (soldado-apoiado soldado))))
(defun oscilacao-respiracao (sessao)
  (let ((soldado (sessao-soldado sessao)))
    (* (if (soldado-apoiado soldado) .0007 .004)
       (if (soldado-mirando soldado) 1.0 .3) (sin (* (sessao-tempo sessao) 1.8)))))
