(in-package #:rimefall)

;;; Regras do combate offline, em metros e passo fixo. A apresentação somente
;;; entrega intenções de entrada; nunca move personagens por quadro renderizado.
(defparameter *armas-guerra*
  '((:fuzil 8 48 .65 2.6 240.0) (:carabina 12 60 .32 2.2 170.0)
    (:metralhadora 30 120 .14 3.4 200.0) (:escopeta 6 30 .85 2.8 45.0)
    (:pistola 10 50 .28 1.8 75.0) (:precisao 10 20 .55 2.4 260.0)
    (:franco-atirador 5 10 1.15 3.3 360.0)))
(defvar *indice-colisoes-guerra* (make-hash-table :test #'equal))
(defvar *celulas-livres-guerra* (make-hash-table :test #'equal))
(defvar *caixas-guerra* nil)

(defun dados-arma-guerra (jogador) (or (assoc (jogador-guerra-arma jogador) *armas-guerra*) (first *armas-guerra*)))
(defun equipar-guerra (jogador)
  (setf (jogador-guerra-municao jogador) (second (dados-arma-guerra jogador))
        (jogador-guerra-reserva jogador) (third (dados-arma-guerra jogador))
        (jogador-guerra-tempo-recarga jogador) 0.0 (jogador-guerra-tempo-arma jogador) 0.0
        (jogador-guerra-ferimentos jogador) 0 (jogador-guerra-reanimacoes jogador) 0
        (jogador-guerra-inclinacao jogador) 0.0 (jogador-guerra-caminho jogador) nil
        (jogador-guerra-supressao jogador) 0.0))

(defun trocar-arma-guerra (jogador deslocamento)
  "Percorre as armas conhecidas sem criar munição além da reserva atual."
  (let* ((nomes (mapcar #'first *armas-guerra*))
         (atual (or (position (jogador-guerra-arma jogador) nomes) 0))
         (nova (nth (mod (+ atual deslocamento) (length nomes)) nomes))
         (total (+ (jogador-guerra-municao jogador) (jogador-guerra-reserva jogador)))
         (capacidade (second (assoc nova *armas-guerra*))))
    (setf (jogador-guerra-arma jogador) nova
          (jogador-guerra-municao jogador) (min capacidade total)
          (jogador-guerra-reserva jogador) (max 0 (- total (jogador-guerra-municao jogador)))
          (jogador-guerra-tempo-recarga jogador) 0.0
          (jogador-guerra-tempo-arma jogador) 0.0)
    nova))

(defun preparar-colisoes-guerra ()
  (clrhash *indice-colisoes-guerra*) (clrhash *celulas-livres-guerra*)
  (setf *caixas-guerra*
        (loop for (x z largura profundidade altura) in *volumes-guerra*
              collect (criar-obstaculo :x x :z z :largura largura :profundidade profundidade :altura altura)))
  (dolist (caixa *caixas-guerra*)
    (loop for x from (floor (- (obstaculo-x caixa) (/ (obstaculo-largura caixa) 2) 1) 8)
          to (floor (+ (obstaculo-x caixa) (/ (obstaculo-largura caixa) 2) 1) 8)
          do (loop for z from (floor (- (obstaculo-z caixa) (/ (obstaculo-profundidade caixa) 2) 1) 8)
                   to (floor (+ (obstaculo-z caixa) (/ (obstaculo-profundidade caixa) 2) 1) 8)
                   do (push caixa (gethash (cons x z) *indice-colisoes-guerra*)))))
  t)
(preparar-colisoes-guerra)

(defun colisao-guerra-p (x z &optional (raio .38))
  (or (> (abs x) (- *limite-mapa-guerra* raio)) (> (abs z) (- *limite-mapa-guerra* raio))
      (some (lambda (caixa)
              (and (< (abs (- x (obstaculo-x caixa))) (+ raio (/ (obstaculo-largura caixa) 2)))
                   (< (abs (- z (obstaculo-z caixa))) (+ raio (/ (obstaculo-profundidade caixa) 2)))))
            (gethash (cons (floor x 8) (floor z 8)) *indice-colisoes-guerra*))))

(defun mover-jogador-guerra (guerra jogador dx dz)
  (declare (ignore guerra))
  (when (jogador-ativo-p jogador)
    (let ((antes-x (jogador-guerra-x jogador)) (antes-z (jogador-guerra-z jogador))
          (passos (max 1 (ceiling (max (abs dx) (abs dz)) .25))))
      (dotimes (passo passos)
        (unless (colisao-guerra-p (+ (jogador-guerra-x jogador) (/ dx passos)) (jogador-guerra-z jogador))
          (incf (jogador-guerra-x jogador) (/ dx passos)))
        (unless (colisao-guerra-p (jogador-guerra-x jogador) (+ (jogador-guerra-z jogador) (/ dz passos)))
          (incf (jogador-guerra-z jogador) (/ dz passos))))
      (let ((distancia (distancia antes-x antes-z (jogador-guerra-x jogador) (jogador-guerra-z jogador))))
        (incf (jogador-guerra-passada jogador) (* distancia 3.0))
        (setf (jogador-guerra-movimento jogador) (if (> distancia .0001) 1.0 0.0))
        (> distancia .0001)))))



(defun altura-jogador-guerra (jogador)
  (cond ((not (jogador-ativo-p jogador)) .45) ((jogador-guerra-agachado jogador) 1.0) (t 1.65)))

(defun distancia-parede-guerra (x y z dx dy dz alcance)
  (let ((menor alcance))
    (dolist (parede *caixas-guerra* menor)
      (when (and (<= (abs (- (obstaculo-x parede) x)) (+ alcance (/ (obstaculo-largura parede) 2)))
                 (<= (abs (- (obstaculo-z parede) z)) (+ alcance (/ (obstaculo-profundidade parede) 2))))
        (let ((toque (segmento-caixa x y z dx dy dz parede menor)))
          (when toque (setf menor (min menor toque))))))))

(defun linha-livre-guerra-p (jogador outro)
  (let* ((dx (- (jogador-guerra-x outro) (jogador-guerra-x jogador)))
         (dz (- (jogador-guerra-z outro) (jogador-guerra-z jogador)))
         (dist (max .001 (sqrt (+ (* dx dx) (* dz dz))))))
    (>= (distancia-parede-guerra (jogador-guerra-x jogador) 1.45 (jogador-guerra-z jogador)
                               (/ dx dist) 0.0 (/ dz dist) dist) (- dist .1))))

(defun alvo-mais-proximo-guerra (guerra jogador &optional (distancia-maxima 150.0))
  (let ((melhor nil) (menor distancia-maxima))
    (dolist (outro (guerra-jogadores guerra) melhor)
      (when (and (jogador-ativo-p outro)
                 (not (eq (jogador-guerra-exercito outro) (jogador-guerra-exercito jogador)))
                 (< (distancia-guerra jogador outro) menor) (linha-livre-guerra-p jogador outro))
        (setf melhor outro menor (distancia-guerra jogador outro))))))

(defun alvo-na-mira-guerra (guerra jogador)
  "Raio da câmera contra coberturas e volumes humanos; inclui fogo amigo."
  (let* ((angulo (jogador-guerra-angulo jogador)) (inclinacao (jogador-guerra-inclinacao jogador))
         (dx (* (sin angulo) (cos inclinacao))) (dy (sin inclinacao))
         (dz (* (- (cos angulo)) (cos inclinacao)))
         (x (jogador-guerra-x jogador)) (y (altura-jogador-guerra jogador)) (z (jogador-guerra-z jogador))
         (menor (distancia-parede-guerra x y z dx dy dz (sixth (dados-arma-guerra jogador)))) (alvo nil))
    (dolist (outro (guerra-jogadores guerra))
      (when (and (not (eq jogador outro)) (member (jogador-guerra-estado outro) '(:ativo :incapacitado)))
        (let ((toque (segmento-caixa x y z dx dy dz
                      (criar-obstaculo :x (jogador-guerra-x outro) :z (jogador-guerra-z outro)
                       :largura .75 :profundidade .75 :altura (+ .15 (altura-jogador-guerra outro))) menor)))
          (when (and toque (< toque menor)) (setf menor toque alvo outro)))))
    (when (guerra-invasao guerra)
      (dolist (monstro (invasao-guerra-monstros (guerra-invasao guerra)))
        (when (plusp (monstro-guerra-vida monstro))
          (let ((toque (segmento-caixa x y z dx dy dz
                         (criar-obstaculo :x (monstro-guerra-x monstro) :z (monstro-guerra-z monstro)
                                         :largura 1.4 :profundidade 1.4 :altura 2.2) menor)))
            (when (and toque (< toque menor)) (setf menor toque alvo monstro))))))
    (values alvo (list (+ x (* dx menor)) (+ y (* dy menor)) (+ z (* dz menor))))))

(defun iniciar-recarga-guerra (jogador)
  (when (and (jogador-ativo-p jogador) (<= (jogador-guerra-tempo-recarga jogador) 0)
             (< (jogador-guerra-municao jogador) (second (dados-arma-guerra jogador)))
             (plusp (jogador-guerra-reserva jogador)))
    (setf (jogador-guerra-tempo-recarga jogador) (fifth (dados-arma-guerra jogador))) t))

(defun ferir-jogador-guerra (guerra jogador &optional atacante)
  (setf (jogador-guerra-ferido-ate jogador) (+ (guerra-tempo guerra) .8))
  (cond ((or (eq (jogador-guerra-estado jogador) :incapacitado)
             (plusp (jogador-guerra-reanimacoes jogador)))
         (when (matar-jogador-guerra guerra jogador "Fogo ou contato inimigo")
           (when atacante (incf (jogador-guerra-eliminacoes atacante)))))
        ((>= (incf (jogador-guerra-ferimentos jogador)) 2) (incapacitar-jogador-guerra guerra jogador))))

(defun aplicar-supressao-guerra (jogador intensidade)
  "Acumula pressão de fogo; ela decai sozinha e nunca causa dano direto."
  (when (jogador-ativo-p jogador)
    (setf (jogador-guerra-supressao jogador)
          (min 1.0 (+ (jogador-guerra-supressao jogador) intensidade)))))

(defun distancia-linha-guerra (px pz ox oz dx dz alcance)
  "Distância horizontal de um ponto ao raio do disparo, limitada ao alcance."
  (let ((projecao (+ (* (- px ox) dx) (* (- pz oz) dz))))
    (when (and (>= projecao 0.0) (<= projecao alcance))
      (sqrt (max 0.0 (- (+ (expt (- px ox) 2) (expt (- pz oz) 2))
                         (expt projecao 2)))))))

(defun disparar-guerra (guerra jogador &optional alvo)
  ;; ALVO orienta os bots; os impactos passam sempre pelo mesmo raio da arma.
  (when (and alvo (jogador-guerra-bot-p jogador))
    (setf (jogador-guerra-angulo jogador) (angulo-entre-guerra jogador alvo)))
  (when (and (guerra-ativa-p guerra) (not (guerra-pausada guerra)) (jogador-ativo-p jogador)
             (plusp (jogador-guerra-municao jogador)) (<= (jogador-guerra-tempo-arma jogador) 0)
             (<= (jogador-guerra-tempo-recarga jogador) 0) (not (jogador-guerra-correndo jogador)))
    (decf (jogador-guerra-municao jogador))
    (setf (jogador-guerra-tempo-arma jogador) (fourth (dados-arma-guerra jogador))
          (jogador-guerra-recuo jogador) 1.0 (jogador-guerra-clarão jogador) .065)
    (registrar-ruido-guerra guerra (jogador-guerra-x jogador) (jogador-guerra-z jogador) 80.0 :tiro)
    (push (list :fuzil (jogador-guerra-x jogador) (jogador-guerra-z jogador)) (guerra-audio guerra))
    (multiple-value-bind (atingido destino) (alvo-na-mira-guerra guerra jogador)
      (push (list .12 (list (jogador-guerra-x jogador) (altura-jogador-guerra jogador) (jogador-guerra-z jogador)) destino)
            (guerra-efeitos guerra))
      ;; Rajadas próximas impõem pressão mesmo quando o raio não atravessa o
      ;; corpo. Isso cria a janela de supressão típica de um combate de linha.
      (let* ((dados (dados-arma-guerra jogador)) (alcance (sixth dados))
             (angulo (jogador-guerra-angulo jogador))
             (dx (sin angulo)) (dz (- (cos angulo))))
        (dolist (outro (guerra-jogadores guerra))
          (when (and (jogador-ativo-p outro)
                     (not (eq (jogador-guerra-exercito outro) (jogador-guerra-exercito jogador)))
                     (<= (or (distancia-linha-guerra (jogador-guerra-x outro) (jogador-guerra-z outro)
                                                      (jogador-guerra-x jogador) (jogador-guerra-z jogador)
                                                      dx dz alcance)
                             most-positive-single-float)
                         2.2))
            (aplicar-supressao-guerra outro .18))))
      (typecase atingido
        (jogador-guerra (ferir-jogador-guerra guerra atingido jogador))
        (monstro-guerra (decf (monstro-guerra-vida atingido) 55))))
    (unless (jogador-guerra-bot-p jogador)
      (incf (jogador-guerra-inclinacao jogador) (if (jogador-guerra-mirando jogador) .018 .04)))
    t))

(defun atualizar-armas-guerra (guerra intervalo)
  (dolist (jogador (guerra-jogadores guerra))
    (setf (jogador-guerra-tempo-arma jogador) (max 0.0 (- (jogador-guerra-tempo-arma jogador) intervalo))
          (jogador-guerra-clarão jogador) (max 0.0 (- (jogador-guerra-clarão jogador) intervalo))
          (jogador-guerra-recuo jogador) (max 0.0 (- (jogador-guerra-recuo jogador) (* intervalo 5)))
          (jogador-guerra-supressao jogador) (max 0.0 (- (jogador-guerra-supressao jogador) (* intervalo .16))))
    (when (plusp (jogador-guerra-tempo-recarga jogador))
      (setf (jogador-guerra-tempo-recarga jogador) (max 0.0 (- (jogador-guerra-tempo-recarga jogador) intervalo)))
      (when (zerop (jogador-guerra-tempo-recarga jogador))
        (let ((quantidade (min (jogador-guerra-reserva jogador)
                               (- (second (dados-arma-guerra jogador)) (jogador-guerra-municao jogador)))))
          (incf (jogador-guerra-municao jogador) quantidade) (decf (jogador-guerra-reserva jogador) quantidade)))))
  (dolist (efeito (guerra-efeitos guerra)) (decf (first efeito) intervalo))
  (setf (guerra-efeitos guerra) (delete-if (lambda (efeito) (<= (first efeito) 0)) (guerra-efeitos guerra))))

(defun celula-guerra (x z) (cons (round x 2) (round z 2)))
(defun celula-livre-guerra-p (celula)
  (multiple-value-bind (valor presente) (gethash celula *celulas-livres-guerra*)
    (if presente valor
        (setf (gethash celula *celulas-livres-guerra*)
              (not (colisao-guerra-p (* 2 (car celula)) (* 2 (cdr celula)) .6))))))


(defun caminho-guerra (x z destino-x destino-z)
  "Busca A* com fila de prioridade; retorna aproximação se a chegada estiver ocupada."
  (let* ((inicio (celula-guerra x z)) (destino (celula-guerra destino-x destino-z))
         (fila (make-array 64 :adjustable t :fill-pointer 0))
         (custos (make-hash-table :test #'equal)) (pais (make-hash-table :test #'equal))
         (fechados (make-hash-table :test #'equal)) (melhor inicio))
    (labels ((estimativa (c) (+ (abs (- (car c) (car destino))) (abs (- (cdr c) (cdr destino)))))
             (inserir (c custo)
               (let ((indice (length fila)) (valor (list (+ custo (* 1.2 (estimativa c))) c)))
                 (vector-push-extend valor fila)
                 (loop while (> indice 0) for pai = (floor (1- indice) 2)
                       while (< (first valor) (first (aref fila pai)))
                       do (setf (aref fila indice) (aref fila pai) indice pai))
                 (setf (aref fila indice) valor)))
             (retirar ()
               (let ((topo (second (aref fila 0))) (ultimo (vector-pop fila)) (indice 0))
                 (when (plusp (length fila))
                   (loop for filho = (1+ (* indice 2)) while (< filho (length fila))
                         do (when (and (< (1+ filho) (length fila))
                                       (< (first (aref fila (1+ filho))) (first (aref fila filho)))) (incf filho))
                            (when (<= (first ultimo) (first (aref fila filho))) (return))
                            (setf (aref fila indice) (aref fila filho) indice filho))
                   (setf (aref fila indice) ultimo)) topo))
             (reconstruir (c)
               (let ((rota nil)) (loop until (equal c inicio) do (push c rota) (setf c (gethash c pais))) rota)))
      (setf (gethash inicio custos) 0) (inserir inicio 0)
      (loop repeat 4096 while (plusp (length fila)) for atual = (retirar)
            unless (gethash atual fechados)
            do (when (< (estimativa atual) (estimativa melhor)) (setf melhor atual))
               (when (<= (estimativa atual) 1) (return-from caminho-guerra (reconstruir atual)))
               (setf (gethash atual fechados) t)
               (dolist (delta '((1 . 0) (-1 . 0) (0 . 1) (0 . -1)))
                 (let* ((novo (cons (+ (car atual) (car delta)) (+ (cdr atual) (cdr delta))))
                        (custo (1+ (gethash atual custos))))
                   (when (and (not (gethash novo fechados)) (celula-livre-guerra-p novo)
                              (< custo (gethash novo custos most-positive-fixnum)))
                     (setf (gethash novo custos) custo (gethash novo pais) atual)
                     (inserir novo custo)))))
      (reconstruir melhor))))

(defun objetivo-guerra (guerra jogador)
  (find-if (lambda (setor) (not (eq (setor-guerra-dono setor) (exercito-id (jogador-guerra-exercito jogador)))))
           (if (eq (exercito-id (jogador-guerra-exercito jogador)) :aurora)
               (guerra-setores guerra) (reverse (guerra-setores guerra)))))



(defun avancar-bot-guerra (guerra jogador x z intervalo)
  (when (or (null (jogador-guerra-destino jogador))
            (> (distancia x z (car (jogador-guerra-destino jogador)) (cdr (jogador-guerra-destino jogador))) 8))
    (setf (jogador-guerra-destino jogador) (cons x z)
          (jogador-guerra-caminho jogador) (caminho-guerra (jogador-guerra-x jogador) (jogador-guerra-z jogador) x z)))
  (let ((celula (first (jogador-guerra-caminho jogador))))
    (when celula
      (let* ((dx (- (* 2 (car celula)) (jogador-guerra-x jogador)))
             (dz (- (* 2 (cdr celula)) (jogador-guerra-z jogador))) (dist (sqrt (+ (* dx dx) (* dz dz)))))
        (setf (jogador-guerra-angulo jogador) (atan dx (- dz)))
        (if (< dist .25) (pop (jogador-guerra-caminho jogador))
            (unless (mover-jogador-guerra guerra jogador (* (/ dx dist) (min dist (* intervalo 3.2)))
                                                        (* (/ dz dist) (min dist (* intervalo 3.2))))
              (setf (jogador-guerra-destino jogador) nil)))))))

(defun atualizar-bots-guerra (guerra intervalo)
  (dolist (jogador (guerra-jogadores guerra))
    (when (and (jogador-guerra-bot-p jogador) (jogador-ativo-p jogador))
      (when (>= (guerra-tempo guerra) (jogador-guerra-pensar-em jogador))
        (let ((alvo (alvo-mais-proximo-guerra guerra jogador 90.0)))
          (setf (jogador-guerra-alvo-id jogador) (and alvo (jogador-guerra-id alvo))
                (jogador-guerra-pensar-em jogador) (+ (guerra-tempo guerra) .4))))
      (let* ((alvo (and (jogador-guerra-alvo-id jogador)
                        (localizar-jogador-guerra guerra (jogador-guerra-alvo-id jogador))))
             (setor (objetivo-guerra guerra jogador))
             (ferido (when (eq (jogador-guerra-funcao jogador) :medico)
                       (find-if (lambda (outro) (and (eq (jogador-guerra-estado outro) :incapacitado)
                           (eq (jogador-guerra-exercito outro) (jogador-guerra-exercito jogador))
                           (< (distancia-guerra jogador outro) 30))) (guerra-jogadores guerra)))))
        (cond
          (ferido (if (< (distancia-guerra jogador ferido) 3)
                      (progn (estabilizar-jogador-guerra guerra jogador ferido) (reanimar-jogador-guerra guerra jogador ferido))
                      (avancar-bot-guerra guerra jogador (jogador-guerra-x ferido) (jogador-guerra-z ferido) intervalo)))
          (alvo
           (let ((distancia-alvo (distancia-guerra jogador alvo)))
             (setf (jogador-guerra-angulo jogador) (+ (angulo-entre-guerra jogador alvo)
                         (* (+ .006 (* .025 (jogador-guerra-supressao jogador)))
                            (sin (+ (guerra-quadro guerra) (jogador-guerra-id jogador)))))
                   (jogador-guerra-inclinacao jogador) (atan (- 1.2 (altura-jogador-guerra jogador)) (max 1 distancia-alvo)))
             ;; A infantaria só abre fogo em alcance de combate; até lá,
             ;; aproxima-se e preserva a leitura tática da frente.
             (if (and (< distancia-alvo 70.0) (< (jogador-guerra-supressao jogador) .85))
                 (if (plusp (jogador-guerra-municao jogador))
                     (when (disparar-guerra guerra jogador)
                       (setf (jogador-guerra-tempo-arma jogador) (max 1.0 (jogador-guerra-tempo-arma jogador))))
                     (iniciar-recarga-guerra jogador))
                 (avancar-bot-guerra guerra jogador (jogador-guerra-x alvo)
                                     (jogador-guerra-z alvo) intervalo)))
           ;; O contato não congela a linha: soldados fora do alcance curto
           ;; avançam em direção ao setor designado enquanto atiram.
           (when (and setor (> (sqrt (+ (expt (- (jogador-guerra-x jogador)
                                                   (setor-guerra-x setor)) 2)
                                          (expt (- (jogador-guerra-z jogador)
                                                   (setor-guerra-z setor)) 2))) 24))
             (avancar-bot-guerra guerra jogador (setor-guerra-x setor)
                                 (setor-guerra-z setor) intervalo)))
          (setor
           (let* ((ordem (esquadrao-guerra-ordem (jogador-guerra-esquadrao jogador)))
                  (local (jogador-local-guerra guerra))
                  (reunir (and (eq ordem :reunir) (eq (jogador-guerra-exercito jogador) (jogador-guerra-exercito local))))
                  (x (if reunir (+ (jogador-guerra-x local) (* 2 (mod (jogador-guerra-id jogador) 4)))
                         (+ 10 (* 4 (mod (jogador-guerra-id jogador) 4)))))
                  (z (if reunir (+ (jogador-guerra-z local) 4) (setor-guerra-z setor))))
             (when (> (distancia (jogador-guerra-x jogador) (jogador-guerra-z jogador) x z) 3)
               (avancar-bot-guerra guerra jogador x z intervalo))))
          (t (let* ((adversario (find-if (lambda (e) (not (eq e (jogador-guerra-exercito jogador)))) (guerra-exercitos guerra)))
                    (qg (exercito-quartel-general adversario)))
               (avancar-bot-guerra guerra jogador 24.0 (* .91 (quartel-general-z qg)) intervalo))))))))

(defun atualizar-setores-guerra (guerra intervalo)
  (dolist (setor (guerra-setores guerra))
    (let* ((a (jogadores-no-setor guerra setor (localizar-exercito-guerra guerra :aurora)))
           (b (jogadores-no-setor guerra setor (localizar-exercito-guerra guerra :bruma)))
           (diferenca (- a b)) (lado (if (plusp diferenca) :aurora :bruma)))
      (setf (setor-guerra-contestacao setor) (float diferenca))
      (unless (or (zerop diferenca) (eq (setor-guerra-dono setor) lado))
        (incf (setor-guerra-progresso setor) (* intervalo .045 (max -3 (min 3 diferenca)))))
      (when (>= (abs (setor-guerra-progresso setor)) 1)
        (setf (setor-guerra-dono setor) (if (plusp (setor-guerra-progresso setor)) :aurora :bruma)
              (setor-guerra-progresso setor) 0.0)
        (emitir-mensagem-guerra guerra (localizar-exercito-guerra guerra (setor-guerra-dono setor))
                                (format nil "Setor capturado: ~A" (setor-guerra-nome setor)) :comando)))))

(defun atualizar-assalto-qg-guerra (guerra intervalo)
  (dolist (exercito (guerra-exercitos guerra))
    (when (frente-controlada-p guerra exercito)
      (let* ((adversario (find-if (lambda (outro) (not (eq outro exercito))) (guerra-exercitos guerra)))
             (qg (exercito-quartel-general adversario))
             (presentes (count-if (lambda (j) (and (jogador-ativo-p j) (eq (jogador-guerra-exercito j) exercito)
                                (< (distancia (jogador-guerra-x j) (jogador-guerra-z j) 0 (quartel-general-z qg)) 65)))
                                 (guerra-jogadores guerra))))
        (when (plusp presentes)
          (decf (quartel-general-vida qg) (* intervalo presentes 8))
          (when (<= (quartel-general-vida qg) 0) (aplicar-dano-qg guerra adversario 0 "Assalto da infantaria")))))))

(defun atualizar-reforcos-guerra (guerra intervalo)
  (declare (ignore intervalo))
  (dolist (exercito (guerra-exercitos guerra))
    (dolist (jogador (copy-list (exercito-fila-reforcos exercito)))
      (when (>= (guerra-tempo guerra) (jogador-guerra-retorno-em jogador))
        (incf (jogador-guerra-geracao jogador))
        (equipar-guerra jogador)
        (setf (jogador-guerra-estado jogador) :ativo
              (jogador-guerra-x jogador) -6.0
              (jogador-guerra-z jogador) (if (eq (exercito-id exercito) :aurora) -55.0 55.0)
              (jogador-guerra-angulo jogador) (if (eq (exercito-id exercito) :aurora) pi 0.0)
              (exercito-fila-reforcos exercito) (remove jogador (exercito-fila-reforcos exercito)))))))

(defun atualizar-combate-local-guerra (guerra intervalo)
  (let* ((j (jogador-local-guerra guerra)) (frente (jogador-guerra-frente j)) (lado (jogador-guerra-lateral j))
         (normal (max 1.0 (sqrt (+ (* frente frente) (* lado lado)))))
         (angulo (jogador-guerra-angulo j))
         (velocidade (cond ((jogador-guerra-agachado j) 1.5) ((jogador-guerra-mirando j) 1.8)
                          ((jogador-guerra-correndo j) 5.0) (t 3.2))))
    (when (jogador-ativo-p j)
      (mover-jogador-guerra guerra j (* intervalo velocidade (/ (+ (* frente (sin angulo)) (* lado (cos angulo))) normal))
                                       (* intervalo velocidade (/ (+ (* (- frente) (cos angulo)) (* lado (sin angulo))) normal)))
      (when (and (> (jogador-guerra-movimento j) 0) (zerop (mod (guerra-quadro guerra) 30)))
        (registrar-ruido-guerra guerra (jogador-guerra-x j) (jogador-guerra-z j) 8 :passos))
      (when (jogador-guerra-gatilho j) (disparar-guerra guerra j)))))

(defun interagir-guerra (guerra jogador)
  (cond
    ((eq (jogador-guerra-estado jogador) :incapacitado) (matar-jogador-guerra guerra jogador "Evacuação impossível"))
    ((and (jogador-ativo-p jogador)
          (some (lambda (z) (< (distancia (jogador-guerra-x jogador) (jogador-guerra-z jogador) -10 z) 4)) '(-55 55)))
     (setf (jogador-guerra-reserva jogador) (third (dados-arma-guerra jogador)))
     (push (list :recarga (jogador-guerra-x jogador) (jogador-guerra-z jogador)) (guerra-audio guerra)) t)))
