(in-package #:rimefall)

(defun botao (identificador titulo x y largura &key selecionado (habilitado t) (altura 48))
  (let ((focado (eq identificador *foco*)))
    (retangulo x y largura altura
               (cond ((not habilitado) '(.065 .085 .098 .92))
                     (selecionado '(.16 .21 .22 1)) (focado '(.13 .17 .18 1))
                     (t '(.075 .11 .13 1))))
    (when (or selecionado focado)
      (retangulo x y (if selecionado 4 2) altura *destaque*))
    (desenhar-texto titulo (+ x 18) (+ y (/ (- altura 14) 2)) 2 (if habilitado *gelo* *apagado*))
    (push (list identificador x y largura altura habilitado) *botoes*)))

(defun cabecalho (sessao subtitulo)
  (retangulo 0 0 1280 720 '(.025 .043 .055 .86))
  (retangulo 48 40 5 17 *destaque*)
  (desenhar-texto "POSTO 07 / CÍRCULO POLAR" 68 44 2 *apagado*)
  (desenhar-texto "RIMEFALL" 48 86 7 *gelo*)
  (desenhar-texto subtitulo 48 155 2 *destaque*)
  (desenhar-texto (format nil "~2,'0D / 04" (sessao-usados sessao)) 1080 82 3 *gelo*)
  (desenhar-texto "SOLDADOS USADOS" 1040 118 2 *apagado*)
  (retangulo 48 184 1184 1 '(.25 .32 .34 1))
  (desenhar-texto "TAB: NAVEGAR   ENTER: CONFIRMAR   H: HISTÓRICO   ESC: SAIR/VOLTAR" 48 681 1.5 *apagado*))

(defun desenhar-notas (sessao)
  (cabecalho sessao "01 / NOTAS DE CAMPO")
  (let* ((notas (sessao-notas sessao)) (acervo (sessao-acervo sessao))
         (identidade (nth (min 3 (sessao-usados sessao)) *identidades*)))
    (desenhar-texto (first identidade) 48 208 2 *destaque*)
    (desenhar-texto (second identidade) 48 238 1.4 *apagado*)
    (desenhar-texto "ARMAMENTO / UMA ARMA" 48 277 1.7 *destaque*)
    (loop for chave in '(:fuzil :escopeta :carabina :submetralhadora :precisao :franco-atirador) for y from 310 by 33
          for conhecimento = (procurar-conhecimento chave)
          do (botao chave (conhecimento-titulo conhecimento) 48 y 318
                    :habilitado (gethash chave acervo) :selecionado (eq chave (notas-arma notas)) :altura 29))
    (botao :mapa "MAPA EXPLORADO E MARCAS" 48 515 318)
    (paragrafo "O terreno conhecido é transmitido na morte. Marcas são anotações suas." 58 580 33 *apagado* 1.4 3)
    (desenhar-texto "PREPARO / ESCOLHA ATÉ UM" 398 277 1.7 *destaque*)
    (loop for chave in '(:nenhum :silencio :distracao :temporizador :bipé) for y from 310 by 51
          do (botao chave (if (eq chave :nenhum) "Equipamento básico"
                             (conhecimento-titulo (procurar-conhecimento chave)))
                    398 y 368 :altura 43
                    :habilitado (or (eq chave :nenhum) (gethash chave acervo))
                    :selecionado (if (eq chave :nenhum) (null (notas-preparo notas))
                                     (eq chave (notas-preparo notas)))))
    (let ((conhecimento (procurar-conhecimento (or (and (procurar-conhecimento *foco*) *foco*)
                                                  (notas-preparo notas)))))
      (if conhecimento
        (paragrafo (if (gethash (conhecimento-identificador conhecimento) acervo)
                       (conhecimento-descricao conhecimento) (conhecimento-criterio conhecimento))
                    402 577 40 *apagado* 1.4 3)
        (paragrafo "Duas pedras básicas. Agache para reduzir os passos. Selecione uma descoberta para ler o critério." 402 577 40 *apagado* 1.4 3)))
    (retangulo 800 272 432 315 *painel*)
    (desenhar-texto "DIÁRIO / SEM EFEITO MECÂNICO" 816 290 1.7 *destaque*)
    (botao :diario (if *edicao-diario* "ESCREVENDO / ESC CONCLUI" "EDITAR DIÁRIO") 814 322 404 :altura 40)
    (let ((linhas (linhas-texto (notas-texto notas) 43)))
      (setf *linha-diario* (limitar *linha-diario* 0 (max 0 (- (length linhas) 8))))
      (loop for linha in (nthcdr *linha-diario* linhas) for indice below 8
            do (desenhar-texto linha 816 (+ 385 (* indice 22)) 1.5 *gelo*)))
    (desenhar-texto (format nil "~D / 600   RODA: ROLAR" (length (notas-texto notas))) 816 566 1.3 *apagado*)
    (botao :entrar "ENTRAR EM CAMPO" 800 610 432 :habilitado (not *gravacao-bloqueada*))))

(defun desenhar-relatorio (sessao)
  (let* ((final (member (sessao-fase sessao) '(:vitoria :derrota)))
         (registro (first (sessao-historico sessao)))
         (evidencias (if (eq (sessao-fase sessao) :vitoria)
                         (reverse (soldado-aprendizados (sessao-soldado sessao)))
                         (getf registro :evidencias))))
    (cabecalho sessao (case (sessao-fase sessao)
                       (:vitoria "03 / O POSTO RESISTIU") (:derrota "03 / O ESQUADRÃO CAIU")
                       (t "02 / TRANSMISSÃO PÓSTUMA")))
    (desenhar-texto (case (sessao-fase sessao) (:vitoria "O SILÊNCIO VOLTOU.")
                                          (:derrota "NENHUM SUBSTITUTO.") (t "UM NOME A MENOS.")) 64 230 3 *gelo*)
    (paragrafo (if (eq (sessao-fase sessao) :vitoria)
                  "As três ondas foram eliminadas. Os que ficaram carregam a memória do esquadrão."
                  "O equipamento ficou no campo. O que foi aprendido agora pertence a todos.")
               64 285 63 *apagado* 1.8)
    (retangulo 48 353 1184 219 *painel*)
    (desenhar-texto (if (eq (sessao-fase sessao) :vitoria)
                        "APRENDIZADOS DO SOBREVIVENTE" "CONHECIMENTO TRANSMITIDO") 68 378 2 *destaque*)
    (if evidencias
        (loop for evidencia in evidencias for indice from 0
              do (desenhar-texto (conhecimento-titulo (procurar-conhecimento (evidencia-conhecimento evidencia)))
                                  68 (+ 402 (* indice 14)) 1.7 *gelo*)
                 (desenhar-texto (format nil "VIDA ~D / ~,1F S" (evidencia-soldado evidencia)
                                        (evidencia-instante evidencia)) 910 (+ 402 (* indice 14)) 1.5 *apagado*))
        (desenhar-texto "NENHUMA NOVA EVIDÊNCIA NESTA VIDA." 68 430 1.7 *apagado*))
    (desenhar-texto "H abre o histórico completo com as evidências." 68 549 1.4 *apagado*)
    (botao (if final :reiniciar :notas) (if final "INICIAR NOVA SESSÃO" "PREPARAR PRÓXIMO SOLDADO")
           820 607 412)
    (desenhar-texto (format nil "ONDA ~D / 3    TEMPO EM CAMPO ~D S" (sessao-onda sessao) (floor (sessao-tempo sessao)))
                     64 626 1.7 *apagado*)))

(defun desenhar-historico (sessao)
  (cabecalho sessao "ARQUIVO / MEMÓRIA DO ESQUADRÃO")
  (let* ((registros (reverse (sessao-historico sessao)))
         (quantidade (length registros))
         (registro (nth (min *pagina-historico* (max 0 (1- quantidade))) registros)))
    (desenhar-texto (format nil "VIDAS REGISTRADAS: ~D" quantidade) 64 225 2 *destaque*)
    (if registro
        (if *diario-historico*
            (progn
              (desenhar-texto "DIÁRIO COMPLETO DESTA VIDA" 64 280 2 *destaque*)
              (paragrafo (getf registro :diario) 64 326 105 *gelo* 1.5 13))
        (progn
          (desenhar-texto (format nil "~A / ~D ELIMINAÇÕES / ONDA ~D" (getf registro :nome)
                                  (getf registro :eliminacoes) (getf registro :onda)) 64 269 2 *gelo*)
          (desenhar-texto (getf registro :causa) 64 299 1.3 *apagado*)
          (loop for evidencia in (nthcdr (* 5 *pagina-evidencias*) (getf registro :evidencias)) for indice below 5
                do (desenhar-texto (conhecimento-titulo (procurar-conhecimento (evidencia-conhecimento evidencia)))
                                   64 (+ 320 (* indice 43)) 1.7 *destaque*)
                   (paragrafo (evidencia-descricao evidencia) 64 (+ 341 (* indice 43)) 120 *gelo* 1.3 1))
          (botao :evidencias-anteriores "EVIDÊNCIAS -" 64 549 230 :altura 29 :habilitado (> *pagina-evidencias* 0))
          (botao :evidencias-proximas "EVIDÊNCIAS +" 315 549 230 :altura 29
                 :habilitado (< (* 5 (1+ *pagina-evidencias*)) (length (getf registro :evidencias))))
          (desenhar-texto (getf registro :origem) 64 585 1.4 *apagado*)
          ))
        (paragrafo "Nenhum soldado morreu. Novas descobertas entram no acervo coletivo somente após a morte."
                   64 285 72 *gelo* 2))
    (botao :anterior "ANTERIOR" 48 623 205 :habilitado (> *pagina-historico* 0))
    (botao :proxima "PRÓXIMA" 272 623 205 :habilitado (< *pagina-historico* (1- quantidade)))
    (botao :diario-historico (if *diario-historico* "VER EVIDÊNCIAS" "LER DIÁRIO COMPLETO")
           496 623 360 :habilitado registro)
    (botao :fechar-historico "VOLTAR" 1010 623 222)))

(defun nome-tecla (tecla)
  (case tecla (340 "SHIFT") (341 "CTRL") (32 "ESPAÇO") (t (if (<= 33 tecla 126) (string (code-char tecla)) (format nil "TECLA ~D" tecla)))))
(defun titulo-acao (acao)
  (cdr (assoc acao '((:frente . "Avançar") (:tras . "Recuar") (:esquerda . "Esquerda") (:direita . "Direita")
                    (:correr . "Correr") (:agachar . "Agachar") (:recarregar . "Recarregar")
                    (:recolher . "Interagir") (:isca . "Lançar pedra") (:dispositivo . "Isca temporizada") (:apoiar . "Apoiar arma")))))
(defun desenhar-pausa (sessao)
  (cabecalho sessao "PAUSA / O CERCO ESTÁ SUSPENSO")
  (desenhar-texto "MOVA-SE COM INTENÇÃO." 64 225 3 *gelo*)
  (loop for par in (getf *configuracao* :atalhos) for indice from 0
        do (desenhar-texto (format nil "~A / ~A" (nome-tecla (cdr par)) (titulo-acao (car par)))
                           (+ 64 (* (floor indice 6) 580)) (+ 300 (* (mod indice 6) 36)) 2 *apagado*))
  (desenhar-texto "MOUSE / OLHAR    DIREITO / MIRAR    ESQUERDO / DISPARAR" 64 549 1.7 *gelo*)
  (botao :retomar "RETOMAR CERCO" 840 617 392)
  (botao :configuracoes "CONFIGURAÇÕES" 440 617 360)
  (botao :sair "SALVAR E SAIR" 48 617 350))

(defun desenhar-indicadores (sessao)
  (let ((soldado (sessao-soldado sessao)))
    (when (plusp (soldado-ferimentos soldado))
      (retangulo 0 0 1280 24 '(.35 .055 .04 .30))
      (retangulo 0 0 24 720 '(.35 .055 .04 .30))
      (retangulo 1256 0 24 720 '(.35 .055 .04 .30))
      (retangulo 0 696 1280 24 '(.35 .055 .04 .30)))
    (retangulo 32 629 325 65 '(.025 .04 .05 .80))
    (desenhar-texto (conhecimento-titulo (procurar-conhecimento (soldado-arma soldado))) 48 643 1.5 *apagado*)
    (desenhar-texto (format nil "~D / ~2,'0D" (soldado-carregador soldado) (reserva-arma soldado)) 48 668 2.4 *gelo*)
    (desenhar-texto (format nil "ISCAS ~D" (soldado-iscas soldado)) 229 670 1.7 *apagado*)
    (desenhar-texto (if (plusp (soldado-ferimentos soldado)) "FERIDO / SEM REGENERAÇÃO" "POSTO 07 / EM CAMPO")
                     903 672 1.6 (if (plusp (soldado-ferimentos soldado)) *destaque* *apagado*))
    (when (soldado-apoiado soldado) (desenhar-texto "ARMA APOIADA" 48 594 1.4 *destaque*))
    (when (soldado-equipamento soldado)
      (desenhar-texto (conhecimento-titulo (procurar-conhecimento (soldado-equipamento soldado))) 48 568 1.3 *apagado*))
    (when (plusp (soldado-recarga soldado))
      (desenhar-texto "RECARREGANDO" 554 593 1.8 *gelo*))
    (when (or (suprimento-proximo sessao) (porta-proxima sessao) (dispositivo-proximo sessao))
      (retangulo 405 544 470 34 '(.025 .04 .05 .85))
      (desenhar-texto (format nil "~A / ~A" (nome-tecla (cdr (assoc :recolher (getf *configuracao* :atalhos))))
                        (cond ((porta-proxima sessao) "ABRIR OU FECHAR PORTÃO")
                              ((dispositivo-proximo sessao) "RECUPERAR DISPOSITIVO") (t "RECOLHER OU TROCAR EQUIPAMENTO"))) 419 555 1.8 *gelo*))
    (when (< (sessao-tempo sessao) (sessao-mensagem-ate sessao))
      (let ((texto (sessao-mensagem sessao)))
        (retangulo 240 46 800 42 '(.025 .04 .05 .78))
        (desenhar-texto texto (- 640 (* (length texto) 4.5)) 61 1.5 *gelo*)))
    (when (< (sessao-tempo sessao) 14.0)
      (retangulo 38 25 535 29 '(.025 .04 .05 .80))
      (desenhar-texto "ESC: CONTROLES   /   ELES CAÇAM PELO SOM." 48 38 1.3 *apagado*))))

(defun ativar-botao (sessao identificador janela)
  (case identificador
    ((:fuzil :escopeta :carabina :submetralhadora :precisao :franco-atirador) (when (gethash identificador (sessao-acervo sessao))
                         (setf (notas-arma (sessao-notas sessao)) identificador)))
    ((:silencio :distracao :temporizador :bipé) (when (gethash identificador (sessao-acervo sessao))
                             (setf (notas-preparo (sessao-notas sessao)) identificador)))
    (:nenhum (setf (notas-preparo (sessao-notas sessao)) nil))
    (:diario (setf *edicao-diario* t))
    (:diario-historico (setf *diario-historico* (not *diario-historico*)))
    (:entrar (setf *edicao-diario* nil) (confirmar-notas sessao))
    (:notas (abrir-notas sessao) (setf *foco* :entrar))
    ((:nova :reiniciar) (setf *gravacao-bloqueada* nil *erro-persistencia* nil *mapa-aberto* nil)
     (setf *foco* :entrar *historico-aberto* nil *edicao-diario* nil) (let ((nova (nova-sessao))) (salvar-transicao nova) (return-from ativar-botao nova)))
    (:tentar-salvar
     (setf *gravacao-bloqueada* nil)
     (salvar-transicao sessao))
    (:retomar (unless *gravacao-bloqueada* (setf (sessao-fase sessao) :combate)))
    (:continuar (let ((salva (carregar-sessao))) (when salva (return-from ativar-botao salva))))
    (:configuracoes (setf *configuracoes-abertas* t *foco* :voltar-configuracoes))
    (:voltar-configuracoes (salvar-configuracao) (setf *configuracoes-abertas* nil *remapeando* nil))
    (:mapa (setf *mapa-aberto* t *foco* :fechar-mapa))
    (:fechar-mapa (setf *mapa-aberto* nil *editando-marca* nil))
    (:editar-marca (setf *editando-marca* t))
    (:guardar-marca (when (adicionar-marca sessao (car *celula-mapa*) (cdr *celula-mapa*) *texto-marca*)
                      (setf *editando-marca* nil) (salvar-transicao sessao)))
    (:apagar-marca (adicionar-marca sessao (car *celula-mapa*) (cdr *celula-mapa*) "")
                   (setf *texto-marca* "") (salvar-transicao sessao))
    (:sair (janela:set-window-should-close janela t))
    (:evidencias-anteriores (setf *pagina-evidencias* (max 0 (1- *pagina-evidencias*))))
    (:evidencias-proximas (incf *pagina-evidencias*))
    (:anterior (setf *pagina-evidencias* 0 *pagina-historico* (max 0 (1- *pagina-historico*))))
    (:proxima (setf *pagina-evidencias* 0 *pagina-historico* (min (1- (length (sessao-historico sessao))) (1+ *pagina-historico*))))
    (:fechar-historico (setf *historico-aberto* nil))
    (t (ativar-configuracao identificador janela)))
  sessao)

(defun processar-interface (sessao estado janela)
  (when (entrada:key-pressed-p estado janela:key-escape)
    (cond (*remapeando* (setf *remapeando* nil))
          (*editando-marca* (setf *editando-marca* nil))
          (*configuracoes-abertas* (salvar-configuracao) (setf *configuracoes-abertas* nil))
          (*mapa-aberto* (setf *mapa-aberto* nil))
          (*edicao-diario* (setf *edicao-diario* nil))
          (*historico-aberto* (setf *historico-aberto* nil))
          ((eq (sessao-fase sessao) :pausa) (unless *gravacao-bloqueada* (setf (sessao-fase sessao) :combate)))
          ((eq (sessao-fase sessao) :combate) (setf (sessao-fase sessao) :pausa *foco* :retomar))
          (t (janela:set-window-should-close janela t)))
    (return-from processar-interface sessao))
  (when (processar-edicoes sessao estado janela) (return-from processar-interface sessao))
  (when (and (eq (sessao-fase sessao) :combate) (not (entrada:input-focused-p estado)))
    (setf (sessao-fase sessao) :pausa *foco* :retomar))
  (when (eq (sessao-fase sessao) :combate)
    (let ((soldado (sessao-soldado sessao)))
      (setf (soldado-agachado soldado) (acao-mantida-p estado :agachar)
            (soldado-mirando soldado) (entrada:mouse-down-p estado janela:mouse-button-right)
            (soldado-correndo soldado) (and (acao-mantida-p estado :correr)
                                            (not (soldado-mirando soldado)) (not (soldado-agachado soldado))))
      (multiple-value-bind (dx dy) (entrada:mouse-delta estado)
        (incf (soldado-angulo soldado) (* (getf *configuracao* :sensibilidade) dx))
        (setf (soldado-inclinacao soldado) (limitar (- (soldado-inclinacao soldado) (* (getf *configuracao* :sensibilidade) dy)) -1.3 1.3)))
      (when (entrada:mouse-pressed-p estado janela:mouse-button-left) (disparar sessao))
      (when (acao-pressionada-p estado :recolher) (recolher sessao))
      (when (acao-pressionada-p estado :recarregar) (iniciar-recarga sessao))
      (when (acao-pressionada-p estado :isca) (lancar-isca sessao))
      (when (acao-pressionada-p estado :dispositivo) (colocar-dispositivo sessao))
      (when (acao-pressionada-p estado :apoiar) (apoiar-arma sessao)))
    (return-from processar-interface sessao))
  (when (eq (sessao-fase sessao) :notas)
    (multiple-value-bind (horizontal vertical) (entrada:scroll-delta estado)
      (declare (ignore horizontal))
      (decf *linha-diario* (round (* vertical 3)))))
  (when *edicao-diario*
    (let* ((notas (sessao-notas sessao))
           (digitado (if (and (entrada:key-down-p estado janela:key-left-control)
                              (entrada:key-pressed-p estado janela:key-v))
                         (or (janela:clipboard-string janela) "")
                         (entrada:consume-text-input estado)))
           (texto (concatenate 'string (notas-texto notas) digitado)))
      (when (and (entrada:key-pressed-p estado janela:key-backspace) (plusp (length texto)))
        (setf texto (subseq texto 0 (1- (length texto)))))
      (when (entrada:key-pressed-p estado janela:key-enter) (setf texto (concatenate 'string texto (string #\Newline))))
      (setf (notas-texto notas) (subseq texto 0 (min 600 (length texto))))
      (when (or (plusp (length digitado)) (entrada:key-pressed-p estado janela:key-enter))
        (setf *linha-diario* (max 0 (- (length (linhas-texto (notas-texto notas) 39)) 9)))))
    (unless (entrada:mouse-pressed-p estado janela:mouse-button-left)
      (return-from processar-interface sessao)))
  (when (and (not *configuracoes-abertas*) (not *mapa-aberto*) (not (eq (sessao-fase sessao) :titulo))
             (entrada:key-pressed-p estado janela:key-h))
    (setf *historico-aberto* (not *historico-aberto*) *pagina-historico* 0 *pagina-evidencias* 0 *foco* :fechar-historico))
  (unless *edicao-diario*
    (multiple-value-bind (dx dy) (entrada:mouse-delta estado)
      (when (or (not (zerop dx)) (not (zerop dy)))
        (multiple-value-bind (x y) (entrada:mouse-position estado)
          (multiple-value-bind (largura altura) (janela:window-size janela)
            (setf x (* x (/ 1280 (max largura 1))) y (* y (/ 720 (max altura 1)))))
          (dolist (botao *botoes*)
            (destructuring-bind (identificador bx by largura altura habilitado) botao
              (declare (ignore habilitado))
              (when (and (<= bx x (+ bx largura)) (<= by y (+ by altura))) (setf *foco* identificador))))))))
  (when (entrada:key-pressed-p estado janela:key-tab)
    (let* ((opcoes (mapcar #'first (reverse *botoes*)))
           (indice (position *foco* opcoes)))
      (when opcoes (setf *foco* (nth (mod (1+ (or indice -1)) (length opcoes)) opcoes)))))
  (when (entrada:mouse-pressed-p estado janela:mouse-button-left)
    (multiple-value-bind (x y) (entrada:mouse-position estado)
      (multiple-value-bind (largura altura) (janela:window-size janela)
        (setf x (* x (/ 1280 (max largura 1))) y (* y (/ 720 (max altura 1)))))
      (dolist (botao *botoes*)
        (destructuring-bind (identificador bx by largura altura habilitado) botao
          (when (and habilitado (<= bx x (+ bx largura)) (<= by y (+ by altura)))
            (setf *foco* identificador *edicao-diario* nil)
            (return-from processar-interface (ativar-botao sessao identificador janela)))))))
  (when (entrada:key-pressed-p estado janela:key-enter)
    (when (find-if (lambda (botao) (and (eq (first botao) *foco*) (sixth botao))) *botoes*)
      (setf sessao (ativar-botao sessao *foco* janela))))
  sessao)


(defun acao-mantida-p (estado acao)
  (entrada:key-down-p estado (cdr (assoc acao (getf *configuracao* :atalhos)))))
(defun acao-pressionada-p (estado acao)
  (entrada:key-pressed-p estado (cdr (assoc acao (getf *configuracao* :atalhos)))))
(defun desenhar-titulo (sessao)
  (cabecalho sessao "DEMO / A MEMÓRIA SOBREVIVE AO FRIO")
  (paragrafo "Quatro soldados. Três ondas. Um posto congelado. As criaturas caçam pelo som. O que cada soldado descobre passa ao esquadrão quando ele morre."
             64 238 55 *gelo* 2 5)
  (desenhar-texto "POSTO DE TESTES / EXPANSÃO 0.2" 64 475 1.8 *destaque*)
  (paragrafo "Saia do abrigo para buscar equipamento experimental. Pare, ouça o vento e escolha quando arriscar um disparo." 64 524 57 *apagado* 1.7)
  (botao :continuar "CONTINUAR" 840 240 392 :habilitado (probe-file (caminho-sessao)))
  (botao :nova "NOVA SESSÃO" 840 318 392)
  (paragrafo "Nova sessão substitui o cerco salvo." 848 384 36 *apagado* 1.4 2)
  (botao :configuracoes "CONFIGURAÇÕES" 840 440 392)
  (botao :sair "SAIR" 840 520 392))

(defparameter *opcoes-configuracao*
  '((:sensibilidade "Sensibilidade" .0005 .008 .0005)
    (:visao "Campo de visão" 55 100 5)
    (:volume "Volume geral" 0.0 1.0 .1)
    (:efeitos "Efeitos" 0.0 1.0 .1)
    (:ambiente "Ambiente" 0.0 1.0 .1)))
(defun identificador-opcao (prefixo chave)
  (intern (concatenate 'string prefixo (symbol-name chave)) :keyword))
(defun desenhar-configuracoes (sessao)
  (cabecalho sessao "PREFERÊNCIAS / CONTROLES E APRESENTAÇÃO")
  (loop for (chave titulo) in *opcoes-configuracao* for y from 226 by 53
        do (desenhar-texto (format nil "~A: ~,3F" titulo (getf *configuracao* chave)) 64 (+ y 15) 1.6 *gelo*)
           (botao (identificador-opcao "MENOS-" chave) "-" 402 y 64 :altura 43)
           (botao (identificador-opcao "MAIS-" chave) "+" 478 y 64 :altura 43))
  (botao :resolucao (format nil "RESOLUÇÃO: ~D X ~D" (getf *configuracao* :largura) (getf *configuracao* :altura)) 64 497 478 :altura 43)
  (botao :tela-cheia (if (getf *configuracao* :tela-cheia) "TELA CHEIA / SIM" "TELA CHEIA / NÃO") 64 548 478 :altura 43)
  (desenhar-texto "TELA CHEIA APLICADA NA PRÓXIMA ABERTURA." 64 610 1.3 *apagado*)
  (loop for par in (getf *configuracao* :atalhos) for indice from 0
        do (botao (identificador-opcao "TECLA-" (car par))
                  (format nil "~A: ~A" (titulo-acao (car par))
                          (if (eq (car par) *remapeando*) "PRESSIONE UMA TECLA" (nome-tecla (cdr par))))
                  606 (+ 217 (* indice 33)) 626 :altura 29))
  (botao :sincronizar (if (getf *configuracao* :sincronizar) "VSYNC / SIM" "VSYNC / NÃO") 606 591 240 :altura 40)
  (botao :neve (format nil "NEVE: ~D" (getf *configuracao* :neve)) 866 591 366 :altura 40)
  (botao :voltar-configuracoes "SALVAR E VOLTAR" 840 644 392 :altura 30))
(defun ativar-configuracao (identificador janela)
  (dolist (opcao *opcoes-configuracao*)
    (destructuring-bind (chave titulo minimo maximo passo) opcao
      (declare (ignore titulo))
      (dolist (direcao '(-1 1))
        (when (eq identificador (identificador-opcao (if (= direcao -1) "MENOS-" "MAIS-") chave))
          (setf (getf *configuracao* chave) (limitar (+ (getf *configuracao* chave) (* direcao passo)) minimo maximo))))))
  (dolist (par *atalhos-padrao*)
    (when (eq identificador (identificador-opcao "TECLA-" (car par))) (setf *remapeando* (car par))))
  (case identificador
    (:resolucao
     (let* ((opcoes '((1280 720) (1600 900) (1920 1080)))
            (indice (position (list (getf *configuracao* :largura) (getf *configuracao* :altura)) opcoes :test #'equal))
            (nova (nth (mod (1+ (or indice 0)) 3) opcoes)))
       (setf (getf *configuracao* :largura) (first nova) (getf *configuracao* :altura) (second nova))
       (janela:set-window-size janela (first nova) (second nova))))
    (:tela-cheia (setf (getf *configuracao* :tela-cheia) (not (getf *configuracao* :tela-cheia))))
    (:sincronizar (setf (getf *configuracao* :sincronizar) (not (getf *configuracao* :sincronizar)))
                 (janela:swap-interval (if (getf *configuracao* :sincronizar) 1 0)))
    (:neve (setf (getf *configuracao* :neve) (mod (+ 85 (getf *configuracao* :neve)) 340)))))

(defun selecionar-celula (sessao coluna linha)
  (setf *celula-mapa* (cons (limitar coluna (- *meia-grade-mapa*) (1- *meia-grade-mapa*)) (limitar linha (- *meia-grade-mapa*) (1- *meia-grade-mapa*)))
        *texto-marca* (or (second (assoc *celula-mapa* (sessao-marcas sessao) :test #'equal)) "")
        *editando-marca* nil))
(defun desenhar-mapa (sessao)
  (cabecalho sessao "CARTOGRAFIA / APENAS MEMÓRIA TRANSMITIDA")
  (retangulo 62 213 452 452 *painel*)
  (loop for coluna from (- *meia-grade-mapa*) below *meia-grade-mapa* do
    (loop for linha from (- *meia-grade-mapa*) below *meia-grade-mapa* for x = (+ 64 (* (+ coluna *meia-grade-mapa*) (/ 448 (* 2 *meia-grade-mapa*)))) for y = (+ 215 (* (+ linha *meia-grade-mapa*) (/ 448 (* 2 *meia-grade-mapa*))))
          for conhecido = (gethash (cons coluna linha) (sessao-explorado sessao))
          do (retangulo x y 10 10 (if conhecido '(.38 .46 .46 1) '(.055 .075 .09 1)))
             (when (and conhecido (assoc (cons coluna linha) (sessao-marcas sessao) :test #'equal))
               (retangulo (+ x 3) (+ y 3) 4 4 *destaque*))
             (when (equal *celula-mapa* (cons coluna linha))
               (retangulo x y 10 2 *gelo*) (retangulo x (+ y 8) 10 2 *gelo*)
               (retangulo x y 2 10 *gelo*) (retangulo (+ x 8) y 2 10 *gelo*))))
  (desenhar-texto "NORTE" 248 199 1.3 *apagado*)
  (desenhar-texto "MARCA MANUAL" 570 223 2 *destaque*)
  (paragrafo "Clique numa célula conhecida ou use as setas. Escreva um rótulo e grave. O mapa não mostra inimigos nem suprimentos automaticamente."
             570 263 64 *apagado* 1.5 4)
  (botao :editar-marca (if *editando-marca* "DIGITANDO / ENTER CONCLUI" "EDITAR RÓTULO") 570 365 650
          :habilitado (gethash *celula-mapa* (sessao-explorado sessao)))
  (paragrafo *texto-marca* 586 434 53 *gelo* 1.8 2)
  (botao :guardar-marca "GRAVAR MARCA" 570 486 310 :habilitado (gethash *celula-mapa* (sessao-explorado sessao)))
  (botao :apagar-marca "APAGAR MARCA" 902 486 318 :habilitado (assoc *celula-mapa* (sessao-marcas sessao) :test #'equal))
  (desenhar-texto (format nil "~D CÉLULAS / ~D MARCAS" (hash-table-count (sessao-explorado sessao))
                                (length (sessao-marcas sessao))) 570 568 1.5 *apagado*)
  (botao :fechar-mapa "VOLTAR ÀS NOTAS" 840 617 392))
(defun processar-edicoes (sessao estado janela)
  (when *remapeando*
    (loop for tecla from 32 to 348
          when (and (not (member tecla '(256 257 258))) (entrada:key-pressed-p estado tecla))
          do (let* ((atalhos (getf *configuracao* :atalhos)) (atual (assoc *remapeando* atalhos))
                    (conflito (find tecla atalhos :key #'cdr)))
               (when conflito (setf (cdr conflito) (cdr atual)))
               (setf (cdr atual) tecla *remapeando* nil)) (return))
    (return-from processar-edicoes t))
  (when *mapa-aberto*
    (when *editando-marca*
      (let ((texto (concatenate 'string *texto-marca*
                    (if (and (entrada:key-down-p estado janela:key-left-control) (entrada:key-pressed-p estado janela:key-v))
                        (or (janela:clipboard-string janela) "") (entrada:consume-text-input estado)))))
        (when (and (entrada:key-pressed-p estado janela:key-backspace) (plusp (length texto)))
          (setf texto (subseq texto 0 (1- (length texto)))))
        (setf *texto-marca* (subseq texto 0 (min 48 (length texto)))))
      (when (entrada:key-pressed-p estado janela:key-enter)
        (adicionar-marca sessao (car *celula-mapa*) (cdr *celula-mapa*) *texto-marca*)
        (salvar-transicao sessao) (setf *editando-marca* nil))
      (return-from processar-edicoes (not (entrada:mouse-pressed-p estado janela:mouse-button-left))))
    (loop for tecla in (list janela:key-left janela:key-right janela:key-up janela:key-down)
          for deslocamento in '((-1 . 0) (1 . 0) (0 . -1) (0 . 1))
          when (entrada:key-pressed-p estado tecla)
          do (selecionar-celula sessao (+ (car *celula-mapa*) (car deslocamento)) (+ (cdr *celula-mapa*) (cdr deslocamento))))
    (when (entrada:mouse-pressed-p estado janela:mouse-button-left)
      (multiple-value-bind (x y) (entrada:mouse-position estado)
        (multiple-value-bind (largura altura) (janela:window-size janela)
          (setf x (* x (/ 1280 largura)) y (* y (/ 720 altura))))
        (when (and (<= 64 x 511) (<= 215 y 662))
          (selecionar-celula sessao (- (floor (- x 64) (/ 448 (* 2 *meia-grade-mapa*))) *meia-grade-mapa*)
                             (- (floor (- y 215) (/ 448 (* 2 *meia-grade-mapa*))) *meia-grade-mapa*))
          (return-from processar-edicoes t)))))
  nil)
(defun desenhar-interface (sessao)
  (cond (*configuracoes-abertas* (desenhar-configuracoes sessao))
        (*mapa-aberto* (desenhar-mapa sessao))
        (*historico-aberto* (desenhar-historico sessao))
        ((eq (sessao-fase sessao) :titulo) (desenhar-titulo sessao))
        ((eq (sessao-fase sessao) :notas) (desenhar-notas sessao))
        ((eq (sessao-fase sessao) :combate) (desenhar-indicadores sessao))
        ((eq (sessao-fase sessao) :pausa) (desenhar-pausa sessao))
        (t (desenhar-relatorio sessao)))
  (when *erro-persistencia*
    (retangulo 48 10 1184 32 '(.2 .035 .025 1))
    (desenhar-texto (subseq *erro-persistencia* 0 (min 110 (length *erro-persistencia*))) 58 20 1.4 *gelo*)
    (unless (eq (sessao-fase sessao) :titulo)
      (botao :tentar-salvar "TENTAR SALVAR" 1030 8 202 :altura 32))))
