(in-package #:rimefall)

(defun processar-entrada-guerra (sessao estado janela)
  (let* ((guerra *guerra-atual*) (j (jogador-local-guerra guerra)))
    (when (entrada:key-pressed-p estado janela:key-tab)
      (setf *hud-guerra-visivel* (not *hud-guerra-visivel*)))
    ;; Q deixa a batalha a qualquer momento e retorna ao menu principal.
    (when (entrada:key-pressed-p estado janela:key-q)
      (setf (sessao-fase sessao) :titulo)
      (return-from processar-entrada-guerra nil))
    (when (or (guerra-pausada guerra) (not (guerra-ativa-p guerra)))
      (when (entrada:key-pressed-p estado janela:key-enter)
        (if (guerra-ativa-p guerra) (setf (guerra-pausada guerra) nil)
            (ativar-botao sessao :guerra janela)))
      (return-from processar-entrada-guerra nil))
    (setf (jogador-guerra-frente j) (- (if (acao-mantida-p estado :frente) 1.0 0.0)
                                       (if (acao-mantida-p estado :tras) 1.0 0.0))
          (jogador-guerra-lateral j) (- (if (acao-mantida-p estado :direita) 1.0 0.0)
                                        (if (acao-mantida-p estado :esquerda) 1.0 0.0))
          (jogador-guerra-mirando j) (entrada:mouse-down-p estado janela:mouse-button-right)
          (jogador-guerra-agachado j) (acao-mantida-p estado :agachar)
          (jogador-guerra-correndo j) (and (acao-mantida-p estado :correr) (not (jogador-guerra-mirando j)))
          (jogador-guerra-gatilho j) (entrada:mouse-down-p estado janela:mouse-button-left))
    (when (jogador-ativo-p j)
      (multiple-value-bind (dx dy) (entrada:mouse-delta estado)
        (let ((sensibilidade (* (getf *configuracao* :sensibilidade) (if (jogador-guerra-mirando j) .5 1.0))))
          (incf (jogador-guerra-angulo j) (* sensibilidade dx))
          (setf (jogador-guerra-inclinacao j) (limitar (- (jogador-guerra-inclinacao j) (* sensibilidade dy)) -1.35 1.35))))
    (when (acao-pressionada-p estado :recarregar)
      (when (iniciar-recarga-guerra j) (push (list :recarga (jogador-guerra-x j) (jogador-guerra-z j)) (guerra-audio guerra)))))
    (when (entrada:key-pressed-p estado janela:key-4) (trocar-arma-guerra j 1))
    (when (entrada:key-pressed-p estado janela:key-5) (trocar-arma-guerra j -1))
    (when (acao-pressionada-p estado :recolher) (interagir-guerra guerra j))
    (loop for tecla in (list janela:key-1 janela:key-2 janela:key-3)
          for ordem in '(:atacar :defender :reunir)
          when (entrada:key-pressed-p estado tecla)
            do (dolist (esquadrao (guerra-esquadroes guerra))
                 (when (eq (esquadrao-guerra-exercito esquadrao) (jogador-guerra-exercito j))
                   (setf (esquadrao-guerra-ordem esquadrao) ordem)
                   (dolist (membro (esquadrao-guerra-jogadores esquadrao))
                     (setf (jogador-guerra-destino membro) nil)))))))

(defun desenhar-combate-guerra (guerra)
  (let* ((j (jogador-local-guerra guerra)) (setor (objetivo-guerra guerra j)))
    (retangulo 24 644 330 54 '(.025 .043 .055 .75))
    (desenhar-texto (format nil "~A   ~D / ~D   ~A"
                             (string-upcase (symbol-name (jogador-guerra-arma j)))
                             (jogador-guerra-municao j) (jogador-guerra-reserva j)
                             (if (plusp (jogador-guerra-tempo-recarga j)) "RECARREGANDO" "R / RECARGA")) 40 660 1.6 *gelo*)
    (when (plusp (jogador-guerra-ferimentos j)) (desenhar-texto "FERIDO" 40 625 1.5 *destaque*))
    (when (> (jogador-guerra-supressao j) .35)
      (desenhar-texto (if (> (jogador-guerra-supressao j) .8) "SUPRESSÃO INTENSA" "SUPRESSÃO")
                      40 605 1.25 *destaque*))
    (when setor
      (desenhar-texto (format nil "OBJETIVO / ~A / ~D M" (setor-guerra-nome setor)
                              (round (distancia (jogador-guerra-x j) (jogador-guerra-z j) (setor-guerra-x setor) (setor-guerra-z setor))))
                      28 24 1.5 *gelo*)
      (desenhar-texto (format nil "CAPTURA ~D% / AURORA ~D / BRUMA ~D"
                              (round (* 100 (abs (setor-guerra-progresso setor))))
                              (exercito-reforcos (first (guerra-exercitos guerra)))
                              (exercito-reforcos (second (guerra-exercitos guerra)))) 28 48 1.3 *apagado*))
    (when (and setor (<= (sqrt (+ (expt (- (jogador-guerra-x j) (setor-guerra-ponto-forte-x setor)) 2)
                                  (expt (- (jogador-guerra-z j) (setor-guerra-ponto-forte-z setor)) 2))) 10.0))
      (desenhar-texto "DENTRO DO PONTO FORTE / PRESENÇA 2X" 28 72 1.15 *destaque*))
    (unless setor
      (desenhar-texto "OBJETIVO / QUARTEL-GENERAL INIMIGO" 28 24 1.35 *destaque*)
      (desenhar-texto "AVANCE COM O ESQUADRÃO" 28 48 1.3 *apagado*))
    (desenhar-texto "TAB / FRENTE   E / SUPRIMENTOS   ESC / PAUSA" 780 674 1.1 *apagado*)
    (when (and (jogador-ativo-p j) (not (jogador-guerra-mirando j)))
      (retangulo 636 360 8 1 *apagado*) (retangulo 640 356 1 8 *apagado*))
    (when (guerra-invasao guerra)
      (desenhar-texto "ATENÇÃO / CRIATURAS ATRAÍDAS PELO COMBATE" 380 80 1.4 *destaque*))
    (when (> (jogador-guerra-ferido-ate j) (guerra-tempo guerra))
      (retangulo 0 0 1280 14 '(.6 .05 .04 .6)) (retangulo 0 706 1280 14 '(.6 .05 .04 .6)))
    (unless (jogador-ativo-p j)
      (retangulo 290 280 700 130 *painel*)
      (desenhar-texto (if (eq (jogador-guerra-estado j) :incapacitado) "INCAPACITADO / AGUARDE O MÉDICO" "BAIXA CONFIRMADA / REFORÇO A CAMINHO") 325 310 2 *destaque*)
      (desenhar-texto (if (eq (jogador-guerra-estado j) :incapacitado)
                         "E / ABANDONAR O SOLDADO E SOLICITAR SUBSTITUTO"
                         (format nil "NOVO SOLDADO EM ~D SEGUNDOS" (ceiling (max 0 (- (jogador-guerra-retorno-em j) (guerra-tempo guerra))))))
                      325 360 1.5 *gelo*))
    (when (or (guerra-pausada guerra) (not (guerra-ativa-p guerra)))
      (retangulo 270 250 740 220 *painel*)
      (desenhar-texto (if (guerra-pausada guerra) "GUERRA PAUSADA"
                         (format nil "FIM DA BATALHA / ~A" (or (guerra-vencedor guerra) :empate))) 305 285 2.5 *destaque*)
      (desenhar-texto (if (guerra-ativa-p guerra) "ENTER / RETOMAR" "ENTER / NOVA BATALHA") 305 350 2 *gelo*)
      (desenhar-texto "Q / VOLTAR AO MENU" 305 402 2 *gelo*))))

;;; Interface enxuta do protótipo. A apresentação 3D compartilha a mesma LWLGL.
(defun estado-setores-guerra (guerra)
  (mapcar (lambda (setor)
            (format nil "~A / ~A / ~D%%"
                    (setor-guerra-nome setor)
                    (or (setor-guerra-dono setor) "disputado")
                    (round (* 100 (abs (setor-guerra-progresso setor))))))
          (guerra-setores guerra)))

(defun painel-guerra (guerra)
  (list :tempo (guerra-tempo guerra) :fase (guerra-fase guerra)
        :setores (estado-setores-guerra guerra)
        :reforcos (mapcar (lambda (exercito)
                            (list (exercito-id exercito) (exercito-reforcos exercito)))
                          (guerra-exercitos guerra))
        :vencedor (guerra-vencedor guerra)
        :invasao (and (guerra-invasao guerra) :ativa)
        :mensagens (mensagens-recentes-guerra guerra 4)))

(defun cor-dono-setor (dono)
  (cond ((eq dono :AURORA) '(.28 .40 .25 1.0))
        ((eq dono :BRUMA) '(.30 .34 .42 1.0))
        (t '(.32 .34 .29 1.0))))

(defun nome-curto-guerra (texto limite)
  (if (> (length texto) limite) (concatenate 'string (subseq texto 0 (- limite 1)) ".") texto))

(defun desenhar-cartao-setor (setor x y largura)
  (let* ((dono (setor-guerra-dono setor))
         (progresso (min 1.0 (abs (setor-guerra-progresso setor))))
         (nome (nome-curto-guerra (setor-guerra-nome setor) 20)))
    (retangulo x y largura 112 '(.055 .072 .056 .94))
    (moldura x y largura 112 (cor-dono-setor dono))
    (retangulo (+ x 1) (+ y 1) (- largura 2) 5 (cor-dono-setor dono))
    (desenhar-texto nome (+ x 10) (+ y 18) 1.2 *gelo*)
    (desenhar-texto (string-upcase (or dono "DISPUTADO")) (+ x 10) (+ y 44) 1.15
                    (if dono *gelo* *apagado*))
    (retangulo (+ x 10) (+ y 72) (- largura 20) 8 '(.11 .14 .11 1.0))
    (when (plusp progresso)
      (retangulo (+ x 10) (+ y 72) (* (- largura 20) progresso) 8 *bronze-menu*))
    (desenhar-texto (format nil "~D%%" (round (* 100 progresso))) (+ x 10) (+ y 88) 1.1 *apagado*)))

(defun desenhar-interface-guerra (guerra)
  "Desenha um HUD de combate; o terreno permanece visível entre os painéis."
  (desenhar-combate-guerra guerra)
  (unless *hud-guerra-visivel*
    (return-from desenhar-interface-guerra nil))
  ;; Barra superior de comando, com leitura semelhante a uma tela de
  ;; destacamento: operação, relógio e fase ficam sempre no mesmo lugar.
  (retangulo 0 0 1280 62 *carvao-menu*)
  (retangulo 0 0 1280 5 *bronze-menu*)
  (desenhar-texto "RIMEFALL / CENTRO DE COMANDO" 28 18 1.8 *bronze-menu*)
  (desenhar-texto "GUERRA / FRENTE ATIVA" 430 21 1.35 *gelo*)
  (desenhar-texto (format nil "~2,'0D:~2,'0D / ~A"
                          (floor (/ (guerra-tempo guerra) 60))
                          (mod (floor (guerra-tempo guerra)) 60)
                          (string-upcase (symbol-name (guerra-fase guerra))))
                 650 19 1.7 *gelo*)
  (desenhar-texto "OBJETIVO / ALCANÇAR O QG INIMIGO" 900 21 1.15 *apagado*)
  ;; A linha de frente é apresentada como cartões de situação, permitindo
  ;; identificar rapidamente o setor contestado sem marcadores no mundo 3D.
  (desenhar-texto "FRENTE / SITUAÇÃO DOS SETORES" 28 88 1.45 *bronze-menu*)
  (loop for setor in (guerra-setores guerra) for indice from 0
        do (desenhar-cartao-setor setor (+ 26 (* indice 158)) 112 146))
  ;; Exércitos e reforços ficam separados para leitura rápida.
  (retangulo 875 88 379 180 '(.055 .072 .056 .94))
  (moldura 875 88 379 180 '(.25 .31 .23 1))
  (desenhar-texto "EXÉRCITOS / RESERVAS" 900 108 1.35 *bronze-menu*)
  (loop for exercito in (guerra-exercitos guerra) for indice from 0
        do (desenhar-texto (format nil "~A / REFORÇOS ~D / ORDEM ~A"
                                   (exercito-nome exercito) (exercito-reforcos exercito)
                                   (exercito-ordem exercito))
                           900 (+ 145 (* indice 42)) 1.25 *gelo*))
  (when (guerra-invasao guerra)
    (retangulo 420 78 440 42 '(.35 .055 .04 .85))
    (desenhar-texto "INVASÃO / MONSTROS A CAMINHO DO RUÍDO" 440 92 1.3 *destaque*))
  ;; Mensagens de comando ocupam um painel pequeno e transitório.
  (retangulo 875 292 379 150 '(.055 .072 .056 .94))
  (moldura 875 292 379 150 '(.25 .31 .23 1))
  (desenhar-texto "COMUNICAÇÕES / ESQUADRÃO" 900 312 1.2 *bronze-menu*)
  (let ((jogador (jogador-local-guerra guerra)))
    (retangulo 26 570 520 104 '(.025 .043 .055 .68))
    (desenhar-texto (format nil "VOCÊ / ~A / ~A / MUNIÇÃO ~D~@[ / INCAPACITADO~]~@[ / RECARREGANDO~]"
                            (jogador-guerra-nome jogador)
                            (string-upcase (symbol-name (jogador-guerra-funcao jogador)))
                            (jogador-guerra-municao jogador)
                            (when (eq (jogador-guerra-estado jogador) :incapacitado) t)
                            (when (plusp (jogador-guerra-tempo-recarga jogador)) t))
                    48 590 1.35 *gelo*)
    (desenhar-texto (format nil "POSIÇÃO ~D / ~D   ·   BATALHA EM PRIMEIRA PESSOA / LEIA O TERRENO E O SOM"
                            (round (jogador-guerra-x jogador))
                            (round (jogador-guerra-z jogador)))
                    48 620 1.05 *apagado*))
  (loop for mensagem in (mensagens-recentes-guerra guerra 4) for indice from 0
        do (desenhar-texto (getf mensagem :texto) 900 (+ 335 (* indice 25)) 1.1 *apagado*))
    (desenhar-texto "WASD/SETAS MOVER   MOUSE MIRAR   CLIQUE OU ESPAÇO ATIRAR   R RECARREGAR   4/5 TROCAR ARMA" 580 590 1.0 *apagado*)
  (desenhar-texto "1 ATAQUE   2 DEFESA   3 REUNIÃO   ESC SAIR DA GUERRA" 580 620 1.15 *apagado*)
  (desenhar-texto "BATALHA OFFLINE 8 CONTRA 8 / TAB MOSTRA OU OCULTA O HUD" 580 650 1.05 *apagado*)
  ;; Mira discreta: não revela inimigos nem substitui a leitura do terreno.
  (retangulo 638 357 4 6 *gelo*)
  (retangulo 635 360 10 1 *gelo*)
  (retangulo 635 359 1 3 *gelo*)
  (retangulo 644 359 1 3 *gelo*)
  (when (and (jogador-local-guerra guerra)
             (> (jogador-guerra-tempo-arma (jogador-local-guerra guerra)) .20))
    ;; Clarão curto confirma o ciclo do disparo sem criar um marcador de alvo.
    (retangulo 632 350 16 20 *destaque*)))
