(in-package #:rimefall)

(defparameter *limiar-invasao* 100.0)
(defparameter *aviso-invasao* 20.0)
(defparameter *duracao-invasao* 180.0)
(defstruct (monstro-guerra (:constructor criar-monstro-guerra)
                           (:predicate monstro-guerra-p))
  id x z alvo-x alvo-z (vida 100.0) (estado :aproximando) (ataque 0.0))
(defstruct (invasao-guerra (:constructor criar-invasao-guerra)
                           (:predicate invasao-guerra-p))
  (estado :aviso) (tempo 0.0) (x 0.0) (z 0.0) (monstros nil)
  (alvo-exercito nil) (dano-qg 0.0))

(defun registrar-ruido-guerra (guerra x z intensidade origem)
  "Ruídos acumulam pressão, mas nunca revelam a posição de um jogador."
  (declare (ignore origem))
  (incf (guerra-pressao-sonora guerra) (max 0.0 (* intensidade .08)))
  (when (and (null (guerra-invasao guerra))
             (>= (guerra-pressao-sonora guerra) *limiar-invasao*))
    (setf (guerra-invasao guerra)
          (criar-invasao-guerra :tempo 0.0 :x (float x) :z (float z)))
    (dolist (exercito (guerra-exercitos guerra))
      (emitir-mensagem-guerra guerra exercito
                              "Pressão sonora crítica. Invasão se aproxima." :comando))))

(defun criar-horda-guerra (invasao)
  (setf (invasao-guerra-monstros invasao)
        (loop for id below 12
              collect (criar-monstro-guerra :id id
                                            :x (+ (invasao-guerra-x invasao) (* (- id 6) 8.0))
                                            :z (+ (invasao-guerra-z invasao) 70.0)
                                            :alvo-x (invasao-guerra-x invasao)
                                            :alvo-z (invasao-guerra-z invasao)))))

(defun atualizar-invasao-guerra (guerra intervalo)
  (let ((invasao (guerra-invasao guerra)))
    (when invasao
      (incf (invasao-guerra-tempo invasao) intervalo)
      (case (invasao-guerra-estado invasao)
        (:aviso (when (>= (invasao-guerra-tempo invasao) *aviso-invasao*)
                 (setf (invasao-guerra-estado invasao) :ataque)
                 (criar-horda-guerra invasao)))
        (:ataque
         (dolist (monstro (invasao-guerra-monstros invasao))
           (when (plusp (monstro-guerra-vida monstro))
             (let ((dist (sqrt (+ (expt (- (monstro-guerra-x monstro)
                                            (monstro-guerra-alvo-x monstro)) 2)
                                  (expt (- (monstro-guerra-z monstro)
                                            (monstro-guerra-alvo-z monstro)) 2)))))
               (if (> dist 2.0)
                   (progn
                     (incf (monstro-guerra-x monstro)
                           (* intervalo (/ (- (monstro-guerra-alvo-x monstro)
                                              (monstro-guerra-x monstro)) (max dist 1.0)) 6.0))
                     (incf (monstro-guerra-z monstro)
                           (* intervalo (/ (- (monstro-guerra-alvo-z monstro)
                                              (monstro-guerra-z monstro)) (max dist 1.0)) 6.0)))
                   (incf (invasao-guerra-dano-qg invasao) (* intervalo 1.5))))))
         (when (>= (invasao-guerra-dano-qg invasao) 20.0)
           (dolist (exercito (guerra-exercitos guerra))
             (when (< (distancia (quartel-general-x (exercito-quartel-general exercito))
                                 (quartel-general-z (exercito-quartel-general exercito))
                                 (invasao-guerra-x invasao) (invasao-guerra-z invasao))
                       150.0)
               (aplicar-dano-qg guerra exercito 10.0 "Invasão"))))
         (when (>= (invasao-guerra-tempo invasao) (+ *aviso-invasao* *duracao-invasao*))
           (setf (guerra-invasao guerra) nil (guerra-pressao-sonora guerra) 0.0)))))))

(defun eliminar-monstro-guerra (guerra monstro)
  (when (plusp (monstro-guerra-vida monstro))
    (setf (monstro-guerra-vida monstro) 0.0)
    (when (guerra-invasao guerra)
      (setf (invasao-guerra-monstros (guerra-invasao guerra))
            (remove monstro (invasao-guerra-monstros (guerra-invasao guerra)))))
    t))
