(in-package #:rimefall)

(defparameter *limiar-invasao* 100.0)
(defparameter *aviso-invasao* 20.0)
(defparameter *duracao-invasao* 180.0)
(defstruct (monstro-guerra (:constructor criar-monstro-guerra)
                           (:predicate monstro-guerra-p))
  id x z alvo-x alvo-z (vida 100.0) (estado :aproximando) (ataque 0.0))
(defstruct (invasao-guerra (:constructor criar-invasao-guerra)
                           (:predicate invasao-guerra-p))
  (estado :aviso) (tempo 0.0) (x 0.0) (z 0.0) (monstros nil)
  (alvo-exercito nil) (dano-qg 0.0))

(defun registrar-ruido-guerra (guerra x z intensidade origem)
  "Ruídos acumulam pressão, mas nunca revelam a posição de um jogador."
  (when (and (guerra-invasao guerra) (not (eq origem :passos)))
    (dolist (monstro (invasao-guerra-monstros (guerra-invasao guerra)))
      (when (< (distancia x z (monstro-guerra-x monstro) (monstro-guerra-z monstro)) (* intensidade 2))
        (setf (monstro-guerra-alvo-x monstro) x (monstro-guerra-alvo-z monstro) z))))
  (incf (guerra-pressao-sonora guerra) (max 0.0 (* intensidade .08)))
  (when (and (null (guerra-invasao guerra))
             (>= (guerra-pressao-sonora guerra) *limiar-invasao*))
    (setf (guerra-invasao guerra)
          (criar-invasao-guerra :tempo 0.0 :x (float x) :z (float z)))
    (dolist (exercito (guerra-exercitos guerra))
      (emitir-mensagem-guerra guerra exercito
                              "Pressão sonora crítica. Invasão se aproxima." :comando))))

(defun criar-horda-guerra (invasao)
  (setf (invasao-guerra-monstros invasao)
        (loop for id below 12
              collect (criar-monstro-guerra :id id
                                            :x (+ (invasao-guerra-x invasao) (* (- id 6) 8.0))
                                            :z (+ (invasao-guerra-z invasao) 70.0)
                                            :alvo-x (invasao-guerra-x invasao)
                                            :alvo-z (invasao-guerra-z invasao)))))

(defun atualizar-invasao-guerra (guerra intervalo)
  (unless (and (guerra-ativa-p guerra) (not (guerra-pausada guerra)))
    (return-from atualizar-invasao-guerra nil))
  (let ((invasao (guerra-invasao guerra)))
    (when invasao
      (incf (invasao-guerra-tempo invasao) intervalo)
      (when (and (eq (invasao-guerra-estado invasao) :aviso)
                 (>= (invasao-guerra-tempo invasao) *aviso-invasao*))
        (setf (invasao-guerra-estado invasao) :ataque)
        (criar-horda-guerra invasao))
      (dolist (monstro (invasao-guerra-monstros invasao))
        (when (plusp (monstro-guerra-vida monstro))
          (setf (monstro-guerra-ataque monstro) (max 0.0 (- (monstro-guerra-ataque monstro) intervalo)))
          (let* ((dx (- (monstro-guerra-alvo-x monstro) (monstro-guerra-x monstro)))
                 (dz (- (monstro-guerra-alvo-z monstro) (monstro-guerra-z monstro)))
                 (dist (max .001 (sqrt (+ (* dx dx) (* dz dz)))))
                 (velocidade (min dist (* intervalo 3.8))))
            (when (> dist .8)
              (unless (colisao-guerra-p (+ (monstro-guerra-x monstro) (* velocidade (/ dx dist))) (monstro-guerra-z monstro))
                (incf (monstro-guerra-x monstro) (* velocidade (/ dx dist))))
              (unless (colisao-guerra-p (monstro-guerra-x monstro) (+ (monstro-guerra-z monstro) (* velocidade (/ dz dist))))
                (incf (monstro-guerra-z monstro) (* velocidade (/ dz dist))))))
          ;; Contato próximo independe do som; fora dele a criatura só segue a pista.
          (dolist (j (guerra-jogadores guerra))
            (when (and (jogador-ativo-p j) (zerop (monstro-guerra-ataque monstro))
                       (< (distancia (jogador-guerra-x j) (jogador-guerra-z j) (monstro-guerra-x monstro) (monstro-guerra-z monstro)) 1.6))
              (ferir-jogador-guerra guerra j)
              (setf (monstro-guerra-ataque monstro) 1.6)
              (push (list :criatura (monstro-guerra-x monstro) (monstro-guerra-z monstro)) (guerra-audio guerra))))
          (dolist (exercito (guerra-exercitos guerra))
            (let ((qg (exercito-quartel-general exercito)))
              (when (< (distancia (monstro-guerra-x monstro) (monstro-guerra-z monstro) (quartel-general-x qg) (quartel-general-z qg)) 22)
                (decf (quartel-general-vida qg) (* intervalo 8))
                (when (<= (quartel-general-vida qg) 0) (aplicar-dano-qg guerra exercito 0 "Criaturas")))))))
      (when (> (invasao-guerra-tempo invasao) (+ *aviso-invasao* *duracao-invasao*))
        (setf (guerra-invasao guerra) nil (guerra-pressao-sonora guerra) 0.0)))))

(defun eliminar-monstro-guerra (guerra monstro)
  (when (plusp (monstro-guerra-vida monstro))
    (setf (monstro-guerra-vida monstro) 0.0)
    (when (guerra-invasao guerra)
      (setf (invasao-guerra-monstros (guerra-invasao guerra))
            (remove monstro (invasao-guerra-monstros (guerra-invasao guerra)))))
    t))
