(in-package #:rimefall)

(defun criar-logistica-guerra (guerra)
  (dolist (exercito (guerra-exercitos guerra))
    (push (criar-veiculo-guerra :id (list :caminhao (exercito-id exercito))
                                :exercito exercito
                                :x -20.0 :z (if (eq (exercito-id exercito) :aurora) -60.0 60.0)
                                :destino-x -20.0 :destino-z (if (eq (exercito-id exercito) :aurora) -60.0 60.0))
          (guerra-veiculos guerra))
    (push (criar-morteiro-guerra :id (list :morteiro (exercito-id exercito))
                                 :exercito exercito :x 12.0
                                 :z (quartel-general-z (exercito-quartel-general exercito)))
          (guerra-morteiros guerra)))
  guerra)

(defun embarcar-jogador-guerra (veiculo jogador)
  (when (and (eq (jogador-guerra-exercito jogador) (veiculo-guerra-exercito veiculo))
             (jogador-ativo-p jogador)
             (< (length (veiculo-guerra-passageiros veiculo)) (veiculo-guerra-capacidade veiculo))
             (< (sqrt (+ (expt (- (jogador-guerra-x jogador) (veiculo-guerra-x veiculo)) 2)
                          (expt (- (jogador-guerra-z jogador) (veiculo-guerra-z veiculo)) 2))) 5.0))
    (pushnew jogador (veiculo-guerra-passageiros veiculo))
    (setf (jogador-guerra-x jogador) (veiculo-guerra-x veiculo)
          (jogador-guerra-z jogador) (veiculo-guerra-z veiculo))
    t))

(defun desembarcar-jogador-guerra (veiculo jogador)
  (when (member jogador (veiculo-guerra-passageiros veiculo))
    (setf (veiculo-guerra-passageiros veiculo)
          (remove jogador (veiculo-guerra-passageiros veiculo)))
    t))

(defun dirigir-caminhao-guerra (veiculo jogador x z)
  (when (and (eq jogador (veiculo-guerra-motorista veiculo))
             (jogador-ativo-p jogador))
    (setf (veiculo-guerra-destino-x veiculo) (float x)
          (veiculo-guerra-destino-z veiculo) (float z))
    t))

(defun carregar-caminhao-guerra (veiculo jogador quantidade)
  (when (and (eq (jogador-guerra-funcao jogador) :suporte)
             (eq (jogador-guerra-exercito jogador) (veiculo-guerra-exercito veiculo))
             (<= quantidade 100))
    (incf (veiculo-guerra-carga veiculo) (max 0 quantidade))
    t))

(defun operar-morteiro-guerra (morteiro jogador x z)
  (when (and (eq (jogador-guerra-exercito jogador) (morteiro-guerra-exercito morteiro))
             (member (jogador-guerra-funcao jogador) '(:suporte :comandante)))
    (if (eq (morteiro-guerra-operador morteiro) jogador)
        (setf (morteiro-guerra-alvo-x morteiro) (float x)
              (morteiro-guerra-alvo-z morteiro) (float z))
        (when (eq (jogador-guerra-funcao jogador) :suporte)
          (setf (morteiro-guerra-observador morteiro) jogador)))
    (and (morteiro-guerra-operador morteiro) (morteiro-guerra-observador morteiro))))

(defun disparar-morteiro-guerra (guerra morteiro)
  (when (and (morteiro-guerra-operador morteiro)
             (morteiro-guerra-observador morteiro)
             (plusp (morteiro-guerra-municao morteiro))
             (zerop (morteiro-guerra-recarga morteiro)))
    (decf (morteiro-guerra-municao morteiro))
    (setf (morteiro-guerra-recarga morteiro) 4.0)
    (registrar-ruido-guerra guerra (morteiro-guerra-alvo-x morteiro)
                             (morteiro-guerra-alvo-z morteiro) 100.0 :morteiro)
    t))

(defun atualizar-logistica-guerra (guerra intervalo)
  (unless (and (guerra-ativa-p guerra) (not (guerra-pausada guerra)))
    (return-from atualizar-logistica-guerra guerra))
  (dolist (veiculo (guerra-veiculos guerra))
    (let ((dist (sqrt (+ (expt (- (veiculo-guerra-destino-x veiculo) (veiculo-guerra-x veiculo)) 2)
                          (expt (- (veiculo-guerra-destino-z veiculo) (veiculo-guerra-z veiculo)) 2)))))
      (when (and (> dist .5) (veiculo-guerra-motorista veiculo) (plusp (veiculo-guerra-vida veiculo)))
        (incf (veiculo-guerra-x veiculo)
              (* intervalo (/ (- (veiculo-guerra-destino-x veiculo) (veiculo-guerra-x veiculo)) dist)
                 (veiculo-guerra-velocidade veiculo)))
        (incf (veiculo-guerra-z veiculo)
              (* intervalo (/ (- (veiculo-guerra-destino-z veiculo) (veiculo-guerra-z veiculo)) dist)
                 (veiculo-guerra-velocidade veiculo)))
        (dolist (jogador (veiculo-guerra-passageiros veiculo))
          (setf (jogador-guerra-x jogador) (veiculo-guerra-x veiculo)
                (jogador-guerra-z jogador) (veiculo-guerra-z veiculo)))))
    (when (plusp (veiculo-guerra-carga veiculo))
      (decf (veiculo-guerra-carga veiculo) 0.01)))
  (dolist (morteiro (guerra-morteiros guerra))
    (when (plusp (morteiro-guerra-recarga morteiro))
      (setf (morteiro-guerra-recarga morteiro) (max 0.0 (- (morteiro-guerra-recarga morteiro) intervalo)))))
  guerra)
