(in-package #:rimefall)

;;; Somente dados conhecidos atravessam o arquivo; nunca objetos de OpenGL/OpenAL.
(defvar *persistencia-ativa* nil)
(defvar *pasta-dados* nil)
(defvar *pasta-configuracao* nil)
(defvar *erro-persistencia* nil)
(defvar *gravacao-bloqueada* nil)
(defparameter *versao-salvamento* 4)
(defparameter *atalhos-padrao*
  '((:frente . 87) (:tras . 83) (:esquerda . 65) (:direita . 68)
    (:correr . 340) (:agachar . 341) (:recarregar . 82) (:recolher . 69)
    (:isca . 71) (:dispositivo . 70) (:apoiar . 66)))
(defun configuracao-padrao ()
  (list :sensibilidade .0022 :visao 72 :largura 1280 :altura 720 :tela-cheia nil
        :sincronizar t :neve 170 :volume 1.0 :efeitos 1.0 :ambiente .7
        :atalhos (copy-tree *atalhos-padrao*)))
(defvar *configuracao* (configuracao-padrao))
(defparameter *estruturas-persistentes*
  '((sessao . %criar-sessao) (soldado . criar-soldado) (inimigo . criar-inimigo)
    (obstaculo . criar-obstaculo) (suprimento . criar-suprimento) (ruido . criar-ruido)
    (isca . criar-isca) (dispositivo . criar-dispositivo) (evidencia . criar-evidencia) (notas . criar-notas)))
(defun pasta-usuario (variavel padrao)
  (uiop:ensure-directory-pathname
   (merge-pathnames "rimefall/"
    (uiop:ensure-directory-pathname (or (uiop:getenv variavel) (merge-pathnames padrao (user-homedir-pathname)))))))
(defun caminho-sessao () (merge-pathnames "sessao.sexp" (or *pasta-dados* (pasta-usuario "XDG_DATA_HOME" ".local/share/"))))
(defun caminho-configuracao ()
  (merge-pathnames "preferencias.sexp" (or *pasta-configuracao* (pasta-usuario "XDG_CONFIG_HOME" ".config/"))))
(defun campos-estrutura (tipo)
  (mapcar #'sb-mop:slot-definition-name (sb-mop:class-slots (find-class tipo))))
(defun codificar-dados (valor)
  (cond ((or (null valor) (eq valor t) (keywordp valor) (numberp valor) (stringp valor)) valor)
        ((symbolp valor) (list :simbolo (symbol-name valor)))
        ((consp valor) (list :par (codificar-dados (car valor)) (codificar-dados (cdr valor))))
        ((hash-table-p valor)
         (list :tabela (if (eq (hash-table-test valor) 'equal) :igual :identico)
               (loop for chave being the hash-keys of valor using (hash-value dado)
                     collect (list (codificar-dados chave) (codificar-dados dado)))))
        ((assoc (type-of valor) *estruturas-persistentes*)
         (list :estrutura (symbol-name (type-of valor))
               (loop for campo in (campos-estrutura (type-of valor))
                     collect (list (symbol-name campo) (codificar-dados (slot-value valor campo))))))
        (t (error "Dado não permitido no salvamento: ~S" (type-of valor)))))
(defun decodificar-dados (valor &optional (profundidade 0))
  (when (> profundidade 4096) (error "Salvamento excessivamente aninhado."))
  (flet ((decodificar (dado) (decodificar-dados dado (1+ profundidade))))
    (cond ((or (null valor) (eq valor t) (keywordp valor) (realp valor) (stringp valor)) valor)
          ((consp valor)
           (case (first valor)
             (:simbolo (or (find-symbol (second valor) :rimefall) (error "Símbolo desconhecido.")))
             (:par (unless (= (length valor) 3) (error "Par inválido."))
                   (cons (decodificar (second valor)) (decodificar (third valor))))
             (:tabela
              (unless (member (second valor) '(:igual :identico)) (error "Tabela inválida."))
              (let ((tabela (make-hash-table :test (if (eq (second valor) :igual) #'equal #'eql))))
                (dolist (par (third valor)) (setf (gethash (decodificar (first par)) tabela) (decodificar (second par))))
                tabela))
             (:estrutura
              (let* ((tipo (find-symbol (second valor) :rimefall))
                     (construtor (cdr (assoc tipo *estruturas-persistentes*)))
                     (campos (when construtor (campos-estrutura tipo))) (argumentos nil))
                (unless (and construtor (= (length campos) (length (third valor)))) (error "Estrutura incompatível."))
                (loop for campo in campos for par in (third valor)
                      do (unless (string= (symbol-name campo) (first par)) (error "Campo incompatível."))
                         (setf argumentos (append argumentos (list (intern (symbol-name campo) :keyword) (decodificar (second par))))))
                (apply construtor argumentos)))
             (t (error "Formato de dado desconhecido."))))
          (t (error "Valor inválido no salvamento.")))))
(defun rejeitar-despacho (arquivo caractere)
  (declare (ignore arquivo caractere)) (error "Sintaxe de leitor não permitida."))
(defun ler-dados (caminho)
  (let ((*read-eval* nil) (*readtable* (copy-readtable nil)) (*package* (find-package :keyword)))
    ;; Impede #S, #., referências circulares e demais extensões do leitor.
    (set-macro-character #\# #'rejeitar-despacho nil *readtable*)
    (with-open-file (arquivo caminho :external-format :utf-8)
      (when (> (file-length arquivo) 8000000) (error "Arquivo de dados grande demais."))
      (let ((valor (read arquivo)))
        (unless (eq (read arquivo nil :fim) :fim) (error "Dados extras no arquivo.")) valor))))
(defun gravar-dados (caminho dados)
  (ensure-directories-exist caminho)
  (let ((temporario (make-pathname :type "temporario" :defaults caminho)))
    (unwind-protect
         (progn
           (with-open-file (arquivo temporario :direction :output :if-exists :supersede :external-format :utf-8)
             (let ((*print-pretty* nil) (*print-circle* nil) (*print-readably* nil) (*print-escape* t) (*print-level* nil) (*print-length* nil)
                   (*package* (find-package :keyword)))
               (write dados :stream arquivo) (terpri arquivo) (finish-output arquivo)))
           (uiop:rename-file-overwriting-target temporario caminho))
      (when (probe-file temporario) (delete-file temporario)))))
(defun conferir-sessao (sessao)
  (unless (and (sessao-p sessao) (eq (sessao-mapa sessao) :posto-ampliado)
               (member (sessao-fase sessao) '(:notas :combate :pausa :relatorio :derrota :vitoria))
               (<= 0 (sessao-usados sessao) 4) (<= 0 (sessao-onda sessao) 3)
               (not (validar-notas (sessao-notas sessao) (sessao-acervo sessao)))
               (<= 0 (sessao-tempo sessao))
               (member (sessao-clima sessao) '(:calmaria :aviso :rajada))
               (hash-table-p (sessao-explorado sessao)))
    (error "Sessão incompatível ou danificada."))
  (let ((soldado (sessao-soldado sessao)))
    (when (and (member (sessao-fase sessao) '(:combate :pausa))
               (or (not (soldado-p soldado)) (soldado-transferido soldado) (>= (soldado-ferimentos soldado) 2)))
      (error "Estado de vida inconsistente."))
    (when soldado
      (unless (and (<= 0 (soldado-carregador soldado) (capacidade-arma (soldado-arma soldado)))
                   (<= 0 (soldado-reserva-fuzil soldado)) (<= 0 (soldado-reserva-escopeta soldado))
                   (<= 0 (soldado-reserva-carabina soldado)) (<= 0 (soldado-reserva-submetralhadora soldado))
                   (<= 0 (soldado-reserva-precisao soldado)) (<= 0 (soldado-reserva-franco-atirador soldado))
                   (= (soldado-numero soldado) (sessao-usados sessao))) (error "Inventário inconsistente."))))
  sessao)
(defun salvar-sessao (sessao)
  (when (or (not *persistencia-ativa*) *gravacao-bloqueada*) (return-from salvar-sessao nil))
  (handler-case
      (let ((copia (copiar-sessao sessao)))
        (setf (sessao-sons copia) nil)
        (gravar-dados (caminho-sessao) (list :rimefall *versao-salvamento* (codificar-dados copia)))
        (setf *erro-persistencia* nil) t)
    (error (condicao) (setf *erro-persistencia* (format nil "Não foi possível salvar: ~A" condicao)) nil)))
(defun salvar-transicao (sessao)
  (when *persistencia-ativa*
    (unless (salvar-sessao sessao)
      (setf *gravacao-bloqueada* t))
    (setf (sessao-salvamento-em sessao) (+ (sessao-tempo sessao) 5.0))))
(defun salvar-periodicamente (sessao)
  (when (and *persistencia-ativa* (not (eq (sessao-fase sessao) :titulo))
             (>= (sessao-tempo sessao) (sessao-salvamento-em sessao)))
    (setf (sessao-salvamento-em sessao) (+ (sessao-tempo sessao) 5.0))
    (salvar-sessao sessao)))
(defun carregar-sessao ()
  (handler-case
      (let ((dados (ler-dados (caminho-sessao))))
        (unless (and (eq (first dados) :rimefall) (eql (second dados) *versao-salvamento*))
          (error "Versão de salvamento incompatível."))
        (let ((sessao (conferir-sessao (decodificar-dados (third dados)))))
          (when (eq (sessao-fase sessao) :combate) (setf (sessao-fase sessao) :pausa))
          (setf *erro-persistencia* nil *gravacao-bloqueada* nil) sessao))
    (error (condicao)
      (setf *erro-persistencia* (format nil "Não foi possível continuar: ~A" condicao)
            *gravacao-bloqueada* t) nil)))
(defun conferir-configuracao (dados)
  (unless (and (listp dados)
               (<= .0005 (getf dados :sensibilidade) .008)
               (<= 55 (getf dados :visao) 100)
               (member (list (getf dados :largura) (getf dados :altura)) '((1280 720) (1600 900) (1920 1080)) :test #'equal)
               (member (getf dados :neve) '(0 85 170 255))
               (every (lambda (chave) (<= 0 (getf dados chave) 1)) '(:volume :efeitos :ambiente))
               (member (getf dados :tela-cheia) '(nil t)) (member (getf dados :sincronizar) '(nil t))
               (= (length (getf dados :atalhos)) (length *atalhos-padrao*))
               (every (lambda (par) (let ((tecla (cdr (assoc (car par) (getf dados :atalhos)))))
                                     (and (integerp tecla) (<= 32 tecla 348) (not (member tecla '(256 257 258))))))
                      *atalhos-padrao*)
               (= (length (remove-duplicates (mapcar #'cdr (getf dados :atalhos)))) (length *atalhos-padrao*)))
    (error "Preferências inválidas.")) dados)
(defun carregar-configuracao ()
  (when (probe-file (caminho-configuracao))
    (handler-case
        (setf *configuracao* (conferir-configuracao (decodificar-dados (ler-dados (caminho-configuracao)))))
      (error (condicao) (setf *erro-persistencia* (format nil "Preferências não carregadas: ~A" condicao))))))
(defun salvar-configuracao ()
  (handler-case
      (progn (conferir-configuracao *configuracao*)
             (gravar-dados (caminho-configuracao) (codificar-dados *configuracao*)) t)
    (error (condicao) (setf *erro-persistencia* (format nil "Preferências não salvas: ~A" condicao)) nil)))
