(in-package #:rimefall)

;;; Somente dados conhecidos atravessam o arquivo; nunca objetos de OpenGL/OpenAL.
(defvar *persistencia-ativa* nil)
(defvar *pasta-dados* nil)
(defvar *pasta-configuracao* nil)
(defvar *erro-persistencia* nil)
(defvar *gravacao-bloqueada* nil)
(defparameter *versao-salvamento* 4)
(defparameter *atalhos-padrao*
  '((:frente . 87) (:tras . 83) (:esquerda . 65) (:direita . 68)
    (:correr . 340) (:agachar . 341) (:recarregar . 82) (:recolher . 69)
    (:isca . 71) (:dispositivo . 70) (:apoiar . 66)))
(defun configuracao-padrao ()
  (list :sensibilidade .0022 :visao 72 :largura 1280 :altura 720 :tela-cheia nil
        :sincronizar t :neve 170 :volume 1.0 :efeitos 1.0 :ambiente .7
        :atalhos (copy-tree *atalhos-padrao*)))
(defvar *configuracao* (configuracao-padrao))
(defparameter *estruturas-persistentes*
  '((sessao . %criar-sessao) (soldado . criar-soldado) (inimigo . criar-inimigo)
    (obstaculo . criar-obstaculo) (suprimento . criar-suprimento) (ruido . criar-ruido)
    (isca . criar-isca) (dispositivo . criar-dispositivo) (evidencia . criar-evidencia) (notas . criar-notas)
    (quartel-general . criar-quartel-general) (exercito . criar-exercito)
    (setor-guerra . criar-setor-guerra) (esquadrao-guerra . criar-esquadrao-guerra)
    (jogador-guerra . criar-jogador-guerra) (comando-guerra . criar-comando-guerra)
    (veiculo-guerra . criar-veiculo-guerra) (morteiro-guerra . criar-morteiro-guerra)
    (guerra . criar-guerra) (monstro-guerra . criar-monstro-guerra)
    (invasao-guerra . criar-invasao-guerra)))
(defun pasta-usuario (variavel padrao)
  (uiop:ensure-directory-pathname
   (merge-pathnames "rimefall/"
    (uiop:ensure-directory-pathname (or (uiop:getenv variavel) (merge-pathnames padrao (user-homedir-pathname)))))))
(defun caminho-sessao () (merge-pathnames "sessao.sexp" (or *pasta-dados* (pasta-usuario "XDG_DATA_HOME" ".local/share/"))))
(defun caminho-configuracao ()
  (merge-pathnames "preferencias.sexp" (or *pasta-configuracao* (pasta-usuario "XDG_CONFIG_HOME" ".config/"))))
(defun campos-estrutura (tipo)
  (mapcar #'sb-mop:slot-definition-name (sb-mop:class-slots (find-class tipo))))
(defun codificar-dados (valor)
  (cond ((or (null valor) (eq valor t) (keywordp valor) (numberp valor) (stringp valor)) valor)
        ((symbolp valor) (list :simbolo (symbol-name valor)))
        ((consp valor) (list :par (codificar-dados (car valor)) (codificar-dados (cdr valor))))
        ((hash-table-p valor)
         (list :tabela (if (eq (hash-table-test valor) 'equal) :igual :identico)
               (loop for chave being the hash-keys of valor using (hash-value dado)
                     collect (list (codificar-dados chave) (codificar-dados dado)))))
        ((assoc (type-of valor) *estruturas-persistentes*)
         (list :estrutura (symbol-name (type-of valor))
               (loop for campo in (campos-estrutura (type-of valor))
                     collect (list (symbol-name campo) (codificar-dados (slot-value valor campo))))))
        (t (error "Dado não permitido no salvamento: ~S" (type-of valor)))))
(defun decodificar-dados (valor &optional (profundidade 0))
  (when (> profundidade 4096) (error "Salvamento excessivamente aninhado."))
  (flet ((decodificar (dado) (decodificar-dados dado (1+ profundidade))))
    (cond ((or (null valor) (eq valor t) (keywordp valor) (realp valor) (stringp valor)) valor)
          ((consp valor)
           (case (first valor)
             (:simbolo (or (find-symbol (second valor) :rimefall) (error "Símbolo desconhecido.")))
             (:par (unless (= (length valor) 3) (error "Par inválido."))
                   (cons (decodificar (second valor)) (decodificar (third valor))))
             (:tabela
              (unless (member (second valor) '(:igual :identico)) (error "Tabela inválida."))
              (let ((tabela (make-hash-table :test (if (eq (second valor) :igual) #'equal #'eql))))
                (dolist (par (third valor)) (setf (gethash (decodificar (first par)) tabela) (decodificar (second par))))
                tabela))
             (:estrutura
              (let* ((tipo (find-symbol (second valor) :rimefall))
                     (construtor (cdr (assoc tipo *estruturas-persistentes*)))
                     (campos (when construtor (campos-estrutura tipo))) (argumentos nil))
                (unless (and construtor (= (length campos) (length (third valor)))) (error "Estrutura incompatível."))
                (loop for campo in campos for par in (third valor)
                      do (unless (string= (symbol-name campo) (first par)) (error "Campo incompatível."))
                         (setf argumentos (append argumentos (list (intern (symbol-name campo) :keyword) (decodificar (second par))))))
                (apply construtor argumentos)))
             (t (error "Formato de dado desconhecido."))))
          (t (error "Valor inválido no salvamento.")))))
(defun rejeitar-despacho (arquivo caractere)
  (declare (ignore arquivo caractere)) (error "Sintaxe de leitor não permitida."))
(defun ler-dados (caminho)
  (let ((*read-eval* nil) (*readtable* (copy-readtable nil)) (*package* (find-package :keyword)))
    ;; Impede #S, #., referências circulares e demais extensões do leitor.
    (set-macro-character #\# #'rejeitar-despacho nil *readtable*)
    (with-open-file (arquivo caminho :external-format :utf-8)
      (when (> (file-length arquivo) 8000000) (error "Arquivo de dados grande demais."))
      (let ((valor (read arquivo)))
        (unless (eq (read arquivo nil :fim) :fim) (error "Dados extras no arquivo.")) valor))))
(defun gravar-dados (caminho dados)
  (ensure-directories-exist caminho)
  (let ((temporario (make-pathname :type "temporario" :defaults caminho)))
    (unwind-protect
         (progn
           (with-open-file (arquivo temporario :direction :output :if-exists :supersede :external-format :utf-8)
             (let ((*print-pretty* nil) (*print-circle* nil) (*print-readably* nil) (*print-escape* t) (*print-level* nil) (*print-length* nil)
                   (*package* (find-package :keyword)))
               (write dados :stream arquivo) (terpri arquivo) (finish-output arquivo)))
           (uiop:rename-file-overwriting-target temporario caminho))
      (when (probe-file temporario) (delete-file temporario)))))
(defun conferir-sessao (sessao)
  (unless (and (sessao-p sessao) (eq (sessao-mapa sessao) :posto-ampliado)
               (member (sessao-fase sessao) '(:notas :combate :pausa :relatorio :derrota :vitoria))
               (<= 0 (sessao-usados sessao) 4) (<= 0 (sessao-onda sessao) 3)
               (not (validar-notas (sessao-notas sessao) (sessao-acervo sessao)))
               (<= 0 (sessao-tempo sessao))
               (member (sessao-clima sessao) '(:calmaria :aviso :rajada))
               (hash-table-p (sessao-explorado sessao)))
    (error "Sessão incompatível ou danificada."))
  (let ((soldado (sessao-soldado sessao)))
    (when (and (member (sessao-fase sessao) '(:combate :pausa))
               (or (not (soldado-p soldado)) (soldado-transferido soldado) (>= (soldado-ferimentos soldado) 2)))
      (error "Estado de vida inconsistente."))
    (when soldado
      (unless (and (<= 0 (soldado-carregador soldado) (capacidade-arma (soldado-arma soldado)))
                   (<= 0 (soldado-reserva-fuzil soldado)) (<= 0 (soldado-reserva-escopeta soldado))
                   (<= 0 (soldado-reserva-carabina soldado)) (<= 0 (soldado-reserva-submetralhadora soldado))
                   (<= 0 (soldado-reserva-precisao soldado)) (<= 0 (soldado-reserva-franco-atirador soldado))
                   (= (soldado-numero soldado) (sessao-usados sessao))) (error "Inventário inconsistente."))))
  sessao)
(defun salvar-sessao (sessao)
  (when (or (not *persistencia-ativa*) *gravacao-bloqueada*) (return-from salvar-sessao nil))
  (handler-case
      (let ((copia (copiar-sessao sessao)))
        (setf (sessao-sons copia) nil)
        (gravar-dados (caminho-sessao) (list :rimefall *versao-salvamento* (codificar-dados copia)))
        (setf *erro-persistencia* nil) t)
    (error (condicao) (setf *erro-persistencia* (format nil "Não foi possível salvar: ~A" condicao)) nil)))
(defun salvar-transicao (sessao)
  (when *persistencia-ativa*
    (unless (salvar-sessao sessao)
      (setf *gravacao-bloqueada* t))
    (setf (sessao-salvamento-em sessao) (+ (sessao-tempo sessao) 5.0))))
(defun salvar-periodicamente (sessao)
  (when (and *persistencia-ativa* (not (eq (sessao-fase sessao) :titulo))
             (>= (sessao-tempo sessao) (sessao-salvamento-em sessao)))
    (setf (sessao-salvamento-em sessao) (+ (sessao-tempo sessao) 5.0))
    (salvar-sessao sessao)))
(defun carregar-sessao ()
  (handler-case
      (let ((dados (ler-dados (caminho-sessao))))
        (unless (and (eq (first dados) :rimefall) (eql (second dados) *versao-salvamento*))
          (error "Versão de salvamento incompatível."))
        (let ((sessao (conferir-sessao (decodificar-dados (third dados)))))
          (when (eq (sessao-fase sessao) :combate) (setf (sessao-fase sessao) :pausa))
          (setf *erro-persistencia* nil *gravacao-bloqueada* nil) sessao))
    (error (condicao)
      (setf *erro-persistencia* (format nil "Não foi possível continuar: ~A" condicao)
            *gravacao-bloqueada* t) nil)))
(defun conferir-configuracao (dados)
  (unless (and (listp dados)
               (<= .0005 (getf dados :sensibilidade) .008)
               (<= 55 (getf dados :visao) 100)
               (member (list (getf dados :largura) (getf dados :altura)) '((1280 720) (1600 900) (1920 1080)) :test #'equal)
               (member (getf dados :neve) '(0 85 170 255))
               (every (lambda (chave) (<= 0 (getf dados chave) 1)) '(:volume :efeitos :ambiente))
               (member (getf dados :tela-cheia) '(nil t)) (member (getf dados :sincronizar) '(nil t))
               (= (length (getf dados :atalhos)) (length *atalhos-padrao*))
               (every (lambda (par) (let ((tecla (cdr (assoc (car par) (getf dados :atalhos)))))
                                     (and (integerp tecla) (<= 32 tecla 348) (not (member tecla '(256 257 258))))))
                      *atalhos-padrao*)
               (= (length (remove-duplicates (mapcar #'cdr (getf dados :atalhos)))) (length *atalhos-padrao*)))
    (error "Preferências inválidas.")) dados)
(defun carregar-configuracao ()
  (when (probe-file (caminho-configuracao))
    (handler-case
        (setf *configuracao* (conferir-configuracao (decodificar-dados (ler-dados (caminho-configuracao)))))
      (error (condicao) (setf *erro-persistencia* (format nil "Preferências não carregadas: ~A" condicao))))))
(defun salvar-configuracao ()
  (handler-case
      (progn (conferir-configuracao *configuracao*)
             (gravar-dados (caminho-configuracao) (codificar-dados *configuracao*)) t)
    (error (condicao) (setf *erro-persistencia* (format nil "Preferências não salvas: ~A" condicao)) nil)))

(defun conferir-guerra (guerra)
  (unless (and (guerra-p guerra) (member (guerra-fase guerra)
                                         '(:preparacao :combate :pausa :vitoria :derrota :empate))
               (<= 0 (guerra-quadro guerra)) (= 5 (length (guerra-setores guerra)))
               (= 2 (length (guerra-exercitos guerra)))
               (every (lambda (j) (member (jogador-guerra-funcao j) *funcoes-guerra*))
                      (guerra-jogadores guerra)))
    (error "Estado de guerra incompatível."))
  guerra)

(defun dados-guerra (guerra)
  "Projeção acíclica do estado: referências são ids, nunca objetos Lisp."
  (list :fase (guerra-fase guerra) :tempo (guerra-tempo guerra) :quadro (guerra-quadro guerra)
        :modo (guerra-modo guerra) :vencedor (guerra-vencedor guerra) :semente (guerra-semente guerra)
        :pressao (guerra-pressao-sonora guerra)
        :setores (mapcar (lambda (setor)
                           (list (setor-guerra-id setor) (setor-guerra-dono setor)
                                 (setor-guerra-progresso setor) (setor-guerra-contestacao setor)))
                         (guerra-setores guerra))
        :exercitos (mapcar (lambda (exercito)
                             (list (exercito-id exercito) (exercito-reforcos exercito)
                                   (quartel-general-vida (exercito-quartel-general exercito))
                                   (exercito-ordem exercito))) (guerra-exercitos guerra))
        :jogadores (mapcar (lambda (jogador)
                             (list (jogador-guerra-id jogador) (jogador-guerra-estado jogador)
                                   (jogador-guerra-x jogador) (jogador-guerra-z jogador)
                                   (jogador-guerra-funcao jogador) (jogador-guerra-municao jogador)
                                   (jogador-guerra-eliminacoes jogador) (jogador-guerra-supressao jogador)))
                         (guerra-jogadores guerra))))

(defun aplicar-dados-guerra (guerra dados)
  (setf (guerra-fase guerra) (getf dados :fase)
        (guerra-tempo guerra) (getf dados :tempo)
        (guerra-quadro guerra) (getf dados :quadro)
        (guerra-modo guerra) (getf dados :modo)
        (guerra-vencedor guerra) (getf dados :vencedor)
        (guerra-semente guerra) (getf dados :semente)
        (guerra-pressao-sonora guerra) (getf dados :pressao))
  (dolist (registro (getf dados :setores))
    (let ((setor (find (first registro) (guerra-setores guerra) :key #'setor-guerra-id)))
      (when setor (setf (setor-guerra-dono setor) (second registro)
                        (setor-guerra-progresso setor) (third registro)
                        (setor-guerra-contestacao setor) (fourth registro)))))
  (dolist (registro (getf dados :exercitos))
    (let ((exercito (localizar-exercito-guerra guerra (first registro))))
      (when exercito (setf (exercito-reforcos exercito) (second registro)
                           (quartel-general-vida (exercito-quartel-general exercito)) (third registro)
                           (exercito-ordem exercito) (fourth registro)))))
  (dolist (registro (getf dados :jogadores))
    (let ((jogador (localizar-jogador-guerra guerra (first registro))))
      (when jogador (setf (jogador-guerra-estado jogador) (second registro)
                          (jogador-guerra-x jogador) (third registro)
                          (jogador-guerra-z jogador) (fourth registro)
                          (jogador-guerra-funcao jogador) (fifth registro)
                          (jogador-guerra-municao jogador) (sixth registro)
                          (jogador-guerra-eliminacoes jogador) (seventh registro)
                          (jogador-guerra-supressao jogador) (or (eighth registro) 0.0)))))
  (conferir-guerra guerra))

(defun gravar-guerra (guerra caminho)
  "Salva estado acíclico da batalha com o leitor seguro."
  (gravar-dados caminho (list :rimefall-guerra 1 (codificar-dados (dados-guerra (conferir-guerra guerra))))))

(defun carregar-guerra (caminho)
  (let* ((dados (ler-dados caminho)))
    (unless (and (eq (first dados) :rimefall-guerra) (eql (second dados) 1))
      (error "Versão de guerra incompatível."))
    (let* ((estado (decodificar-dados (third dados)))
           (jogadores (getf estado :jogadores))
           (por-lado (max 1 (floor (length jogadores) 2))))
      (aplicar-dados-guerra (criar-guerra-offline :jogadores-por-lado por-lado) estado))))
