(in-package #:rimefall)

(defun nova-sessao ()
  (let ((sessao (%criar-sessao))) (montar-mapa sessao) sessao))

(defun confirmar-notas (sessao)
  (when *gravacao-bloqueada* (return-from confirmar-notas nil))
  (unless (eq (sessao-fase sessao) :notas) (return-from confirmar-notas nil))
  (let ((erro (validar-notas (sessao-notas sessao) (sessao-acervo sessao))))
    (when erro (avisar sessao erro) (return-from confirmar-notas nil)))
  (when (>= (sessao-usados sessao) 4) (return-from confirmar-notas nil))
  (let* ((notas (sessao-notas sessao)) (arma (notas-arma notas))
         (soldado (criar-soldado :numero (incf (sessao-usados sessao)) :arma arma
                                 :carregador (capacidade-arma arma)
                                 :reserva-fuzil (if (eq arma :fuzil) 8 0)
                                 :reserva-escopeta (if (eq arma :escopeta) 6 0)
                                 :reserva-carabina (if (eq arma :carabina) 16 0)
                                 :reserva-submetralhadora (if (eq arma :submetralhadora) 20 0)
                                 :reserva-precisao (if (eq arma :precisao) 10 0)
                                 :reserva-franco-atirador (if (eq arma :franco-atirador) 5 0)
                                 :iscas (if (eq (notas-preparo notas) :distracao) 4 2)
                                 :preparo (notas-preparo notas))))
    (setf (soldado-nome soldado) (first (nth (1- (soldado-numero soldado)) *identidades*))
          (soldado-origem soldado) (second (nth (1- (soldado-numero soldado)) *identidades*)))
    (setf (sessao-soldado sessao) soldado (sessao-fase sessao) :combate)
    (when (zerop (sessao-onda sessao)) (iniciar-onda sessao))
    (salvar-transicao sessao)
    t))

(defun encerrar-vida (sessao)
  "A transição é idempotente: um corpo, um relatório e uma transmissão por vida."
  (let ((soldado (sessao-soldado sessao)))
    (when (or (null soldado) (soldado-transferido soldado)) (return-from encerrar-vida nil))
    (setf (soldado-ferimentos soldado) 2 (soldado-transferido soldado) t)
    (incorporar-evidencias (sessao-acervo sessao) (reverse (soldado-aprendizados soldado)))
    (maphash (lambda (celula conhecido) (setf (gethash celula (sessao-explorado sessao)) conhecido))
             (soldado-explorado soldado))
    (push (list :nome (soldado-nome soldado) :origem (soldado-origem soldado)
                :causa (soldado-causa soldado) :onda (sessao-onda sessao) :soldado (soldado-numero soldado) :instante (sessao-tempo sessao)
                :eliminacoes (soldado-eliminacoes soldado)
                :evidencias (reverse (soldado-aprendizados soldado))
                :diario (copy-seq (notas-texto (sessao-notas sessao)))) (sessao-historico sessao))
    (push (criar-suprimento :x (soldado-x soldado) :z (soldado-z soldado)
                           :arma (soldado-arma soldado) :corpo (soldado-numero soldado)
                           :fuzil (+ (soldado-reserva-fuzil soldado)
                                     (if (eq (soldado-arma soldado) :fuzil) (soldado-carregador soldado) 0))
                           :escopeta (+ (soldado-reserva-escopeta soldado)
                                        (if (eq (soldado-arma soldado) :escopeta) (soldado-carregador soldado) 0))
                           :carabina (municao-no-corpo soldado :carabina)
                           :submetralhadora (municao-no-corpo soldado :submetralhadora)
                           :precisao (municao-no-corpo soldado :precisao)
                           :franco-atirador (municao-no-corpo soldado :franco-atirador)
                           :iscas (soldado-iscas soldado)
                           :equipamento (unless (and (eq (soldado-equipamento soldado) :temporizador)
                                                     (dispositivo-do-soldado sessao))
                                          (soldado-equipamento soldado))) (sessao-suprimentos sessao))
    (setf (sessao-fase sessao) (if (= (sessao-usados sessao) 4) :derrota :relatorio))
    (when (and (member (soldado-preparo soldado) '(:temporizador :bipé))
               (not (and (eq (soldado-preparo soldado) :temporizador) (dispositivo-do-soldado sessao))))
      (push (criar-suprimento :x (soldado-x soldado) :z (soldado-z soldado)
                             :equipamento (soldado-preparo soldado)) (sessao-suprimentos sessao)))
    (salvar-transicao sessao)
    t))

(defun abrir-notas (sessao)
  (when (eq (sessao-fase sessao) :relatorio) (setf (sessao-fase sessao) :notas) (salvar-transicao sessao)))

(defun iniciar-jogo (&rest opcoes)
  "Abre a demo. As opções de validação são descritas em README.md."
  (unless (fboundp 'executar-apresentacao) (asdf:load-system "rimefall"))
  (apply (symbol-function 'executar-apresentacao) opcoes))
