(in-package #:rimefall)

(defvar *verificacoes* 0)
(defmacro verificar (condicao &optional (descricao "Condição esperada não satisfeita."))
  `(progn (incf *verificacoes*) (unless ,condicao (error "~A: ~S" ,descricao ',condicao))))
(defun sessao-em-combate () (let ((sessao (nova-sessao))) (confirmar-notas sessao) sessao))
(defun avancar-tempo (sessao segundos)
  (dotimes (passo (ceiling (/ segundos *passo-fixo*))) (atualizar-campo sessao *passo-fixo*)))

(defun testar-notas-e-transmissao ()
  (let* ((sessao (sessao-em-combate)) (soldado (sessao-soldado sessao))
         (notas (sessao-notas sessao)) (inimigos (sessao-inimigos sessao)))
    (setf (notas-arma notas) :escopeta)
    (verificar (validar-notas notas (sessao-acervo sessao)))
    (setf (notas-arma notas) :fuzil (notas-preparo notas) '(:silencio :distracao))
    (verificar (validar-notas notas (sessao-acervo sessao)))
    (setf (notas-preparo notas) nil)
    (registrar-aprendizado sessao :escopeta "Eliminação com arma encontrada.")
    (verificar (null (gethash :escopeta (sessao-acervo sessao))))
    (encerrar-vida sessao)
    (verificar (eq (sessao-fase sessao) :relatorio))
    (verificar (gethash :escopeta (sessao-acervo sessao)))
    (verificar (= (length (sessao-historico sessao)) 1))
    (let ((corpos (length (sessao-suprimentos sessao))) (tempo (sessao-tempo sessao)))
      (encerrar-vida sessao) (avancar-tempo sessao 1.0)
      (verificar (= tempo (sessao-tempo sessao)))
      (verificar (= corpos (length (sessao-suprimentos sessao)))))
    (abrir-notas sessao)
    (setf (notas-arma notas) :escopeta (notas-texto notas) "Fuzil infinito. Vida eterna. Silêncio total.")
    (verificar (confirmar-notas sessao))
    (verificar (not (eq soldado (sessao-soldado sessao))))
    (verificar (eq inimigos (sessao-inimigos sessao)))
    (verificar (= (sessao-onda sessao) 1))
    (verificar (= (soldado-carregador (sessao-soldado sessao)) 2))
    (verificar (= (soldado-iscas (sessao-soldado sessao)) 2))
    (verificar (null (soldado-preparo (sessao-soldado sessao))))
    (registrar-aprendizado sessao :escopeta "Outra vida, outro êxito.")
    (encerrar-vida sessao)
    (verificar (= (length (gethash :escopeta (sessao-acervo sessao))) 2))
    (abrir-notas sessao) (confirmar-notas sessao) (encerrar-vida sessao)
    (abrir-notas sessao) (confirmar-notas sessao)
    (registrar-aprendizado sessao :silencio "Última descoberta.")
    (encerrar-vida sessao)
    (verificar (eq (sessao-fase sessao) :derrota))
    (verificar (gethash :silencio (sessao-acervo sessao)))
    (verificar (not (confirmar-notas sessao)))
    (verificar (= (sessao-usados sessao) 4))
    (let ((nova (nova-sessao)))
      (verificar (= (hash-table-count (sessao-acervo nova)) 1))
      (verificar (string= "" (notas-texto (sessao-notas nova)))))))

(defun testar-audicao ()
  (let* ((sessao (sessao-em-combate)) (soldado (sessao-soldado sessao))
         (inimigo (criar-inimigo :x 0.0 :z 4.0 :alvo-x 0.0 :alvo-z 4.0)))
    (setf (sessao-obstaculos sessao) nil (sessao-inimigos sessao) (list inimigo)
          (soldado-x soldado) 0.0 (soldado-z soldado) 0.0)
    (atualizar-inimigo sessao inimigo 0.01)
    (verificar (eq (inimigo-estado inimigo) :patrulha) "Visão não deve adquirir alvos")
    (emitir-ruido sessao 0.0 0.0 12.0 :passo 1)
    (verificar (eq (inimigo-estado inimigo) :investigar))
    (setf (soldado-x soldado) 12.0)
    (verificar (= (inimigo-alvo-x inimigo) 0.0) "Memória não acompanha posição atual")
    (avancar-tempo sessao 10.0)
    (verificar (find :silencio (soldado-aprendizados soldado) :key #'evidencia-conhecimento))
    (verificar (eq (inimigo-estado inimigo) :patrulha))
    (emitir-ruido sessao 12.0 0.0 40.0 :fuzil 1)
    (emitir-ruido sessao -4.0 0.0 40.0 :isca 1)
    (verificar (= (inimigo-alvo-x inimigo) -4.0))
    (verificar (find :distracao (soldado-aprendizados soldado) :key #'evidencia-conhecimento))
    (verificar (null (gethash :distracao (sessao-acervo sessao)))))
  (let* ((sessao (sessao-em-combate)) (inimigo (criar-inimigo :x 8.0 :z 0.0)))
    (setf (sessao-inimigos sessao) (list inimigo)
          (sessao-obstaculos sessao) (list (criar-obstaculo :x 4.0 :z 0.0 :largura 1.0 :profundidade 5.0 :altura 3.0)))
    (emitir-ruido sessao 0.0 0.0 10.0 :passo 1)
    (verificar (eq (inimigo-estado inimigo) :patrulha) "Parede deve atenuar som")
    (emitir-ruido sessao 0.0 0.0 30.0 :fuzil 1)
    (verificar (eq (inimigo-estado inimigo) :investigar)))
  (let* ((sessao (sessao-em-combate)) (inimigo (criar-inimigo :x 0.0 :z 0.0)))
    (setf (sessao-inimigos sessao) (list inimigo) (sessao-obstaculos sessao) nil)
    (emitir-ruido sessao 1.0 0.0 20.0 :isca 1)
    (verificar (null (soldado-aprendizados (sessao-soldado sessao))) "Isca sem perseguição não ensina")))

(defun testar-combate-e-recuperacao ()
  (let* ((sessao (sessao-em-combate)) (soldado (sessao-soldado sessao)))
    (setf (soldado-x soldado) 3.0 (soldado-z soldado) 18.0)
    (verificar (recolher sessao))
    (verificar (eq (soldado-arma soldado) :escopeta))
    (verificar (= (soldado-reserva-escopeta soldado) 8))
    (verificar (null (soldado-aprendizados soldado)))
    (iniciar-recarga sessao) (avancar-tempo sessao 3.0)
    (verificar (= (soldado-carregador soldado) 2))
    (verificar (= (soldado-reserva-escopeta soldado) 6))
    (setf (sessao-obstaculos sessao) nil
          (sessao-inimigos sessao) (list (criar-inimigo :x 3.0 :z 12.0))
          (soldado-inclinacao soldado) (atan -0.65 6.0))
    (disparar sessao)
    (verificar (notany #'vivo-p (sessao-inimigos sessao)))
    (verificar (find :escopeta (soldado-aprendizados soldado) :key #'evidencia-conhecimento))
    (encerrar-vida sessao) (abrir-notas sessao) (confirmar-notas sessao)
    (let ((novo (sessao-soldado sessao)) (corpo (first (sessao-suprimentos sessao))))
      (setf (soldado-x novo) 3.0 (soldado-z novo) 18.0)
      (verificar (recolher sessao))
      (verificar (suprimento-retirado corpo))
      (verificar (= (soldado-reserva-escopeta novo) 7))
      (let ((total (soldado-reserva-escopeta novo)))
        (recolher sessao)
        (verificar (= total (soldado-reserva-escopeta novo)) "Corpo não duplica munição"))))
  (let* ((sessao (sessao-em-combate)) (soldado (sessao-soldado sessao))
         (inimigo (criar-inimigo :x 0.0 :z 22.0)))
    (setf (sessao-inimigos sessao) (list inimigo))
    (avancar-tempo sessao 0.7)
    (verificar (zerop (soldado-ferimentos soldado)) "Ataque deve avisar antes de acertar")
    (avancar-tempo sessao 0.3)
    (verificar (= (soldado-ferimentos soldado) 1))
    (avancar-tempo sessao 3.0)
    (verificar (eq (sessao-fase sessao) :relatorio))))

(defun testar-colisoes-e-ondas ()
  (let ((sessao (sessao-em-combate)))
    (verificar (bloqueado-p sessao -5.0 23.0))
    (verificar (not (bloqueado-p sessao 0.0 18.0)))
    (verificar (calcular-rota sessao -24.0 -18.0 0.0 23.0))
    (verificar (calcular-rota sessao -24.0 -18.0 2.55 13.0)
               "Um ruído junto da quina não pode tornar o destino inalcançável")
    (dotimes (onda 3)
      (verificar (= (length (sessao-inimigos sessao)) (nth onda *composicao-ondas*)))
      (dolist (inimigo (sessao-inimigos sessao)) (setf (inimigo-vida inimigo) 0))
      (avancar-tempo sessao 8.2))
    (verificar (eq (sessao-fase sessao) :vitoria))))

(defun executar-testes ()
  (let ((*verificacoes* 0))
    (testar-notas-e-transmissao) (testar-audicao)
    (testar-combate-e-recuperacao) (testar-colisoes-e-ondas)
    (testar-expansao-combate) (testar-clima-e-portas) (testar-chamador-e-dispositivo)
    (testar-exploracao) (testar-persistencia) (testar-novas-armas-e-mapa) (testar-cone-optico)
    (format t "~&~D verificações concluídas sem falhas.~%" *verificacoes*) t))

(defun testar-expansao-combate ()
  (let* ((sessao (sessao-em-combate)) (soldado (sessao-soldado sessao)))
    (setf (sessao-inimigos sessao) (list (criar-inimigo :x 26.0 :z -26.0))
          (soldado-carregador soldado) 0 (soldado-reserva-fuzil soldado) 4)
    (iniciar-recarga sessao)
    (avancar-tempo sessao .4)
    (verificar (zerop (soldado-carregador soldado)))
    (verificar (not (disparar sessao)))
    (avancar-tempo sessao .5)
    (verificar (= (soldado-carregador soldado) 1))
    (verificar (= (soldado-reserva-fuzil soldado) 3))
    (verificar (plusp (soldado-recarga soldado)))
    (verificar (disparar sessao))
    (verificar (zerop (soldado-recarga soldado)))
    (verificar (not (disparar sessao)))
    (verificar (= (soldado-reserva-fuzil soldado) 3))
    (avancar-tempo sessao 1.2)
    (setf (soldado-carregador soldado) 4 (soldado-agachado soldado) t (soldado-equipamento soldado) :bipé
          (soldado-x soldado) 0.0 (soldado-z soldado) 5.0 (sessao-obstaculos sessao) nil
          (sessao-inimigos sessao) (list (criar-inimigo :x 0.0 :z 0.0))
          (soldado-inclinacao soldado) 0.0)
    (verificar (eq (apoiar-arma sessao) :bipé))
    (disparar sessao)
    (verificar (find :bipé (soldado-aprendizados soldado) :key #'evidencia-conhecimento))
    (verificar (not (gethash :bipé (sessao-acervo sessao))))
    (mover-soldado sessao 1.0 0.0 .1)
    (verificar (null (soldado-apoiado soldado)))
    (apoiar-arma sessao) (iniciar-recarga sessao)
    (verificar (null (soldado-apoiado soldado))))
  (let* ((sessao (sessao-em-combate)) (soldado (sessao-soldado sessao)))
    (setf (soldado-x soldado) -9.0 (soldado-z soldado) 14.0)
    (verificar (eq (apoiar-arma sessao) :cobertura))
    (setf (soldado-x soldado) 0.0 (soldado-z soldado) 23.0 (soldado-apoiado soldado) nil)
    (verificar (null (apoiar-arma sessao)))))

(defun testar-clima-e-portas ()
  (let* ((sessao (sessao-em-combate)) (soldado (sessao-soldado sessao)))
    (verificar (= (fator-passos sessao) 1.25))
    (setf (soldado-x soldado) 0.0 (soldado-z soldado) 6.0)
    (verificar (= (fator-passos sessao) 1.8))
    (setf (sessao-tempo-clima sessao) .01)
    (atualizar-clima sessao .02)
    (verificar (eq (sessao-clima sessao) :aviso))
    (verificar (= (sessao-tempo-clima sessao) 4.0))
    (atualizar-clima sessao 4.0)
    (verificar (eq (sessao-clima sessao) :rajada))
    (verificar (= (fator-passos sessao) .9))
    (verificar (< (distancia-visivel sessao) *fim-neblina*))
    (setf (sessao-fase sessao) :pausa)
    (avancar-tempo sessao 2.0)
    (verificar (= (sessao-tempo-clima sessao) 10.0))
    (setf (sessao-fase sessao) :combate)
    (atualizar-clima sessao 10.0)
    (verificar (<= 30 (sessao-tempo-clima sessao) 45))
    (verificar (eq (sessao-clima sessao) :calmaria))
    (setf (soldado-x soldado) -19.0 (soldado-z soldado) 15.0)
    (verificar-gelo sessao 0.0)
    (verificar (null (sessao-gelo-partido sessao)))
    (verificar-gelo sessao .1)
    (verificar (= (length (sessao-gelo-partido sessao)) 1))
    (let ((sons (length (sessao-sons sessao))))
      (verificar-gelo sessao .2) (verificar (= sons (length (sessao-sons sessao)))))
    (setf (soldado-x soldado) 0.0 (soldado-z soldado) 15.0)
    (verificar (bloqueado-p sessao 0.0 13.0))
    (verificar (interagir-porta sessao))
    (verificar (not (bloqueado-p sessao 0.0 13.0)))
    (verificar (passagem-livre-p sessao 0.0 15.0 0.0 11.0))
    (setf (soldado-z soldado) 13.0)
    (interagir-porta sessao)
    (verificar (not (bloqueado-p sessao 0.0 13.0)) "Não esmagar o soldado ao fechar")
    (setf (soldado-z soldado) 15.0)
    (interagir-porta sessao)
    (verificar (bloqueado-p sessao 0.0 13.0))
    (let ((inimigo (criar-inimigo :x 0.0 :z 11.0)))
      (setf (sessao-inimigos sessao) (list inimigo))
      (emitir-ruido sessao 0.0 15.0 5.0 :passo 1)
      (verificar (eq (inimigo-estado inimigo) :patrulha))
      (interagir-porta sessao)
      (setf (inimigo-estado inimigo) :patrulha)
      (emitir-ruido sessao 0.0 15.0 5.0 :passo 1)
      (verificar (eq (inimigo-estado inimigo) :investigar)))))

(defun testar-chamador-e-dispositivo ()
  (let* ((sessao (sessao-em-combate)) (soldado (sessao-soldado sessao))
         (chamador (criar-inimigo :tipo :chamador :x 0.0 :z 22.0))
         (vizinho (criar-inimigo :x 3.0 :z 22.0)))
    (setf (sessao-inimigos sessao) (list chamador vizinho) (sessao-obstaculos sessao) nil)
    (atualizar-inimigo sessao chamador .01)
    (verificar (= (inimigo-chamado chamador) 2.0))
    (verificar (eq (inimigo-estado vizinho) :patrulha))
    (setf (soldado-x soldado) 12.0)
    (atualizar-inimigo sessao chamador 2.01)
    (verificar (= (inimigo-alvo-x vizinho) 0.0))
    (verificar (= (inimigo-alvo-z vizinho) 22.0))
    (verificar (null (inimigo-rastreado vizinho)))
    (setf (inimigo-chamou chamador) nil (soldado-x soldado) 0.0)
    (atualizar-inimigo sessao chamador .01)
    (setf (inimigo-vida chamador) 0 (inimigo-estado vizinho) :patrulha)
    (avancar-tempo sessao 2.1)
    (verificar (eq (inimigo-estado vizinho) :patrulha) "Morte interrompe o chamado"))
  (let* ((sessao (sessao-em-combate)) (soldado (sessao-soldado sessao))
         (inimigo (criar-inimigo :x 0.0 :z 3.0)))
    (setf (sessao-obstaculos sessao) nil (sessao-inimigos sessao) (list inimigo)
          (soldado-x soldado) 0.0 (soldado-z soldado) 0.0)
    (verificar (not (colocar-dispositivo sessao)))
    (guardar-equipamento sessao :temporizador)
    (verificar (colocar-dispositivo sessao))
    (verificar (not (colocar-dispositivo sessao)))
    (verificar (not (guardar-equipamento sessao :bipé)))
    (atualizar-dispositivos sessao 2.9)
    (verificar (eq (inimigo-estado inimigo) :patrulha))
    (setf (soldado-x soldado) 8.0)
    (emitir-ruido sessao 8.0 0.0 30.0 :fuzil 1)
    (atualizar-dispositivos sessao .2)
    (verificar (= (inimigo-alvo-x inimigo) 0.0))
    (verificar (find :temporizador (soldado-aprendizados soldado) :key #'evidencia-conhecimento))
    (verificar (not (gethash :temporizador (sessao-acervo sessao))))
    (encerrar-vida sessao)
    (verificar (gethash :temporizador (sessao-acervo sessao)))
    (verificar (notany (lambda (item) (eq (suprimento-equipamento item) :temporizador))
                       (remove-if-not #'suprimento-corpo (sessao-suprimentos sessao))))
    (abrir-notas sessao) (confirmar-notas sessao)
    (setf (soldado-x (sessao-soldado sessao)) 0.0 (soldado-z (sessao-soldado sessao)) 0.0)
    (verificar (recuperar-dispositivo sessao))
    (verificar (null (sessao-dispositivos sessao)))
    (verificar (eq (soldado-equipamento (sessao-soldado sessao)) :temporizador))
    (verificar (not (guardar-equipamento sessao :temporizador)))
    (verificar (guardar-equipamento sessao :bipé))
    (verificar (eq (suprimento-equipamento (first (sessao-suprimentos sessao))) :temporizador))))

(defun testar-exploracao ()
  (let* ((sessao (sessao-em-combate)) (soldado (sessao-soldado sessao)))
    (explorar-campo sessao)
    (verificar (plusp (hash-table-count (soldado-explorado soldado))))
    (verificar (zerop (hash-table-count (sessao-explorado sessao))))
    (verificar (not (visivel-p sessao 0.0 28.0)))
    (verificar (not (adicionar-marca sessao 0 11 "Não disponível em combate")))
    (let ((celula (loop for chave being the hash-keys of (soldado-explorado soldado) return chave)))
      (encerrar-vida sessao)
      (verificar (gethash celula (sessao-explorado sessao)))
      (let ((total (hash-table-count (sessao-explorado sessao))))
        (encerrar-vida sessao) (verificar (= total (hash-table-count (sessao-explorado sessao)))))
      (abrir-notas sessao)
      (verificar (adicionar-marca sessao (car celula) (cdr celula) "Silêncio no abrigo"))
      (verificar (= (length (sessao-marcas sessao)) 1))
      (verificar (not (adicionar-marca sessao -14 -14 "Local desconhecido")))
      (confirmar-notas sessao)
      (verificar (zerop (hash-table-count (soldado-explorado (sessao-soldado sessao))))))
    (verificar (string= (soldado-nome (sessao-soldado sessao)) "Lúcia Reis"))))

(defun testar-persistencia ()
  (let* ((*pasta-dados* (merge-pathnames (format nil "rimefall-testes-~D/" (get-internal-real-time)) (uiop:temporary-directory)))
         (*pasta-configuracao* *pasta-dados*) (*persistencia-ativa* t) (*gravacao-bloqueada* nil)
         (*erro-persistencia* nil) (*configuracao* (configuracao-padrao))
         (sessao (sessao-em-combate)) (soldado (sessao-soldado sessao)))
    (unwind-protect
         (progn
           (setf (soldado-carregador soldado) 1 (soldado-equipamento soldado) :temporizador
                 (sessao-clima sessao) :rajada (sessao-tempo-clima sessao) 6.4)
           (colocar-dispositivo sessao) (atualizar-dispositivos sessao 1.2)
           (iniciar-recarga sessao) (explorar-campo sessao)
           (setf (notas-texto (sessao-notas sessao)) "Memória: ação, coração, silêncio.")
           (verificar (salvar-sessao sessao))
           (let* ((carregada (carregar-sessao)) (novo (sessao-soldado carregada)))
             (verificar (eq (sessao-fase carregada) :pausa))
             (verificar (= (soldado-recarga novo) (soldado-recarga soldado)))
             (verificar (= (sessao-tempo-clima carregada) 6.4))
             (verificar (= (dispositivo-tempo (first (sessao-dispositivos carregada))) 1.2))
             (verificar (string= (notas-texto (sessao-notas carregada)) (notas-texto (sessao-notas sessao))))
             (verificar (equalp (codificar-dados (sessao-inimigos carregada)) (codificar-dados (sessao-inimigos sessao))))
             (avancar-tempo carregada 5.0)
             (verificar (= (sessao-tempo-clima carregada) 6.4)))
           (encerrar-vida sessao)
           (let ((carregada (carregar-sessao)))
             (verificar (eq (sessao-fase carregada) :relatorio))
             (verificar (soldado-transferido (sessao-soldado carregada)))
             (verificar (= (length (sessao-historico carregada)) 1))
             (verificar (plusp (hash-table-count (sessao-explorado carregada))))
             (encerrar-vida carregada)
             (verificar (= (length (sessao-historico carregada)) 1)))
           (setf (getf *configuracao* :volume) .3 (getf *configuracao* :visao) 85)
           (verificar (salvar-configuracao))
           (setf *configuracao* (configuracao-padrao))
           (carregar-configuracao)
           (verificar (= (getf *configuracao* :volume) .3))
           (verificar (= (getf *configuracao* :visao) 85))
           (verificar (= (fator-passos sessao) .625))
           (let ((nova (nova-sessao)))
             (verificar (zerop (hash-table-count (sessao-explorado nova))))
             (verificar (null (sessao-marcas nova)))
             (verificar (= (getf *configuracao* :visao) 85)))
           (with-open-file (arquivo (caminho-sessao) :direction :output :if-exists :supersede)
             (write-string "#.(error \"Não executar\")" arquivo))
           (verificar (null (carregar-sessao)))
           (verificar *gravacao-bloqueada*)
           (verificar (not (salvar-sessao sessao)))
           (verificar (search "#." (uiop:read-file-string (caminho-sessao))))
           (setf *gravacao-bloqueada* nil)
           (gravar-dados (caminho-sessao) '(:rimefall 99 nil))
           (verificar (null (carregar-sessao))))
      (uiop:delete-directory-tree *pasta-dados* :validate t :if-does-not-exist :ignore))))

(defun testar-cone-optico ()
  (let ((soldado (criar-soldado :x 0.0 :z 0.0 :arma :franco-atirador)))
    (verificar (terreno-no-cone-p soldado 4.0 -20.0))
    (setf (soldado-mirando soldado) t)
    (verificar (not (terreno-no-cone-p soldado 4.0 -20.0)))
    (verificar (terreno-no-cone-p soldado 0.0 -20.0))
    (setf (soldado-inclinacao soldado) 1.0)
    (verificar (not (terreno-no-cone-p soldado 0.0 -20.0)))))

(defun testar-novas-armas-e-mapa ()
  (dolist (arma '(:carabina :submetralhadora :precisao :franco-atirador))
    (let* ((sessao (sessao-em-combate)) (soldado (sessao-soldado sessao))
           (item (find arma (sessao-suprimentos sessao) :key #'suprimento-arma)))
      (verificar item)
      (setf (notas-arma (sessao-notas sessao)) arma)
      (verificar (validar-notas (sessao-notas sessao) (sessao-acervo sessao)))
      (setf (notas-arma (sessao-notas sessao)) :fuzil
            (soldado-x soldado) (suprimento-x item) (soldado-z soldado) (suprimento-z item))
      (verificar (recolher sessao))
      (verificar (eq (soldado-arma soldado) arma))
      (verificar (zerop (soldado-carregador soldado)))
      (iniciar-recarga sessao)
      (avancar-tempo sessao .3)
      (verificar (not (disparar sessao)))
      (avancar-tempo sessao (if (eq arma :submetralhadora) 3.0 (+ .2 (* (capacidade-arma arma) (duracao-recarga arma)))))
      (verificar (= (soldado-carregador soldado) (capacidade-arma arma)))
      (setf (sessao-obstaculos sessao) nil (sessao-inimigos sessao) (list (criar-inimigo :x 0.0 :z -6.0))
            (soldado-x soldado) 0.0 (soldado-z soldado) 0.0 (soldado-mirando soldado) t
            (soldado-inclinacao soldado) (atan -.65 6.0))
      (let ((antes (soldado-carregador soldado)))
        (disparar sessao)
        (verificar (= (soldado-carregador soldado) (1- antes)))
        (verificar (if (eq arma :franco-atirador) (not (vivo-p (first (sessao-inimigos sessao)))) (vivo-p (first (sessao-inimigos sessao)))))
        (dotimes (passo 70)
          (setf (soldado-inclinacao soldado) (atan -.65 6.0))
          (atualizar-campo sessao *passo-fixo* :gatilho t))
        (if (not (eq arma :submetralhadora))
            (progn
              (verificar (= (soldado-carregador soldado) (1- antes)) "Carabina exige novo clique")
              (disparar sessao))
            (verificar (< (soldado-carregador soldado) (- antes 3)) "Submetralhadora dispara ao manter o gatilho")))
      (verificar (notany #'vivo-p (sessao-inimigos sessao)))
      (verificar (find arma (soldado-aprendizados soldado) :key #'evidencia-conhecimento))
      (let ((total (municao-no-corpo soldado arma)))
        (encerrar-vida sessao)
        (verificar (gethash arma (sessao-acervo sessao)))
        (let ((corpo (find-if #'suprimento-corpo (sessao-suprimentos sessao))))
          (verificar (= (slot-value corpo (intern (symbol-name arma) :rimefall)) total))))
      (abrir-notas sessao)
      (setf (notas-arma (sessao-notas sessao)) arma)
      (verificar (confirmar-notas sessao))
      (verificar (= (soldado-carregador (sessao-soldado sessao)) (capacidade-arma arma)))
      (verificar (= (reserva-arma (sessao-soldado sessao)) (third (dados-arma arma))))))
  (let ((sessao (sessao-em-combate)))
    (verificar (not (bloqueado-p sessao 35.0 -35.0)))
    (verificar (bloqueado-p sessao 42.0 0.0))
    (verificar (calcular-rota sessao 0.0 23.0 -24.0 -32.0))
    (verificar (calcular-rota sessao 0.0 23.0 25.0 -32.0))
    (verificar (calcular-rota sessao -37.0 -28.0 0.0 23.0))
    (verificar (calcular-rota sessao 37.0 -28.0 0.0 23.0))))
