;;; Ensaio determinístico sem janela: dois exércitos e invasões durante dez minutos.
(require :asdf)
(asdf:load-asd (merge-pathnames "rimefall.asd" *load-truename*))
(asdf:load-system "rimefall/nucleo")
(in-package #:rimefall)
(let ((guerra (criar-guerra-offline)) (inicio (get-internal-real-time)))
  (setf (jogador-guerra-bot-p (jogador-local-guerra guerra)) t)
  (criar-logistica-guerra guerra)
  (dotimes (quadro 36000)
    (atualizar-guerra guerra *passo-fixo*)
    (atualizar-invasao-guerra guerra *passo-fixo*)
    (when (zerop (mod quadro 3600))
      (format t "~&Quadro ~D / baixas ~D / setores ~S / reservas ~S~%"
              quadro (length (guerra-historico guerra))
              (mapcar #'setor-guerra-dono (guerra-setores guerra))
              (mapcar #'exercito-reforcos (guerra-exercitos guerra)))))
  (format t "~&Resultado ~A / vencedor ~A / ~,2F s reais~%" (guerra-fase guerra) (guerra-vencedor guerra)
          (/ (- (get-internal-real-time) inicio) internal-time-units-per-second))
  (assert (plusp (length (guerra-historico guerra))))
  (assert (some (lambda (j) (> (jogador-guerra-geracao j) 1)) (guerra-jogadores guerra))))
