;;; Verificação da animação visual, sem alterar a simulação determinística.
(require :asdf)
(load (merge-pathnames "quicklisp/setup.lisp" (user-homedir-pathname)))
(asdf:load-asd (merge-pathnames "../rimefall.asd" *load-truename*))
(asdf:load-system "rimefall")
(in-package #:rimefall)

(defun verificar-transicao-mira ()
  (dolist (frequencia '(30 60 144))
    (let ((progresso 0.0) (anterior 0.0))
      (dotimes (quadro (ceiling (* .30 frequencia)))
        (setf progresso (avancar-mira progresso t (/ 1.0 frequencia)))
        (assert (<= anterior progresso 1.0))
        (setf anterior progresso))
      (assert (< (abs (- progresso 1.0)) .00001))
      (dotimes (quadro (ceiling (* .22 frequencia)))
        (setf progresso (avancar-mira progresso nil (/ 1.0 frequencia))))
      (assert (< progresso .00001))))
  (assert (< 0.0 (suavizar-mira (avancar-mira 0.0 t (/ 1.0 60))) .05))
  (assert (= (avancar-mira .4 nil 0.0) .4))
  (let* ((entrada (avancar-mira 0.0 t .15))
         (saida (avancar-mira entrada nil .016))
         (retorno (avancar-mira saida t .016)))
    (assert (< 0.0 saida entrada 1.0))
    (assert (< saida retorno 1.0)))
  (assert (= (campo-visao-mira 72 0.0 :fuzil t) 72.0))
  (assert (= (campo-visao-mira 72 1.0 :fuzil t) 48.0))
  (assert (= (campo-visao-mira 72 .5 :fuzil t) 60.0))
  (let* ((*guerra-atual* (criar-guerra-offline :jogadores-por-lado 8))
         (j (jogador-local-guerra *guerra-atual*))
         (soldado (criar-soldado :mirando t))
         (sessao (%criar-sessao :fase :guerra :soldado soldado)))
    ;; Um soldado remanescente do tutorial não pode controlar a câmera da guerra.
    (assert (not (mira-solicitada-p sessao)))
    (setf (jogador-guerra-mirando j) t)
    (assert (mira-solicitada-p sessao))
    (setf (jogador-guerra-tempo-recarga j) 2.6)
    (assert (not (mira-solicitada-p sessao)))
    (setf (sessao-fase sessao) :combate)
    (assert (mira-solicitada-p sessao))
    (setf (soldado-recarga soldado) .8)
    (assert (not (mira-solicitada-p sessao))))
  (format t "Mira aprovada: 30/60/144 Hz, reversão, pausa, recarga e câmera compartilhada.~%"))

(defun capturar-animacao-mira (guerra-p)
  (assert (and (uiop:getenv "DISPLAY") (not (uiop:getenv "WAYLAND_DISPLAY"))))
  (let* ((pasta (merge-pathnames (format nil "rimefall-mira-~D/" (get-universal-time)) (uiop:temporary-directory)))
         (*pasta-dados* (merge-pathnames "dados/" pasta))
         (*pasta-configuracao* (merge-pathnames "preferencias/" pasta))
         (nomes '(processar-interface avancar-mira desenhar-interface))
         (originais (mapcar #'symbol-function nomes))
         (quadro -1) (preparado nil) (imagens nil)
         (etapa (if guerra-p "guerra" "demo")))
    (ensure-directories-exist pasta)
    (unwind-protect
         (progn
           ;; Um passo visual conhecido permite inspecionar os mesmos instantes
           ;; em máquinas diferentes; o teste numérico cobre as taxas reais.
           (setf (symbol-function 'avancar-mira)
                 (lambda (progresso mirando intervalo)
                   (declare (ignore intervalo))
                   (funcall (second originais) progresso mirando (/ 1.0 60))))
           (setf (symbol-function 'processar-interface)
                 (lambda (sessao estado janela)
                   (declare (ignore estado janela))
                   (incf quadro)
                   (unless preparado
                     (unless guerra-p
                       (setf sessao (nova-sessao)) (confirmar-notas sessao)
                       (setf (sessao-inimigos sessao) nil))
                     (setf preparado t))
                   (let ((mirando (or (<= 8 quadro 43) (>= quadro 63))))
                     (if guerra-p
                         (let ((j (jogador-local-guerra *guerra-atual*)))
                           (setf (jogador-guerra-mirando j) mirando)
                           (when (= quadro 85)
                             (decf (jogador-guerra-municao j)) (iniciar-recarga-guerra j)))
                         (progn
                           (setf (soldado-mirando (sessao-soldado sessao)) mirando)
                           (when (= quadro 85)
                             (decf (soldado-carregador (sessao-soldado sessao))) (iniciar-recarga sessao)))))
                   sessao))
           (setf (symbol-function 'desenhar-interface)
                 (lambda (sessao)
                   (funcall (third originais) sessao)
                   ;; A arma e o mundo já foram desenhados neste ponto.
                   (when (zerop (mod quadro 4))
                     (let ((arquivo (merge-pathnames (format nil "~A-~3,'0D.ppm" etapa quadro) pasta)))
                       (capturar-quadro arquivo 1280 720)
                       (push (namestring arquivo) imagens)))))
           (iniciar-jogo :guerra guerra-p :sem-audio t :quadros-maximos 112 :sincronizar nil
                         :largura 1280 :altura 720)
           (uiop:run-program
            (append (list "convert" "-delay" "7" "-loop" "0") (reverse imagens)
                    (list "-resize" "640x360" (namestring (asdf:system-relative-pathname "rimefall"
                                                          (format nil "validacao/mira-~A.gif" etapa)))))))
      (loop for nome in nomes for original in originais do (setf (symbol-function nome) original)))))

(verificar-transicao-mira)
(when (member "--grafico" (uiop:command-line-arguments) :test #'string=)
  (capturar-animacao-mira t)
  (capturar-animacao-mira nil))
